/* Numerical question generators for every CBSE Class 11 and 12 chapter, plus chapter pools.
   Each grid uses realistic textbook values; answers are computed, never typed in. */
(function () {
  const gen = G.gen, { pickQ } = G.qb, sig = G.sig;
  const PI = Math.PI, k = 9e9, e0 = 8.85e-12, mu0 = 4 * PI * 1e-7;
  const deg = d => d * PI / 180;

  /* ================= CLASS 12 ================= */
  // Ch1 Electric charges and fields
  gen("c12-1.coul", 2, [[1, 2, 3, 4, 5], [1, 2, 4, 8], [0.1, 0.2, 0.3, 0.5]], (q1, q2, r) => ({ q: `Charges of ${q1} μC and ${q2} μC are ${r} m apart in air. Find the force between them. (k = 9 × 10⁹ N m²/C²)`, v: k * q1 * q2 * 1e-12 / (r * r), u: "N", w: [k * q1 * q2 * 1e-12 / r, k * (q1 + q2) * 1e-6 / (r * r)], steps: [`F = kq₁q₂/r²`, `= 9 × 10⁹ × ${q1} × 10⁻⁶ × ${q2} × 10⁻⁶ / ${r}²`, `= ${sig(k * q1 * q2 * 1e-12 / (r * r))} N`], e: "Coulomb's law. Remember to convert μC to C and square the distance.", c: "Coulomb's law" }));
  gen("c12-1.scale", 3, [[2, 3, 4, 0.5], [2, 3, 0.5, 4]], (a, b) => ({ q: `Each of two charges is multiplied by ${a} and their separation is multiplied by ${b}. The force becomes how many times the original?`, v: a * a / (b * b), u: "×", w: [a / b, a * a / b, a / (b * b)], e: "F ∝ q₁q₂/r², so the factor is a²/b².", c: "Coulomb's law" }));
  gen("c12-1.field", 2, [[1, 2, 5, 10], [0.05, 0.1, 0.3, 0.5]], (q, r) => ({ q: `Find the electric field ${r} m from a ${q} nC point charge.`, v: k * q * 1e-9 / (r * r), u: "N/C", w: [k * q * 1e-9 / r, k * q * 1e-9 * r * r], e: "E = kq/r².", c: "electric field" }));
  gen("c12-1.gauss", 2, [[1, 2, 4.425, 8.85, 17.7]], q => ({ q: `A closed surface encloses ${q} nC of charge. What is the total electric flux through it? (ε₀ = 8.85 × 10⁻¹² C²/N m²)`, v: q * 1e-9 / e0, u: "N m²/C", w: [q * 1e-9 * e0, q / e0], e: "Gauss's law: Φ = q_enclosed/ε₀. The shape of the surface does not matter.", c: "electric flux" }));
  // Ch2 Potential and capacitance
  gen("c12-2.V", 2, [[1, 2, 5, 10], [0.03, 0.09, 0.18, 0.45]], (q, r) => ({ q: `Find the electric potential ${r} m from a ${q} nC charge.`, v: k * q * 1e-9 / r, u: "V", w: [k * q * 1e-9 / (r * r), q / r], e: "V = kq/r. Potential falls as 1/r, field as 1/r².", c: "electric potential" }));
  gen("c12-2.C", 2, [[0.01, 0.02, 0.05, 0.1], [0.5, 1, 2], [1, 2, 5]], (A, d, K) => ({ q: `A parallel plate capacitor has plates of area ${A} m², ${d} mm apart, filled with a dielectric of K = ${K}. Find C.`, v: K * e0 * A / (d * 1e-3) * 1e12, u: "pF", w: [e0 * A / (d * 1e-3) * 1e12, K * e0 * A / d * 1e12], steps: [`C = Kε₀A/d`, `= ${K} × 8.85 × 10⁻¹² × ${A} / ${d} × 10⁻³`, `= ${sig(K * e0 * A / (d * 1e-3) * 1e12)} pF`], e: "More area or a better dielectric increases C; a bigger gap decreases it.", c: "capacitance" }));
  gen("c12-2.U", 2, [[1, 5, 10, 50, 100], [10, 50, 100, 200]], (C, V) => ({ q: `A ${C} μF capacitor is charged to ${V} V. How much energy does it store?`, v: 0.5 * C * 1e-6 * V * V, u: "J", w: [C * 1e-6 * V * V, 0.5 * C * 1e-6 * V], e: "U = ½CV².", c: "capacitance" }));
  gen("c12-2.comb", 2, [[1, 2, 3, 4, 6], [2, 3, 4, 6, 12], ["series", "parallel"]], (a, b, m) => ({ q: `Find the equivalent capacitance of ${a} μF and ${b} μF in ${m}.`, v: m === "series" ? a * b / (a + b) : a + b, u: "μF", w: [m === "series" ? a + b : a * b / (a + b)], e: "Capacitors: parallel add directly; series combine like resistors in parallel (1/C = 1/C₁ + 1/C₂). The opposite of resistors!", c: "capacitance" }));
  // Ch3 Current electricity
  gen("c12-3.cell", 2, [[1.5, 6, 9, 12, 24], [0.1, 0.5, 1, 2], [2, 5, 10, 20]], (E, r, R) => { const I = E / (R + r); return { q: `A cell of emf ${E} V and internal resistance ${r} Ω drives a ${R} Ω resistor. Find the terminal voltage.`, v: E - I * r, u: "V", w: [E, I * r, E * R / r], steps: [`I = ε/(R + r) = ${E}/${R + r} = ${sig(I)} A`, `V = ε − Ir = ${E} − ${sig(I)} × ${r}`, `V = ${sig(E - I * r)} V`], e: "Some of the emf is 'used up' inside the cell itself.", c: "emf" }; });
  gen("c12-3.par", 2, [[2, 3, 4, 6, 10], [3, 6, 12, 15, 20]], (a, b) => ({ q: `Resistors of ${a} Ω and ${b} Ω are connected in parallel. Find the equivalent resistance.`, v: a * b / (a + b), u: "Ω", w: [a + b, (a + b) / 2], e: "1/R = 1/R₁ + 1/R₂. A parallel combination is always smaller than the smallest resistor.", c: "resistance" }));
  gen("c12-3.P", 1, [[6, 12, 24, 230], [2, 4, 10, 50]], (V, R) => ({ q: `A ${R} Ω resistor is connected across ${V} V. What power does it use?`, v: V * V / R, u: "W", w: [V / R, V * R], e: "P = V²/R = I²R = VI.", c: "power" }));
  gen("c12-3.stretch", 3, [[2, 3, 4]], n => ({ q: `A wire is stretched to ${n} times its original length (volume stays constant). Its resistance becomes how many times larger?`, v: n * n, u: "×", w: [n, n * n * n], e: "Length × n and area ÷ n, so R = ρL/A becomes n² times.", c: "resistivity" }));
  gen("c12-3.wheat", 2, [[5, 10, 20], [10, 20, 40], [15, 25, 30]], (P, Q, R) => ({ q: `A Wheatstone bridge is balanced with P = ${P} Ω, Q = ${Q} Ω and R = ${R} Ω. Find S.`, v: Q * R / P, u: "Ω", w: [P * R / Q, P * Q / R], e: "At balance P/Q = R/S.", c: "resistance" }));
  // Ch4 Moving charges
  const PT = [["proton", 1.67e-27, 1.6e-19], ["electron", 9.11e-31, 1.6e-19], ["alpha particle", 6.64e-27, 3.2e-19]];
  gen("c12-4.r", 3, [PT, [1e5, 1e6, 3e6], [0.1, 0.5, 1]], (p, v, B) => { const r = p[1] * v / (p[2] * B); return { q: `A ${p[0]} moves at ${sig(v)} m/s perpendicular to a ${B} T field. Find the radius of its circular path.`, v: r * 100, u: "cm", w: [p[2] * B / (p[1] * v) * 100, r * 1000], e: "r = mv/qB.", steps: [`r = mv/qB = (${p[1]} × ${sig(v)})/(${p[2]} × ${B})`, `r = ${sig(r)} m = ${sig(r * 100)} cm`], c: "magnetic field" }; });
  gen("c12-4.sol", 2, [[500, 1000, 2000, 5000], [0.5, 1, 2, 5]], (n, I) => ({ q: `A long solenoid has ${n} turns per metre and carries ${I} A. Find B inside it.`, v: mu0 * n * I * 1000, u: "mT", w: [mu0 * n * I, mu0 * I / (2 * PI) * 1000], fmt: x => sig(x), e: "B = μ₀nI, uniform inside a long solenoid.", c: "magnetic field" }));
  gen("c12-4.wire", 2, [[1, 5, 10, 20], [0.01, 0.05, 0.1]], (I, r) => ({ q: `Find the magnetic field ${r * 100} cm from a long straight wire carrying ${I} A.`, v: mu0 * I / (2 * PI * r) * 1e6, u: "μT", w: [mu0 * I / (2 * r) * 1e6, mu0 * I / (2 * PI * r * r) * 1e6], e: "B = μ₀I/2πr. Earth's field is about 50 μT for comparison.", c: "magnetic field" }));
  gen("c12-4.loop", 2, [[1, 2, 5, 10], [0.05, 0.1, 0.2], [1, 10, 50]], (I, R, N) => ({ q: `A circular coil of ${N} turn(s) and radius ${R * 100} cm carries ${I} A. Find B at its centre.`, v: N * mu0 * I / (2 * R) * 1e6, u: "μT", w: [N * mu0 * I / (2 * PI * R) * 1e6, mu0 * I / (2 * R) * 1e6], e: "B = μ₀NI/2R.", c: "magnetic field" }));
  // Ch5 Magnetism and matter
  gen("c12-5.tau", 2, [[0.2, 0.5, 1, 2], [0.1, 0.2, 0.5], [30, 45, 60, 90]], (m, B, th) => ({ q: `A magnet of moment ${m} A m² sits at ${th}° to a ${B} T field. Find the torque on it.`, v: m * B * Math.sin(deg(th)), u: "N m", w: [m * B * Math.cos(deg(th)), m * B], e: "τ = mB sin θ, largest at 90°.", c: "torque" }));
  gen("c12-5.W", 3, [[0.2, 0.5, 1], [0.1, 0.4]], (m, B) => ({ q: `How much work turns a magnet of moment ${m} A m² from aligned to exactly opposite a ${B} T field?`, v: 2 * m * B, u: "J", w: [m * B, 0], e: "W = U(180°) − U(0°) = mB − (−mB) = 2mB.", c: "magnetic field" }));
  gen("c12-5.type", 1, [[["bismuth", "diamagnetic"], ["water", "diamagnetic"], ["copper", "diamagnetic"], ["aluminium", "paramagnetic"], ["oxygen gas", "paramagnetic"], ["iron", "ferromagnetic"], ["nickel", "ferromagnetic"], ["cobalt", "ferromagnetic"], ["a superconductor", "perfectly diamagnetic"]]], m => pickQ({ q: `What kind of magnetic material is ${m[0]}?`, right: m[1], pool: ["diamagnetic", "paramagnetic", "ferromagnetic", "perfectly diamagnetic"], e: "Dia: weakly repelled. Para: weakly attracted. Ferro: strongly attracted and can be magnetised. Superconductors expel the field completely.", c: "magnetic field" }));
  // Ch6 EMI
  gen("c12-6.blv", 1, [[0.1, 0.2, 0.5, 1], [0.5, 1, 2], [2, 5, 10]], (B, l, v) => ({ q: `A ${l} m rod moves at ${v} m/s perpendicular to a ${B} T field. Find the induced emf.`, v: B * l * v, u: "V", w: [B * l / v, B * v], e: "Motional emf ε = Blv.", c: "electromagnetic induction" }));
  gen("c12-6.far", 2, [[10, 50, 100, 500], [1, 2, 5, 10], [0.01, 0.05, 0.1, 0.5]], (N, dphi, dt) => ({ q: `The flux through each turn of a ${N}-turn coil changes by ${dphi} mWb in ${dt} s. Find the average induced emf.`, v: N * dphi * 1e-3 / dt, u: "V", w: [dphi * 1e-3 / dt, N * dphi * dt * 1e-3], e: "ε = N ΔΦ/Δt (Lenz's law gives the direction).", c: "electromagnetic induction" }));
  gen("c12-6.UL", 2, [[0.1, 0.5, 1, 2], [1, 2, 3, 5]], (L, I) => ({ q: `How much energy is stored in a ${L} H inductor carrying ${I} A?`, v: 0.5 * L * I * I, u: "J", w: [L * I * I, 0.5 * L * I], e: "U = ½LI², just like ½mv².", c: "inductance" }));
  // Ch7 AC
  gen("c12-7.XL", 2, [[0.01, 0.05, 0.1, 0.5], [50, 60, 100, 1000]], (L, f) => ({ q: `Find the reactance of a ${L} H inductor at ${f} Hz.`, v: 2 * PI * f * L, u: "Ω", w: [f * L, 1 / (2 * PI * f * L)], e: "X_L = 2πfL, rising with frequency.", c: "reactance" }));
  gen("c12-7.XC", 2, [[1, 10, 50, 100], [50, 100, 1000]], (C, f) => ({ q: `Find the reactance of a ${C} μF capacitor at ${f} Hz.`, v: 1 / (2 * PI * f * C * 1e-6), u: "Ω", w: [2 * PI * f * C * 1e-6, 1 / (f * C * 1e-6)], e: "X_C = 1/2πfC, falling with frequency. Infinite for DC.", c: "reactance" }));
  gen("c12-7.rms", 1, [[110, 120, 220, 230, 240]], V => ({ q: `A mains supply is ${V} V rms. What is its peak voltage?`, v: V * Math.SQRT2, u: "V", w: [V / Math.SQRT2, V * 2], e: "V₀ = √2 × V_rms.", c: "reactance" }));
  gen("c12-7.tr", 2, [[220, 230, 11000], [6, 12, 24, 110], [500, 1000, 2000]], (Vp, Vs, Np) => ({ q: `An ideal transformer steps ${Vp} V down to ${Vs} V. The primary has ${Np} turns. How many turns does the secondary have?`, v: Np * Vs / Vp, u: "turns", w: [Np * Vp / Vs, Np], fmt: x => x >= 10 ? String(Math.round(x)) : sig(x), e: "V_s/V_p = N_s/N_p.", c: "electromagnetic induction" }));
  gen("c12-7.res", 3, [[1, 10, 100], [0.1, 1, 10]], (L, C) => ({ q: `A series LCR circuit has L = ${L} mH and C = ${C} μF. Find its resonant frequency.`, v: 1 / (2 * PI * Math.sqrt(L * 1e-3 * C * 1e-6)), u: "Hz", w: [1 / Math.sqrt(L * 1e-3 * C * 1e-6), 2 * PI * Math.sqrt(L * C)], e: "f₀ = 1/(2π√LC).", c: "impedance" }));
  // Ch8 EM waves
  const WL = [["FM radio", 3], ["mobile 4G", 0.16], ["Wi-Fi", 0.125], ["microwave oven", 0.122], ["hydrogen 21 cm line", 0.21], ["TV remote infrared", 9.4e-7], ["green light", 5.5e-7], ["UV-C lamp", 2.54e-7], ["medical X-ray", 1e-10]];
  gen("c12-8.f", 2, [WL], w => ({ q: `${w[0]} uses waves of wavelength about ${G.fmt(w[1])} m. Find the frequency.`, v: 3e8 / w[1], u: "Hz", w: [w[1] * 3e8, 3e8 / w[1] / 1000], e: "c = fλ, so f = c/λ.", c: "electromagnetic wave" }));
  gen("c12-8.band", 1, [WL], w => { const lg = Math.log10(w[1]); const b = lg < -11 ? "gamma rays" : lg < -8 ? "X-rays" : w[1] < 4e-7 ? "ultraviolet" : w[1] <= 7e-7 ? "visible light" : w[1] < 1e-3 ? "infrared" : w[1] < 0.1 ? "microwaves" : "radio waves"; return pickQ({ q: `${w[0]} (λ ≈ ${G.fmt(w[1])} m) belongs to which part of the spectrum?`, right: b, pool: ["gamma rays", "X-rays", "ultraviolet", "visible light", "infrared", "microwaves", "radio waves"], e: "NCERT ranges: radio > 0.1 m, microwaves 0.1 m to 1 mm, infrared 1 mm to 700 nm, visible 700 to 400 nm, UV 400 nm to 1 nm, X-rays 1 nm to 10⁻³ nm.", c: "electromagnetic spectrum" }); });
  gen("c12-8.B", 2, [[3, 15, 30, 60, 300]], E => ({ q: `An EM wave has electric field amplitude ${E} V/m. Find the magnetic field amplitude.`, v: E / 3e8, u: "T", w: [E * 3e8, E / 3e8 * 1000], e: "B₀ = E₀/c.", c: "electromagnetic wave" }));
  // Ch9 Ray optics
  gen("c12-9.lens", 2, [[10, 15, 20], [12, 25, 30, 40, 60]], (f, u) => { if (u === f) u = f + 5; const v = 1 / (1 / f - 1 / u); return { q: `An object is ${u} cm in front of a convex lens of focal length ${f} cm. Find the image distance v (Cartesian signs: + means on the far side of the lens).`, v: v, u: "cm", w: [1 / (1 / f + 1 / u), -v, u - f], fmt: x => (x > 0 ? "+" : "") + sig(x), e: v > 0 ? "A real, inverted image forms on the far side." : "The object is inside the focal length, so the image is virtual, upright and on the same side (this is how a magnifying glass works).", steps: [`1/v − 1/u = 1/f with u = −${u} cm, f = +${f} cm`, `1/v = 1/${f} − 1/${u}`, `v = ${sig(v)} cm, m = v/u = ${sig(-v / u)}`], c: "lens formula" }; });
  gen("c12-9.P", 1, [[10, 20, 25, 40, 50, 100, -25, -50]], f => ({ q: `Find the power of a lens of focal length ${f} cm.`, v: 100 / f, u: "D", w: [f / 100, 1 / f], fmt: x => (x > 0 ? "+" : "") + sig(x), e: "P = 1/f with f in metres. Convex lenses have positive power.", c: "focal length" }));
  gen("c12-9.crit", 2, [[1.33, 1.5, 1.65, 2.42]], n => ({ q: `Find the critical angle for a material of refractive index ${n} (to air).`, v: Math.asin(1 / n) * 180 / PI, u: "°", w: [Math.acos(1 / n) * 180 / PI, 90 / n], fmt: x => x.toFixed(1), e: `sin c = 1/n. ${n === 2.42 ? "This is diamond: its tiny critical angle traps light and makes it sparkle." : ""}`, c: "total internal reflection" }));
  gen("c12-9.tel", 2, [[50, 100, 150, 200], [2.5, 5, 10]], (fo, fe) => ({ q: `A telescope has an objective of focal length ${fo} cm and an eyepiece of ${fe} cm. Find its magnifying power in normal adjustment.`, v: fo / fe, u: "×", w: [fe / fo, fo * fe], e: "m = f₀/fₑ, and the tube length is f₀ + fₑ.", c: "focal length" }));
  gen("c12-9.mirror", 3, [[10, 15, 20], [30, 40, 60]], (f, u) => { const v = 1 / (1 / f - 1 / u); return { q: `An object is ${u} cm in front of a concave mirror of focal length ${f} cm. How far from the mirror is the image?`, v: v, u: "cm (in front, real)", w: [1 / (1 / f + 1 / u), u + f], e: "Mirror formula 1/v + 1/u = 1/f with u = −" + u + ", f = −" + f + ".", c: "focal length" }; });
  // Ch10 Wave optics
  gen("c12-10.beta", 2, [[450, 500, 600, 650], [0.2, 0.5, 1], [1, 1.5, 2]], (l, d, D) => ({ q: `In Young's experiment λ = ${l} nm, d = ${d} mm and D = ${D} m. Find the fringe width.`, v: l * 1e-9 * D / (d * 1e-3) * 1e3, u: "mm", w: [l * 1e-9 * d * 1e-3 / D * 1e3, l * 1e-9 / (d * 1e-3) * 1e3], e: "β = λD/d.", c: "interference" }));
  gen("c12-10.malus", 2, [[0, 30, 45, 60, 90]], th => ({ q: `Unpolarised light of intensity I₀ passes through a polariser and then an analyser at ${th}° to it. What fraction of I₀ gets through?`, v: 0.5 * Math.pow(Math.cos(deg(th)), 2), fmt: x => x === 0 ? "0" : sig(x), u: "I₀", w: [Math.pow(Math.cos(deg(th)), 2), 0.5 * Math.cos(deg(th))].map(x => x || 0.25), e: "The first polariser halves it; Malus's law multiplies by cos²θ.", c: "polarization" }));
  gen("c12-10.res", 3, [[0.1, 0.5, 2.4, 6.5, 10], [500]], (D, l) => ({ q: `A telescope has an aperture of ${D} m. Find its smallest resolvable angle at ${l} nm (θ ≈ 1.22λ/D).`, v: 1.22 * l * 1e-9 / D, u: "rad", w: [l * 1e-9 / D, 1.22 * D / (l * 1e-9)], e: "Bigger aperture, finer detail. JWST is 6.5 m.", c: "diffraction" }));
  // Ch11 Dual nature
  gen("c12-11.E", 1, [[200, 300, 400, 500, 600, 700]], l => ({ q: `Find the energy of a photon of wavelength ${l} nm.`, v: 1240 / l, u: "eV", w: [l / 1240, 1240 * l], e: "E = hc/λ ≈ 1240 eV nm / λ.", c: "photon" }));
  gen("c12-11.K", 2, [[2.1, 2.3, 4.3, 4.7], [200, 250, 300, 400]], (phi, l) => { const K = 1240 / l - phi; return K > 0 ? { q: `Light of ${l} nm falls on a metal with work function ${phi} eV. Find the maximum kinetic energy of the photoelectrons.`, v: K, u: "eV", w: [1240 / l, 1240 / l + phi], e: "K_max = hc/λ − φ.", steps: [`E = 1240/${l} = ${sig(1240 / l)} eV`, `K = ${sig(1240 / l)} − ${phi} = ${sig(K)} eV`], c: "photoelectric effect" } : { q: `Light of ${l} nm falls on a metal with work function ${phi} eV. What happens?`, o: ["No electrons are emitted, however bright the light", "Electrons come out slowly", "Electrons come out only if the light is bright", "The metal heats up and emits after a delay"], a: 0, e: `Each photon has only ${sig(1240 / l)} eV, less than φ = ${phi} eV.`, c: "photoelectric effect" }; });
  gen("c12-11.deb", 2, [[25, 50, 100, 150, 400, 10000]], V => ({ q: `Find the de Broglie wavelength of an electron accelerated through ${V} V.`, v: 1.227 / Math.sqrt(V), u: "nm", w: [1.227 / V, 1.227 * Math.sqrt(V)], e: "λ = 1.227/√V nm for electrons (non-relativistic).", c: "de Broglie wavelength" }));
  gen("c12-11.thr", 2, [[2.1, 2.3, 4.3, 4.7, 5.6]], phi => ({ q: `A metal has work function ${phi} eV. Find its threshold wavelength.`, v: 1240 / phi, u: "nm", w: [phi * 1240 / 1000, 1240 * phi], e: "λ₀ = hc/φ. Longer wavelengths cannot eject electrons.", c: "work function" }));
  // Ch12 Atoms
  const TR = []; for (let a = 2; a <= 6; a++) for (let b = 1; b < a; b++) TR.push([a, b]);
  gen("c12-12.lam", 2, [TR], ([a, b]) => { const E = 13.6 * (1 / (b * b) - 1 / (a * a)); return { q: `An electron in hydrogen drops from n = ${a} to n = ${b}. Find the wavelength of the photon.`, v: 1240 / E, u: "nm", w: [1240 / (13.6 / (a * a)), 1240 / (13.6 / (b * b))], e: `ΔE = 13.6(1/${b}² − 1/${a}²) = ${sig(E)} eV. ${b === 1 ? "Lyman series (UV)." : b === 2 ? "Balmer series (visible)." : "Infrared series."}`, c: "spectral line" }; });
  gen("c12-12.En", 1, [[1, 2, 3, 4, 5, 6]], n => ({ q: `What is the energy of hydrogen's electron in level n = ${n}?`, v: -13.6 / (n * n), u: "eV", w: [-13.6 / n, 13.6 / (n * n)], fmt: x => sig(x), e: "E_n = −13.6/n² eV.", c: "Bohr model" }));
  gen("c12-12.rn", 1, [[1, 2, 3, 4, 5]], n => ({ q: `Find the radius of hydrogen's orbit n = ${n}.`, v: 0.53 * n * n, u: "Å", w: [0.53 * n, 0.53 / n], e: "r_n = 0.53 n² Å.", c: "Bohr model" }));
  gen("c12-12.series", 1, [TR], ([a, b]) => pickQ({ q: `The jump n = ${a} → n = ${b} in hydrogen belongs to which series?`, right: ["", "Lyman", "Balmer", "Paschen", "Brackett", "Pfund"][b], pool: ["Lyman", "Balmer", "Paschen", "Brackett", "Pfund"], e: "The series is named by the level it ends on: 1 Lyman, 2 Balmer, 3 Paschen, 4 Brackett, 5 Pfund.", c: "spectral line" }));
  // Ch13 Nuclei
  gen("c12-13.R", 2, [[1, 8, 27, 64, 125, 216]], A => ({ q: `Estimate the radius of a nucleus with mass number ${A}. (R₀ = 1.2 fm)`, v: 1.2 * Math.cbrt(A), u: "fm", w: [1.2 * A, 1.2 * Math.sqrt(A)], e: "R = R₀A^(1/3).", c: "nucleus" }));
  gen("c12-13.E", 2, [[0.001, 0.01, 0.02, 0.03, 0.2]], dm => ({ q: `A nuclear reaction has a mass defect of ${dm} u. How much energy is released? (1 u = 931.5 MeV)`, v: dm * 931.5, u: "MeV", w: [dm / 931.5, dm * 931.5 * 1000], e: "E = Δm × 931.5 MeV/u.", c: "mass defect" }));
  gen("c12-13.pern", 2, [[["²H", 2, 2.22], ["⁴He", 4, 28.3], ["¹²C", 12, 92.2], ["¹⁶O", 16, 127.6], ["⁵⁶Fe", 56, 492.3], ["²³⁵U", 235, 1784]]], n => ({ q: `${n[0]} has a total binding energy of ${n[2]} MeV. Find its binding energy per nucleon.`, v: n[2] / n[1], u: "MeV", w: [n[2] * n[1], n[2]], e: "E_b/A. Iron-56 is near the top of the curve (about 8.8 MeV).", c: "binding energy" }));
  // Ch14 Semiconductors
  gen("c12-14.rect", 1, [[50, 60, 100], ["half-wave", "full-wave"]], (f, t) => ({ q: `A ${t} rectifier is fed ${f} Hz AC. What is the frequency of the output ripple?`, v: t === "full-wave" ? 2 * f : f, u: "Hz", w: [t === "full-wave" ? f : 2 * f, f / 2], e: "Half-wave: one pulse per cycle. Full-wave: two pulses per cycle.", c: "rectifier" }));
  gen("c12-14.dope", 1, [[["phosphorus", "n-type", "electrons"], ["arsenic", "n-type", "electrons"], ["antimony", "n-type", "electrons"], ["boron", "p-type", "holes"], ["aluminium", "p-type", "holes"], ["gallium", "p-type", "holes"], ["indium", "p-type", "holes"]]], d => pickQ({ q: `Pure silicon is doped with ${d[0]}. What kind of semiconductor results, and what are its majority carriers?`, right: `${d[1]}, ${d[2]}`, pool: ["n-type, electrons", "p-type, holes", "n-type, holes", "p-type, electrons"], e: "Pentavalent (group 15) atoms donate electrons: n-type. Trivalent (group 13) atoms create holes: p-type.", c: "semiconductor" }));
  gen("c12-14.bias", 1, [[["p-side to +, n-side to −", "forward bias: current flows, depletion layer narrows"], ["p-side to −, n-side to +", "reverse bias: almost no current, depletion layer widens"]]], b => pickQ({ q: `A p-n junction diode is connected with ${b[0]}. What happens?`, right: b[1], pool: ["forward bias: current flows, depletion layer narrows", "reverse bias: almost no current, depletion layer widens", "it breaks down immediately", "current flows equally both ways"], e: "Forward bias pushes carriers towards the junction and shrinks the barrier.", c: "p-n junction" }));

  /* ================= CLASS 11 ================= */
  gen("c11-1.kmh", 1, [[18, 36, 54, 72, 90, 108, 144]], v => ({ q: `Convert ${v} km/h into m/s.`, v: v / 3.6, u: "m/s", w: [v * 3.6, v / 36], e: "Divide by 3.6 (1000 m ÷ 3600 s).", c: "units" }));
  gen("c11-1.dim", 2, [[["force", "M L T⁻²"], ["energy", "M L² T⁻²"], ["power", "M L² T⁻³"], ["pressure", "M L⁻¹ T⁻²"], ["momentum", "M L T⁻¹"], ["G (gravitational constant)", "M⁻¹ L³ T⁻²"], ["Planck's constant h", "M L² T⁻¹"], ["impulse", "M L T⁻¹"], ["surface tension", "M T⁻²"], ["torque", "M L² T⁻²"]]], d => pickQ({ q: `What are the dimensions of ${d[0]}?`, right: d[1], pool: ["M L T⁻²", "M L² T⁻²", "M L² T⁻³", "M L⁻¹ T⁻²", "M L T⁻¹", "M⁻¹ L³ T⁻²", "M L² T⁻¹", "M T⁻²"], e: "Build it from a defining formula, e.g. F = ma gives M × L T⁻².", c: "dimension" }));
  gen("c11-1.sig", 1, [[["0.00340", 3], ["2.500", 4], ["6.02 × 10²³", 3], ["1200.", 4], ["0.050", 2], ["3.0080", 5], ["45", 2]]], s => ({ q: `How many significant figures are in ${s[0]}?`, v: s[1], w: [s[1] + 1, s[1] - 1, s[1] + 2], fmt: x => String(x), e: "Leading zeros never count; zeros between digits always count; trailing zeros count after a decimal point.", c: "precision" }));
  gen("c11-2.vuat", 1, [[0, 5, 10], [1, 2, 3], [4, 5, 10]], (u, a, t) => ({ q: `A car starts at ${u} m/s and accelerates at ${a} m/s² for ${t} s. Find its final velocity.`, v: u + a * t, u: "m/s", w: [u * t + 0.5 * a * t * t, a * t], e: "v = u + at.", c: "acceleration" }));
  gen("c11-2.s", 2, [[0, 5, 10], [1, 2, 4], [4, 5, 10]], (u, a, t) => ({ q: `Starting at ${u} m/s with acceleration ${a} m/s², how far does a body travel in ${t} s?`, v: u * t + 0.5 * a * t * t, u: "m", w: [u * t + a * t * t, u + a * t], e: "s = ut + ½at².", c: "displacement" }));
  gen("c11-2.stop", 2, [[10, 20, 30, 40], [2, 4, 5, 8]], (v, a) => ({ q: `A car moving at ${v} m/s brakes with a deceleration of ${a} m/s². Find its stopping distance.`, v: v * v / (2 * a), u: "m", w: [v * v / a, v / a], e: "0 = v² − 2as ⇒ s = v²/2a. Double speed, four times the distance.", c: "acceleration" }));
  gen("c11-2.fall", 1, [[5, 20, 45, 80, 125]], h => ({ q: `A stone is dropped from ${h} m. How long does it take to hit the ground? (g = 10 m/s²)`, v: Math.sqrt(2 * h / 10), u: "s", w: [2 * h / 10, h / 10], e: "h = ½gt² ⇒ t = √(2h/g).", c: "acceleration due to gravity" }));
  gen("c11-2.rel", 1, [[40, 60, 80], [30, 50, 70], ["towards", "the same direction as"]], (a, b, d) => ({ q: `Two trains move at ${a} km/h and ${b} km/h, travelling ${d} each other. What is their relative speed?`, v: d === "towards" ? a + b : Math.abs(a - b), u: "km/h", w: [d === "towards" ? Math.abs(a - b) : a + b, (a + b) / 2], e: "Opposite directions: add. Same direction: subtract.", c: "velocity" }));
  gen("c11-3.R", 2, [[10, 20, 30, 40], [15, 30, 45, 60, 75]], (u, th) => ({ q: `A projectile is launched at ${u} m/s at ${th}°. Find its range. (g = 10 m/s²)`, v: u * u * Math.sin(deg(2 * th)) / 10, u: "m", w: [u * u * Math.sin(deg(th)) / 10, u * u / 10], e: "R = u² sin 2θ / g.", c: "projectile motion" }));
  gen("c11-3.H", 2, [[10, 20, 30], [30, 45, 60, 90]], (u, th) => ({ q: `A ball is thrown at ${u} m/s at ${th}° to the ground. Find its maximum height. (g = 10 m/s²)`, v: u * u * Math.pow(Math.sin(deg(th)), 2) / 20, u: "m", w: [u * u * Math.sin(deg(th)) / 20, u * u / 20 * Math.sin(deg(2 * th))], e: "H = u² sin²θ / 2g.", c: "projectile motion" }));
  gen("c11-3.T", 2, [[10, 20, 30], [30, 45, 60]], (u, th) => ({ q: `Find the time of flight for a projectile at ${u} m/s and ${th}°. (g = 10 m/s²)`, v: 2 * u * Math.sin(deg(th)) / 10, u: "s", w: [u * Math.sin(deg(th)) / 10, 2 * u / 10], e: "T = 2u sin θ / g.", c: "projectile motion" }));
  gen("c11-3.vec", 1, [[3, 5, 6, 8], [4, 12, 8, 6]], (a, b) => ({ q: `Two perpendicular displacements of ${a} m and ${b} m are added. Find the size of the resultant.`, v: Math.hypot(a, b), u: "m", w: [a + b, Math.abs(a - b)], e: "Pythagoras: R = √(a² + b²).", c: "vector" }));
  gen("c11-4.a", 2, [[20, 30, 50], [2, 5, 10], [0, 0.1, 0.2]], (F, m, mu) => { const f = mu * m * 10, a = Math.max(0, (F - f) / m); return { q: `A ${F} N force pushes a ${m} kg block on a floor with μ = ${mu}. Find the acceleration. (g = 10 m/s²)`, v: a, u: "m/s²", w: [F / m, (F + f) / m].map(x => x || 1), fmt: x => x === 0 ? "0" : sig(x), e: `Friction = μmg = ${sig(f)} N.`, c: "friction" }; });
  gen("c11-4.lift", 2, [[40, 50, 60], [1, 2, 5], ["up", "down"]], (m, a, d) => ({ q: `A ${m} kg person stands on a scale in a lift accelerating ${d} at ${a} m/s². What does the scale read (in newtons)? (g = 10 m/s²)`, v: m * (10 + (d === "up" ? a : -a)), u: "N", w: [m * 10, m * (10 + (d === "up" ? -a : a))], e: "Apparent weight = m(g + a) going up, m(g − a) going down.", c: "weight" }));
  gen("c11-4.imp", 2, [[0.15, 0.4, 1], [10, 20, 30], [0.01, 0.1, 0.5]], (m, v, t) => ({ q: `A ${m} kg ball at ${v} m/s is caught and stopped in ${t} s. Find the average force on the hands.`, v: m * v / t, u: "N", w: [m * v * t, m * v], e: "F = Δp/Δt. Pulling the hands back increases t and lowers F.", c: "impulse" }));
  gen("c11-4.bank", 3, [[10, 15, 20], [50, 100, 200]], (v, r) => ({ q: `At what angle should a road of radius ${r} m be banked for ${v} m/s with no friction needed? (g = 10 m/s²)`, v: Math.atan(v * v / (r * 10)) * 180 / PI, u: "°", w: [Math.atan(r * 10 / (v * v)) * 180 / PI, v * v / (r * 10) * 90], fmt: x => x.toFixed(1), e: "tan θ = v²/rg.", c: "centripetal force" }));
  gen("c11-5.KE", 1, [[0.5, 2, 10, 60, 1000], [2, 5, 10, 20]], (m, v) => ({ q: `Find the kinetic energy of a ${m} kg object moving at ${v} m/s.`, v: 0.5 * m * v * v, u: "J", w: [m * v * v, 0.5 * m * v], e: "K = ½mv².", c: "kinetic energy" }));
  gen("c11-5.drop", 2, [[5, 20, 45, 80], [1, 2, 5]], (h, m) => ({ q: `A ${m} kg ball falls from ${h} m. Find its speed just before landing. (g = 10 m/s², no air)`, v: Math.sqrt(20 * h), u: "m/s", w: [20 * h, Math.sqrt(10 * h)], e: "mgh = ½mv² ⇒ v = √(2gh). The mass cancels!", c: "potential energy" }));
  gen("c11-5.P", 1, [[50, 100, 500], [5, 10, 20], [10, 20, 60]], (m, h, t) => ({ q: `A motor lifts ${m} kg through ${h} m in ${t} s. Find its power. (g = 10 m/s²)`, v: m * 10 * h / t, u: "W", w: [m * 10 * h, m * h / t], e: "P = mgh/t.", c: "power" }));
  gen("c11-5.W", 1, [[10, 20, 50], [2, 5, 10], [0, 30, 60, 90]], (F, s, th) => ({ q: `A ${F} N force moves a box ${s} m, acting at ${th}° to the motion. How much work is done?`, v: F * s * Math.cos(deg(th)), u: "J", w: [F * s, F * s * Math.sin(deg(th))].map(x => x || 1), fmt: x => Math.abs(x) < 1e-9 ? "0" : sig(x), e: "W = Fs cos θ. At 90° no work is done.", c: "work" }));
  gen("c11-6.tau", 1, [[10, 20, 50], [0.2, 0.5, 1], [30, 90]], (F, r, th) => ({ q: `A ${F} N force acts ${r} m from a hinge at ${th}° to the lever. Find the torque.`, v: F * r * Math.sin(deg(th)), u: "N m", w: [F * r * Math.cos(deg(th)), F / r].map(x => x || 1), e: "τ = rF sin θ.", c: "torque" }));
  gen("c11-6.L", 2, [[2, 4, 6], [5, 10], [0.5, 0.25]], (I, w, f) => ({ q: `A skater with I = ${I} kg m² spins at ${w} rad/s, then pulls in so I becomes ${f} of the original. Find the new spin rate.`, v: w / f, u: "rad/s", w: [w * f, w], e: "Angular momentum is conserved: I₁ω₁ = I₂ω₂.", c: "angular momentum" }));
  gen("c11-6.I", 2, [[["ring about its axis", 1], ["disc about its axis", 0.5], ["solid sphere about a diameter", 0.4], ["hollow sphere about a diameter", 2 / 3], ["rod about its centre (length L, use R = L)", 1 / 12]], [2, 5], [0.5, 1]], (b, M, R) => ({ q: `Find the moment of inertia of a ${M} kg ${b[0]}, radius ${R} m.`, v: b[1] * M * R * R, u: "kg m²", w: [M * R * R, M * R].filter(x => Math.abs(x - b[1] * M * R * R) > 1e-9), e: "Ring MR², disc ½MR², solid sphere ⅖MR², hollow sphere ⅔MR², rod about centre ML²/12.", c: "moment of inertia" }));
  gen("c11-7.gh", 2, [[0.25, 0.5, 1, 2]], x => ({ q: `At a height of ${x}R above Earth's surface, g becomes what fraction of its surface value?`, v: 1 / Math.pow(1 + x, 2), fmt: x2 => sig(x2), u: "g", w: [1 / (1 + x), 1 - 2 * x].map(v => v > 0 ? v : 0.3), e: "g' = g R²/(R + h)².", c: "acceleration due to gravity" }));
  gen("c11-7.gd", 2, [[0.25, 0.5, 0.75]], x => ({ q: `At a depth of ${x}R below Earth's surface, g becomes what fraction of its surface value?`, v: 1 - x, fmt: x2 => sig(x2), u: "g", w: [1 / Math.pow(1 - x, 2), 1 - 2 * x].map(v => v > 0 ? v : 0.1), e: "g_d = g(1 − d/R), zero at the centre.", c: "acceleration due to gravity" }));
  gen("c11-7.F", 2, [[["Earth and Moon", 5.97e24, 7.35e22, 3.84e8], ["Earth and Sun", 5.97e24, 1.99e30, 1.496e11], ["two 1000 kg cars 1 m apart", 1000, 1000, 1], ["you (50 kg) and Earth", 50, 5.97e24, 6.371e6]]], s => ({ q: `Find the gravitational force between ${s[0]}. (G = 6.67 × 10⁻¹¹)`, v: 6.67e-11 * s[1] * s[2] / (s[3] * s[3]), u: "N", w: [6.67e-11 * s[1] * s[2] / s[3], 6.67e-11 * s[1] / (s[3] * s[3])], e: "F = Gm₁m₂/r².", c: "universal gravitation" }));
  gen("c11-8.dL", 2, [[1, 2, 3], [1, 2], [100, 200, 500], [1e11, 2e11]], (L, A, F, Y) => ({ q: `A ${L} m wire of area ${A} mm² (Y = ${sig(Y)} Pa) is pulled by ${F} N. Find its extension.`, v: F * L / (A * 1e-6 * Y) * 1000, u: "mm", w: [F * L / (A * Y) * 1000, F / (A * 1e-6 * Y) * 1000], e: "ΔL = FL/(AY).", c: "stress" }));
  gen("c11-8.stress", 1, [[100, 500, 1000], [1, 2, 5]], (F, A) => ({ q: `A ${F} N load hangs from a wire of cross-section ${A} mm². Find the stress.`, v: F / (A * 1e-6), u: "Pa", w: [F * A * 1e-6, F / A], e: "Stress = F/A (convert mm² to m²).", c: "stress" }));
  gen("c11-9.P", 1, [[1, 5, 10, 50, 100], [["water", 1000], ["sea water", 1025], ["mercury", 13600]]], (h, f) => ({ q: `Find the extra pressure at a depth of ${h} m in ${f[0]}. (g = 10 m/s²)`, v: f[1] * 10 * h, u: "Pa", w: [f[1] * h, f[1] * 10 / h], e: "ΔP = ρgh.", c: "pressure" }));
  gen("c11-9.hyd", 1, [[5, 10, 20], [500, 1000, 2000], [50, 100, 200]], (a1, a2, F) => ({ q: `A hydraulic lift has pistons of ${a1} cm² and ${a2} cm². What load can a ${F} N effort lift?`, v: F * a2 / a1, u: "N", w: [F * a1 / a2, F * (a2 - a1)], e: "Pascal's law: F₁/A₁ = F₂/A₂.", c: "pressure" }));
  gen("c11-9.cont", 1, [[2, 3, 4], [1, 2, 5]], (r, v) => ({ q: `Water flows at ${v} m/s in a pipe that then narrows to 1/${r} of its area. Find the new speed.`, v: v * r, u: "m/s", w: [v / r, v], e: "A₁v₁ = A₂v₂.", c: "pressure" }));
  gen("c11-9.term", 3, [[0.5, 1, 2], [["glycerine", 1.4, 1260], ["castor oil", 0.99, 960]]], (r, l) => ({ q: `A steel ball (ρ = 7800 kg/m³) of radius ${r} mm falls through ${l[0]} (η = ${l[1]} Pa s, ρ = ${l[2]} kg/m³). Find its terminal velocity. (g = 9.8 m/s²)`, v: 2 * Math.pow(r * 1e-3, 2) * (7800 - l[2]) * 9.8 / (9 * l[1]) * 100, u: "cm/s", w: [2 * r * 1e-3 * (7800 - l[2]) * 9.8 / (9 * l[1]) * 100, 2 * Math.pow(r * 1e-3, 2) * 7800 * 9.8 / (9 * l[1]) * 100], e: "v_t = 2r²(ρ − σ)g / 9η.", c: "viscosity" }));
  gen("c11-10.Q", 1, [[0.5, 1, 2], [10, 20, 50, 80], [["water", 4186], ["aluminium", 900], ["copper", 385], ["iron", 450]]], (m, dT, s) => ({ q: `How much heat raises ${m} kg of ${s[0]} by ${dT} °C? (c = ${s[1]} J/kg K)`, v: m * s[1] * dT, u: "J", w: [m * s[1], s[1] * dT], e: "Q = mcΔT.", c: "heat" }));
  gen("c11-10.L", 1, [[0.1, 0.5, 1, 2], [["melt ice at 0 °C", 3.34e5], ["boil water at 100 °C", 2.256e6]]], (m, t) => ({ q: `How much heat is needed to ${t[0]} if the mass is ${m} kg? (L = ${G.fmt(t[1])} J/kg)`, v: m * t[1], u: "J", w: [t[1] / m, m * t[1] / 1000], e: "Q = mL. Temperature stays constant during the change.", c: "heat" }));
  gen("c11-10.exp", 2, [[1, 10, 100], [1.2e-5, 2.4e-5, 1.7e-5], [20, 40, 100]], (L, a, dT) => ({ q: `A ${L} m metal rod (α = ${sig(a)} /K) is heated by ${dT} K. Find its expansion.`, v: L * a * dT * 1000, u: "mm", w: [L * a * dT, a * dT * 1000], e: "ΔL = αLΔT.", c: "temperature" }));
  gen("c11-10.scale", 1, [[-40, 0, 25, 37, 100]], C => ({ q: `Convert ${C} °C to Fahrenheit.`, v: C * 9 / 5 + 32, u: "°F", w: [C * 5 / 9 + 32, C + 32], fmt: x => sig(x), e: "F = 9C/5 + 32. At −40 both scales agree.", c: "temperature" }));
  gen("c11-11.dU", 1, [[200, 500, 1000], [100, 200, 300]], (Q, W) => ({ q: `A gas absorbs ${Q} J of heat and does ${W} J of work. Find the change in its internal energy.`, v: Q - W, u: "J", w: [Q + W, W - Q], e: "First law: ΔU = Q − W (W done by the gas).", c: "internal energy" }));
  gen("c11-11.eta", 2, [[500, 1000, 2000], [0.3, 0.5, 0.6, 0.75]], (Q1, r) => ({ q: `A heat engine takes in ${Q1} J and rejects ${Q1 * r} J each cycle. Find its efficiency.`, v: (1 - r) * 100, u: "%", w: [r * 100, (1 - r) * 50], fmt: x => sig(x), e: "η = 1 − Q₂/Q₁.", c: "entropy" }));
  gen("c11-11.W", 1, [[1e5, 2e5], [1, 2, 5]], (P, dV) => ({ q: `A gas expands by ${dV} L at a constant pressure of ${sig(P)} Pa. Find the work done.`, v: P * dV * 1e-3, u: "J", w: [P * dV, P / dV * 1e-3], e: "W = PΔV (convert litres to m³).", c: "work" }));
  gen("c11-12.vrms", 2, [[["hydrogen", 0.002], ["helium", 0.004], ["nitrogen", 0.028], ["oxygen", 0.032], ["carbon dioxide", 0.044]], [100, 300, 1000]], (g, T) => ({ q: `Find the rms speed of ${g[0]} molecules at ${T} K. (R = 8.314 J/mol K)`, v: Math.sqrt(3 * 8.314 * T / g[1]), u: "m/s", w: [Math.sqrt(8.314 * T / g[1]), 3 * 8.314 * T / g[1]], e: "v_rms = √(3RT/M), with M in kg/mol.", c: "temperature" }));
  gen("c11-12.ratio", 2, [[2, 4, 9, 16]], n => ({ q: `If the absolute temperature of a gas is made ${n} times larger, its rms speed becomes how many times larger?`, v: Math.sqrt(n), u: "×", w: [n, n * n], e: "v_rms ∝ √T.", c: "temperature" }));
  gen("c11-12.KE", 2, [[100, 300, 1000, 5772]], T => ({ q: `Find the average kinetic energy of a gas molecule at ${T} K. (k = 1.38 × 10⁻²³ J/K)`, v: 1.5 * 1.38e-23 * T, u: "J", w: [1.38e-23 * T, 3 * 1.38e-23 * T], e: "KE = (3/2)kT, independent of the type of gas.", c: "temperature" }));
  const GW = [["Earth", 9.8], ["the Moon", 1.62], ["Mars", 3.71], ["Jupiter", 24.8]];
  gen("c11-13.pend", 2, [[0.25, 1, 2, 4], GW], (L, w) => ({ q: `Find the period of a ${L} m pendulum on ${w[0]} (g = ${w[1]} m/s²).`, v: 2 * PI * Math.sqrt(L / w[1]), u: "s", w: [2 * PI * Math.sqrt(w[1] / L), PI * Math.sqrt(L / w[1])], e: "T = 2π√(l/g). Mass does not matter.", c: "simple harmonic motion" }));
  gen("c11-13.spring", 2, [[0.1, 0.5, 1, 2], [10, 50, 100, 200]], (m, kk) => ({ q: `A ${m} kg mass on a spring of k = ${kk} N/m oscillates. Find its period.`, v: 2 * PI * Math.sqrt(m / kk), u: "s", w: [2 * PI * Math.sqrt(kk / m), Math.sqrt(m / kk)], e: "T = 2π√(m/k).", c: "simple harmonic motion" }));
  gen("c11-13.vmax", 2, [[0.05, 0.1, 0.2], [2, 5, 10]], (A, w) => ({ q: `A body in SHM has amplitude ${A} m and angular frequency ${w} rad/s. Find its maximum speed.`, v: A * w, u: "m/s", w: [A * w * w, A / w], e: "v_max = Aω, at the mean position.", c: "simple harmonic motion" }));
  gen("c11-14.lam", 1, [[128, 256, 440, 512, 1000], [340, 1480]], (f, v) => ({ q: `A ${f} Hz sound travels at ${v} m/s${v === 1480 ? " (in water)" : ""}. Find its wavelength.`, v: v / f, u: "m", w: [f / v, v * f], e: "λ = v/f.", c: "resonance" }));
  gen("c11-14.str", 2, [[0.5, 1, 2], [100, 200, 400], [1, 2, 3]], (L, v, n) => ({ q: `A string fixed at both ends is ${L} m long; waves travel on it at ${v} m/s. Find harmonic number ${n}.`, v: n * v / (2 * L), u: "Hz", w: [n * v / L, n * v / (4 * L)], e: "f_n = nv/2L.", c: "resonance" }));
  gen("c11-14.beat", 1, [[256, 440, 512], [2, 3, 4, 6]], (f, d) => ({ q: `Tuning forks of ${f} Hz and ${f + d} Hz sound together. How many beats per second are heard?`, v: d, u: "beats/s", w: [2 * f + d, d / 2, 2 * d], fmt: x => sig(x), e: "Beat frequency = |f₁ − f₂|.", c: "interference" }));
  gen("c11-14.pipe", 2, [[0.25, 0.5, 1], ["open at both ends", "closed at one end"]], (L, t) => ({ q: `Find the fundamental frequency of a ${L} m pipe ${t} (v = 340 m/s).`, v: t.startsWith("open") ? 340 / (2 * L) : 340 / (4 * L), u: "Hz", w: [t.startsWith("open") ? 340 / (4 * L) : 340 / (2 * L), 340 / L], e: "Open pipe: v/2L. Closed pipe: v/4L (only odd harmonics).", c: "resonance" }));

  /* ================= POOLS ================= */
  const lessonQ = sec => () => (DATA.lessons || []).filter(L => L.sec === sec || (sec === "quantum" && L.sec === "quantum-adv")).map(L => ({
    q: `${L.q}<br><span class="small muted">${L.mp}</span>`, o: L.mcq.map(m => m[0]), a: L.ok, whys: L.mcq.map(m => m[1]), e: L.mcq[L.ok][1], lv: L.lv, lesson: L.n, c: (G.termsIn ? (G.termsIn(L.q, 1)[0] || {}).t : "")
  }));
  const chapQ = (cls, n) => () => {
    const ch = (cls === 12 ? DATA.cbse12 : DATA.cbse11).find(c => c.n === n), out = [];
    ch.qs.forEach(q => {
      if (q.t === "mcq") out.push({ q: q.q, o: q.o, a: q.a, e: q.e, lv: 2 });
      if (q.t === "ar") out.push({ q: `<b>Assertion (A):</b> ${q.A}<br><b>Reason (R):</b> ${q.R}`, o: DATA.AR_OPTS, a: q.a, e: q.e, lv: 3, fixedOrder: true });
      if (q.t === "case") q.parts.forEach(p => out.push({ q: `<span class="small muted">Case study:</span> ${p.q}`, o: p.o, a: p.a, e: p.e, lv: 3 }));
    });
    return out;
  };
  for (const cls of [11, 12]) for (let n = 1; n <= 14; n++) {
    const id = `c${cls}-${n}`;
    G.pool(id, { name: `Class ${cls} · Chapter ${n}`, fixed: () => chapQ(cls, n)().concat(lessonQ(id)()), gens: [id + ".*"] });
  }
  G.pool("quantum", { name: "Quantum physics", fixed: () => lessonQ("quantum")().concat(DATA.topics.find(t => t.id === "quantum").qs.map(x => ({ q: x[0], o: x[1], a: x[2], e: x[3], lv: 2 }))), gens: ["c12-11.*", "c12-12.*"] });
  G.pool("class12", { name: "All of Class 12", fixed: () => [], include: Array.from({ length: 14 }, (_, i) => "c12-" + (i + 1)) });
  G.pool("class11", { name: "All of Class 11", fixed: () => [], include: Array.from({ length: 14 }, (_, i) => "c11-" + (i + 1)) });

  /* topic quizzes: hand-written topic questions + matching generators */
  const T = id => () => DATA.topics.find(t => t.id === id).qs.map(x => ({ q: x[0], o: x[1], a: x[2], e: x[3], lv: ["bh", "gravity", "quantum", "em"].includes(id) ? 2 : 1 }));
  const TP = { solar: ["myth.*", "nw.weight", "nw.esc", "nw.kepler", "sc.lighttime", "sc.model"], moon: ["sky.*"], stars: ["stars.*"], cosmos: ["origin.*"], bh: ["st.*"], light: ["c12-9.*", "c12-10.*", "c12-8.*"], explore: ["hist.isro", "hist.isroyr", "nw.orbv", "nw.orbT", "ready.*"], motion: ["nw.fma", "nw.acc", "nw.recoil", "nw.stick", "nw.range", "nw.cent", "nw.fric", "c11-2.*", "c11-3.*", "c11-4.*"], gravity: ["nw.orbv", "nw.orbT", "nw.esc", "nw.kepler", "nw.kepler2", "nw.gh", "c11-7.*"], energy: ["c11-5.*", "c11-10.*", "c11-11.*", "c11-12.*"], waves: ["c11-13.*", "c11-14.*"], em: ["c12-1.*", "c12-2.*", "c12-3.*", "c12-4.*", "c12-5.*", "c12-6.*", "c12-7.*"], quantum: ["c12-11.*", "c12-12.*", "c12-13.*", "c12-14.*"] };
  Object.entries(TP).forEach(([id, gens]) => G.pool("topic-" + id, { name: DATA.topics.find(t => t.id === id).name, fixed: id === "quantum" ? () => T(id)().concat(lessonQ("quantum")()) : T(id), gens }));
  G.pool("mega", { name: "Mega mix", fixed: () => [], include: ["origin", "stars", "sky", "spacetime", "newton", "myths", "heroes", "scale", "class11", "class12", "quantum", "ready", "isro-hist"].concat(DATA.topics.map(t => "topic-" + t.id)) });
  G.pool("isro-hist", { name: "India in space", fixed: () => DATA.topics.find(t => t.id === "explore").qs.map(x => ({ q: x[0], o: x[1], a: x[2], e: x[3], lv: 1 })), gens: ["hist.isro", "hist.isroyr", "ready.delay", "ready.panel", "ready.thrust", "nw.orbv", "nw.orbT"] });
})();
