/* More generators: extra chapter formulas, super-hard multi-step problems, and cross-links,
   so every section and chapter has hundreds of questions from easy to super hard. */
(function () {
  const gen = G.gen, { pickQ } = G.qb, sig = G.sig, PI = Math.PI, k = 9e9, e0 = 8.85e-12, mu0 = 4 * PI * 1e-7, deg = d => d * PI / 180;
  const h = 6.626e-34, c = 3e8, eV = 1.6e-19, MU = 3.986e14, RE = 6.371e6;

  /* ---------- CLASS 11 ---------- */
  gen("c11-1.conv2", 1, [[["5 km", 5000, "m"], ["250 cm", 2.5, "m"], ["3.5 g", 0.0035, "kg"], ["2 hours", 7200, "s"], ["1 day", 86400, "s"], ["500 mL", 5e-4, "m³"], ["20 cm²", 0.002, "m²"], ["1 year", 3.156e7, "s"]]], x => ({ q: `Convert ${x[0]} into SI units (${x[2]}).`, v: x[1], u: x[2], w: [x[1] * 10, x[1] / 10, x[1] * 100], e: "SI base units: metre, kilogram, second. Watch squared and cubed units carefully!", c: "units" }));
  gen("c11-1.err", 3, [[[20, 0.1, 5, 0.1], [50, 0.5, 10, 0.2], [100, 1, 4, 0.1]]], ([a, da, b, db]) => ({ q: `A = ${a} ± ${da} and B = ${b} ± ${db}. What is the percentage error in A × B?`, v: (da / a + db / b) * 100, u: "%", w: [(da + db) / (a + b) * 100, Math.abs(da / a - db / b) * 100], e: "For products and quotients, relative errors add.", steps: [`ΔA/A = ${sig(da / a * 100)}%, ΔB/B = ${sig(db / b * 100)}%`, `total = ${sig((da / a + db / b) * 100)}%`], c: "precision" }));
  gen("c11-1.pow", 3, [[2, 3, 0.5]], n => ({ q: `If a quantity Q = x^${n} and x is measured with 2% error, what is the percentage error in Q?`, v: 2 * n, u: "%", w: [2, 2 + n, 2 / n], e: "The error in xⁿ is n times the error in x.", c: "precision" }));
  gen("c11-3.height", 4, [[10, 20], [20, 45, 80]], (u, H) => { const t = Math.sqrt(2 * H / 10); return { q: `A ball is thrown horizontally at ${u} m/s from a cliff ${H} m high. How far from the base does it land? (g = 10 m/s²)`, v: u * t, u: "m", w: [u * u / 10, u * Math.sqrt(H / 10), H], e: "Fall time depends only on height; horizontal distance = speed × time.", steps: [`t = √(2H/g) = √(2 × ${H}/10) = ${sig(t)} s`, `x = u × t = ${u} × ${sig(t)} = ${sig(u * t)} m`], c: "projectile motion" }; });
  gen("c11-4.pulley", 4, [[2, 3, 5], [1, 2]], (m1, m2) => { const a = (m1 - m2) * 10 / (m1 + m2), T = 2 * m1 * m2 * 10 / (m1 + m2); return m1 === m2 ? { q: `Two ${m1} kg masses hang over a frictionless pulley. What is their acceleration?`, v: 0.001, u: "m/s²", fmt: x => x < 0.01 ? "0" : sig(x), w: [10, 5, 2.5], e: "Equal masses balance.", c: "Newton's second law" } : { q: `Masses of ${m1} kg and ${m2} kg hang over a light frictionless pulley (Atwood machine). Find the acceleration. (g = 10 m/s²)`, v: a, u: "m/s²", w: [10, (m1 - m2) * 10 / m1, T / m1], e: `a = (m₁ − m₂)g/(m₁ + m₂). The string tension is ${sig(T)} N.`, steps: [`net pull = (${m1} − ${m2}) × 10 = ${(m1 - m2) * 10} N`, `total mass = ${m1 + m2} kg`, `a = ${sig(a)} m/s²`], c: "Newton's second law" }; });
  gen("c11-5.spring", 4, [[100, 200, 500], [0.05, 0.1, 0.2], [0.1, 0.5]], (kk, x, m) => ({ q: `A spring (k = ${kk} N/m) compressed by ${x} m launches a ${m} kg ball on a smooth floor. Find the ball's speed.`, v: x * Math.sqrt(kk / m), u: "m/s", w: [kk * x / m, 0.5 * kk * x * x], e: "Spring energy ½kx² becomes kinetic energy ½mv².", steps: [`½kx² = ${sig(0.5 * kk * x * x)} J`, `v = x√(k/m) = ${sig(x * Math.sqrt(kk / m))} m/s`], c: "potential energy" }));
  gen("c11-5.coll", 3, [[1, 2, 4], [2, 6], [1, 2, 3]], (m1, u1, m2) => { const v1 = (m1 - m2) / (m1 + m2) * u1, v2 = 2 * m1 / (m1 + m2) * u1; return { q: `A ${m1} kg ball at ${u1} m/s hits a stationary ${m2} kg ball head-on in a perfectly elastic collision. Find the second ball's speed afterwards.`, v: v2, u: "m/s", w: [m1 * u1 / (m1 + m2), u1, Math.abs(v1)], e: `v₂ = 2m₁u₁/(m₁ + m₂). The first ball ends with ${sig(v1)} m/s.`, c: "momentum" }; });
  gen("c11-6.rpm", 1, [[30, 60, 120, 600, 3000]], r => ({ q: `A wheel spins at ${r} revolutions per minute. What is its angular speed?`, v: r * 2 * PI / 60, u: "rad/s", w: [r / 60, r * 2 * PI], e: "ω = 2π × (rev per second).", c: "angular momentum" }));
  gen("c11-6.KE", 2, [[0.5, 1, 2, 5], [5, 10, 20]], (I, w) => ({ q: `A flywheel with I = ${I} kg m² spins at ${w} rad/s. Find its rotational kinetic energy.`, v: 0.5 * I * w * w, u: "J", w: [I * w * w, 0.5 * I * w], e: "K = ½Iω², the rotating version of ½mv².", c: "moment of inertia" }));
  gen("c11-6.seesaw", 2, [[20, 30, 40], [1, 1.5, 2], [25, 50, 60]], (m1, d1, m2) => ({ q: `On a see-saw, a ${m1} kg child sits ${d1} m from the pivot. Where must a ${m2} kg child sit to balance?`, v: m1 * d1 / m2, u: "m from the pivot", w: [m2 * d1 / m1, d1], e: "Balance when torques match: m₁d₁ = m₂d₂.", c: "torque" }));
  gen("c11-6.roll", 4, [[["solid sphere", 0.4], ["disc", 0.5], ["ring", 1]], [1, 2, 5]], (b, hh) => ({ q: `A ${b[0]} rolls without slipping from rest down a ${hh} m high slope. Find its speed at the bottom. (g = 10 m/s²)`, v: Math.sqrt(2 * 10 * hh / (1 + b[1])), u: "m/s", w: [Math.sqrt(20 * hh), Math.sqrt(10 * hh)], e: "mgh = ½mv²(1 + k²/R²). Some energy goes into spinning, so rolling objects are slower than sliding ones. The sphere wins the race!", steps: [`k²/R² = ${b[1]}`, `v = √(2gh/(1 + ${b[1]})) = ${sig(Math.sqrt(2 * 10 * hh / (1 + b[1])))} m/s`], c: "moment of inertia" }));
  gen("c11-7.satE", 4, [[500, 1000, 5000], [100, 1000]], (hk, m) => { const r = RE + hk * 1e3, E = -MU * m / (2 * r); return { q: `Find the total energy of a ${m} kg satellite in a circular orbit ${hk} km above Earth. (GM = 3.986 × 10¹⁴ m³/s²)`, v: E / 1e9, u: "GJ", w: [-MU * m / r / 1e9, MU * m / (2 * r) / 1e9], fmt: x => sig(x), e: "E = −GMm/2r. Negative means bound. KE = +GMm/2r, PE = −GMm/r.", c: "orbital speed" }; });
  gen("c11-8.Y", 2, [[1, 2], [1, 2], [100, 200], [0.5, 1]], (L, A, F, dL) => ({ q: `A ${L} m wire of area ${A} mm² stretches by ${dL} mm under ${F} N. Find Young's modulus.`, v: F * L / (A * 1e-6 * dL * 1e-3), u: "Pa", w: [F / (A * 1e-6), F * L / (A * dL)], e: "Y = (F/A)/(ΔL/L).", c: "stress" }));
  gen("c11-8.U", 3, [[100, 200, 500], [1, 2, 5]], (F, dL) => ({ q: `A wire stretched elastically by ${dL} mm under a final load of ${F} N stores how much energy?`, v: 0.5 * F * dL * 1e-3, u: "J", w: [F * dL * 1e-3, F * dL], e: "U = ½ × force × extension (the area under the force–extension line).", c: "stress" }));
  gen("c11-9.buoy", 2, [[["ice", 917], ["wood", 600], ["a human body", 985], ["cork", 240]], [["fresh water", 1000], ["sea water", 1025]]], (o, f) => ({ q: `What fraction of ${o[0]} (ρ = ${o[1]} kg/m³) floats below the surface in ${f[0]} (ρ = ${f[1]} kg/m³)?`, v: o[1] / f[1] * 100, u: "%", w: [(1 - o[1] / f[1]) * 100, f[1] / o[1] * 50], fmt: x => sig(x), e: "Floating: weight = buoyant force, so submerged fraction = ρ_object/ρ_fluid. That is why icebergs hide about 90% underwater.", c: "pressure" }));
  gen("c11-9.drop", 3, [[0.072, 0.05], [0.5, 1, 2]], (S, r) => ({ q: `Find the excess pressure inside a liquid drop of radius ${r} mm with surface tension ${S} N/m.`, v: 2 * S / (r * 1e-3), u: "Pa", w: [4 * S / (r * 1e-3), S / (r * 1e-3)], e: "Drop: ΔP = 2S/r. A soap bubble has two surfaces: ΔP = 4S/r.", c: "surface tension" }));
  gen("c11-9.bern", 4, [[1, 2], [3, 4, 6], [1000]], (v1, v2, rho) => ({ q: `Water speeds up from ${v1} m/s to ${v2} m/s in a horizontal pipe. By how much does its pressure drop?`, v: 0.5 * rho * (v2 * v2 - v1 * v1), u: "Pa", w: [0.5 * rho * (v2 - v1) ** 2, rho * (v2 * v2 - v1 * v1)], e: "Bernoulli: P + ½ρv² stays constant along a streamline, so faster flow means lower pressure.", c: "pressure" }));
  gen("c11-10.mix", 4, [[0.1, 0.2], [80, 90], [0.2, 0.4], [20, 30]], (m1, T1, m2, T2) => ({ q: `${m1} kg of water at ${T1} °C is mixed with ${m2} kg of water at ${T2} °C. Find the final temperature (no heat loss).`, v: (m1 * T1 + m2 * T2) / (m1 + m2), u: "°C", w: [(T1 + T2) / 2, (m1 * T2 + m2 * T1) / (m1 + m2)], e: "Heat lost by the hot water = heat gained by the cold water (calorimetry).", steps: [`${m1} × c × (${T1} − T) = ${m2} × c × (T − ${T2})`, `T = (${m1} × ${T1} + ${m2} × ${T2}) / ${m1 + m2}`, `T = ${sig((m1 * T1 + m2 * T2) / (m1 + m2))} °C`], c: "heat" }));
  gen("c11-11.iso", 3, [[1, 2], [300, 400], [2, 3]], (n, T, r) => ({ q: `${n} mol of ideal gas expands isothermally at ${T} K to ${r} times its volume. How much work does it do? (R = 8.314)`, v: n * 8.314 * T * Math.log(r), u: "J", w: [n * 8.314 * T * (r - 1), n * 8.314 * T], e: "W = nRT ln(V₂/V₁). ΔU = 0, so Q = W.", c: "work" }));
  gen("c11-11.carnot", 3, [[300, 350], [500, 600, 800]], (Tc, Th) => ({ q: `An ideal engine works between ${Th} K and ${Tc} K. What is its maximum possible efficiency?`, v: (1 - Tc / Th) * 100, u: "%", w: [Tc / Th * 100, (Th - Tc) / Tc * 100], fmt: x => sig(x), e: "η_max = 1 − T_cold/T_hot (temperatures in kelvin). Real engines always do worse.", c: "entropy" }));
  gen("c11-11.dUn", 2, [[1, 2, 3], [10, 50, 100]], (n, dT) => ({ q: `${n} mol of a monatomic ideal gas (Cv = 3R/2) warms by ${dT} K. Find the change in internal energy.`, v: n * 1.5 * 8.314 * dT, u: "J", w: [n * 2.5 * 8.314 * dT, n * 8.314 * dT], e: "ΔU = nCvΔT, whatever the process.", c: "internal energy" }));
  gen("c11-12.pv", 2, [[1, 2, 5], [273, 300, 400], [1e5, 2e5]], (n, T, P) => ({ q: `Find the volume of ${n} mol of an ideal gas at ${T} K and ${sig(P)} Pa.`, v: n * 8.314 * T / P * 1000, u: "L", w: [n * 8.314 * T / P, P / (n * 8.314 * T)], e: "V = nRT/P (m³ → multiply by 1000 for litres).", c: "temperature" }));
  gen("c11-12.ratio2", 3, [[["hydrogen", 2], ["helium", 4]], [["oxygen", 32], ["nitrogen", 28], ["carbon dioxide", 44]]], (a, b) => ({ q: `At the same temperature, how many times faster (rms) are ${a[0]} molecules than ${b[0]} molecules?`, v: Math.sqrt(b[1] / a[1]), u: "×", w: [b[1] / a[1], Math.sqrt(a[1] / b[1])], e: "v_rms ∝ 1/√M at a fixed temperature.", c: "temperature" }));
  gen("c11-12.escape", 4, [[["the Moon", 2380, 390], ["Mars", 5030, 300], ["Earth", 11200, 1000], ["Jupiter", 59500, 1000]], [["hydrogen", 0.002], ["helium", 0.004], ["nitrogen", 0.028]]], (p, g) => { const T = p[2], v = Math.sqrt(3 * 8.314 * T / g[1]), keep = v < p[1] / 6; return pickQ({ q: `On ${p[0]} (escape speed ${p[1] / 1000} km/s; gas at the top of the atmosphere ≈ ${T} K), can ${g[0]} stay in the atmosphere for billions of years? (Rule of thumb: yes if v_rms < 1/6 of escape speed)`, right: keep ? "Yes, it can be held" : "No, it slowly escapes", pool: ["Yes, it can be held", "No, it slowly escapes"], e: `v_rms = √(3RT/M) ≈ ${Math.round(v)} m/s vs 1/6 escape ≈ ${Math.round(p[1] / 6)} m/s. Escape happens at the very top of the atmosphere, which is much hotter than the ground. That is why Jupiter keeps hydrogen while Earth keeps losing hydrogen and helium.`, c: "escape velocity" }); });
  gen("c11-13.E", 2, [[20, 50, 100], [0.05, 0.1, 0.2]], (kk, A) => ({ q: `A spring (k = ${kk} N/m) oscillates with amplitude ${A} m. Find its total energy.`, v: 0.5 * kk * A * A, u: "J", w: [kk * A * A, 0.5 * kk * A], e: "E = ½kA², constant throughout the motion.", c: "simple harmonic motion" }));
  gen("c11-13.L", 3, [[1, 2, 4], [["Earth", 9.8], ["the Moon", 1.62]]], (T, w) => ({ q: `How long must a pendulum be to have a period of ${T} s on ${w[0]}?`, v: w[1] * T * T / (4 * PI * PI), u: "m", w: [w[1] * T / (2 * PI), T * T / (4 * PI * PI)], e: "l = gT²/4π². A 2 s 'seconds pendulum' on Earth is about 1 m long.", c: "simple harmonic motion" }));
  gen("c11-13.tunnel", 4, [[["Earth", 6.371e6, 9.8], ["the Moon", 1.737e6, 1.62], ["Mars", 3.39e6, 3.71]]], p => ({ q: `If you could drop a ball through a straight tunnel through the centre of ${p[0]} (uniform density), how long until it reaches the other side?`, v: PI * Math.sqrt(p[1] / p[2]) / 60, u: "minutes", w: [2 * PI * Math.sqrt(p[1] / p[2]) / 60, Math.sqrt(p[1] / p[2]) / 60], e: "Inside a uniform planet, gravity ∝ distance from the centre: SHM with T = 2π√(R/g). The trip is half a period, the same as a low orbit's half-lap!", c: "simple harmonic motion" }));
  gen("c11-14.vstr", 2, [[50, 100, 200], [0.005, 0.01, 0.02]], (T, m) => ({ q: `A string under ${T} N tension has a mass per length of ${m} kg/m. Find the wave speed.`, v: Math.sqrt(T / m), u: "m/s", w: [T / m, Math.sqrt(m / T)], e: "v = √(T/μ).", c: "resonance" }));
  gen("c11-14.laplace", 3, [[0, 20, 40]], t => ({ q: `Using v ≈ 331 m/s × √(T/273 K), find the speed of sound in air at ${t} °C.`, v: 331 * Math.sqrt((273 + t) / 273), u: "m/s", w: [331 + t, 331 * (273 + t) / 273], e: "Sound speed grows with the square root of absolute temperature.", c: "resonance" }));
  gen("c11-14.echo", 1, [[1, 2, 3, 4]], t => ({ q: `You clap and hear the echo from a cliff ${t} s later (v = 340 m/s). How far is the cliff?`, v: 340 * t / 2, u: "m", w: [340 * t, 340 / t], e: "The sound travels there and back, so halve the total distance.", c: "resonance" }));

  /* ---------- CLASS 12 ---------- */
  gen("c12-1.null", 4, [[1, 4, 9], [4, 9, 16], [0.3, 0.6, 1]], (q1, q2, d) => { if (q1 === q2) q2 = q2 * 4; const x = d * Math.sqrt(q1) / (Math.sqrt(q1) + Math.sqrt(q2)); return { q: `Like charges of ${q1} μC and ${q2} μC are ${d} m apart. How far from the ${q1} μC charge is the electric field zero?`, v: x, u: "m", w: [d / 2, d * q1 / (q1 + q2), d - x], e: "Between like charges the fields oppose. Set kq₁/x² = kq₂/(d − x)². The zero is nearer the smaller charge.", steps: [`√(q₁/q₂) = x/(d − x) = ${sig(Math.sqrt(q1 / q2))}`, `x = d√q₁/(√q₁ + √q₂)`, `x = ${sig(x)} m`], c: "electric field" }; });
  gen("c12-2.diel", 4, [[2, 4, 5], ["battery connected", "battery removed"]], (K, m) => ({ q: `A charged capacitor has a dielectric of K = ${K} slid in with the ${m}. By what factor does its stored energy change?`, v: m === "battery connected" ? K : 1 / K, u: "×", w: [m === "battery connected" ? 1 / K : K, K * K, 1], e: m === "battery connected" ? "V fixed, C rises K times: U = ½CV² rises K times (the battery supplies the extra)." : "Q fixed, C rises K times: U = Q²/2C falls to 1/K (the slab is pulled in and work is done on it).", c: "dielectric" }));
  gen("c12-2.WE", 2, [[1, 2, 5], [0.1, 0.2]], (q, r) => ({ q: `Find the electrostatic potential energy of two ${q} μC charges ${r} m apart.`, v: k * q * q * 1e-12 / r, u: "J", w: [k * q * q * 1e-12 / (r * r), k * q * 1e-6 / r], e: "U = kq₁q₂/r (positive: work was needed to push like charges together).", c: "electric potential" }));
  gen("c12-3.maxP", 4, [[6, 12], [0.5, 1, 2]], (E, r) => ({ q: `A battery of emf ${E} V has internal resistance ${r} Ω. What is the maximum power it can deliver to an external resistor?`, v: E * E / (4 * r), u: "W", w: [E * E / r, E * E / (2 * r)], e: "Maximum power transfer when R = r: P = ε²/4r.", steps: [`choose R = r = ${r} Ω`, `I = ε/2r = ${sig(E / (2 * r))} A`, `P = I²R = ${sig(E * E / (4 * r))} W`], c: "emf" }));
  gen("c12-3.drift", 3, [[1, 2, 5], [1, 2]], (I, A) => ({ q: `A copper wire of cross-section ${A} mm² carries ${I} A. Find the drift speed. (n = 8.5 × 10²⁸ m⁻³, e = 1.6 × 10⁻¹⁹ C)`, v: I / (8.5e28 * A * 1e-6 * 1.6e-19) * 1000, u: "mm/s", w: [I / (8.5e28 * A * 1.6e-19), I / (8.5e28 * A * 1e-6 * 1.6e-19)], e: "v_d = I/(nAe). Tiny! The signal is fast, the electrons are slow.", c: "electric current" }));
  gen("c12-4.vsel", 4, [[1e3, 1e4, 1e5], [0.01, 0.1, 0.5]], (E, B) => ({ q: `In a velocity selector, crossed fields E = ${sig(E)} V/m and B = ${B} T let only one speed pass undeflected. Which speed?`, v: E / B, u: "m/s", w: [E * B, B / E], e: "qE = qvB ⇒ v = E/B. Used in mass spectrometers.", c: "magnetic field" }));
  gen("c12-4.force", 2, [[1, 2, 5], [0.5, 1, 2], [0.1, 0.5], [30, 90]], (I, L, B, th) => ({ q: `A ${L} m wire carrying ${I} A sits at ${th}° to a ${B} T field. Find the force on it.`, v: B * I * L * Math.sin(deg(th)), u: "N", w: [B * I * L * Math.cos(deg(th)), B * I * L], e: "F = BIL sin θ.", c: "magnetic field" }));
  gen("c12-5.m", 2, [[10, 50, 100], [0.5, 1, 2], [0.01, 0.05]], (N, I, r) => ({ q: `A circular coil of ${N} turns and radius ${r} m carries ${I} A. Find its magnetic moment.`, v: N * I * PI * r * r, u: "A m²", w: [N * I * 2 * PI * r, I * PI * r * r], e: "m = NIA, with A = πr².", c: "magnetic field" }));
  gen("c12-5.U", 3, [[0.5, 1], [0.2, 0.5], [0, 60, 90, 180]], (m, B, th) => ({ q: `A magnetic dipole of moment ${m} A m² sits at ${th}° to a ${B} T field. What is its potential energy?`, v: -m * B * Math.cos(deg(th)), u: "J", w: [m * B * Math.cos(deg(th)), -m * B * Math.sin(deg(th))].map(x => x || 0.05), fmt: x => Math.abs(x) < 1e-9 ? "0" : sig(x), e: "U = −mB cos θ: lowest when aligned, highest when opposite.", c: "magnetic field" }));
  gen("c12-6.rail", 4, [[0.5, 1], [0.5, 1], [2, 5], [2, 5]], (B, L, v, R) => { const I = B * L * v / R; return { q: `A ${L} m rod slides at ${v} m/s on rails through a ${B} T field; the circuit resistance is ${R} Ω. What force is needed to keep it moving at steady speed?`, v: B * I * L, u: "N", w: [I, B * L * v], e: "ε = BLv drives I = ε/R; the field pushes back with F = BIL (Lenz). You must match it.", steps: [`ε = BLv = ${sig(B * L * v)} V`, `I = ε/R = ${sig(I)} A`, `F = BIL = ${sig(B * I * L)} N`], c: "Lenz's law" }; });
  gen("c12-6.ac", 3, [[50, 100, 500], [0.05, 0.1], [0.2, 0.5], [10, 50]], (N, A, B, w) => ({ q: `A generator coil has ${N} turns, area ${A} m², turns at ${w} rad/s in a ${B} T field. Find its peak emf.`, v: N * B * A * w, u: "V", w: [B * A * w, N * B * A], e: "ε₀ = NBAω.", c: "electromagnetic induction" }));
  gen("c12-7.Z", 2, [[30, 40, 60], [40, 80], [0, 50]], (R, XL, XC) => ({ q: `A series circuit has R = ${R} Ω, X_L = ${XL} Ω and X_C = ${XC} Ω. Find the impedance.`, v: Math.hypot(R, XL - XC), u: "Ω", w: [R + XL - XC, R + XL + XC, Math.hypot(R, XL + XC)], e: "Z = √(R² + (X_L − X_C)²). Reactances subtract because they are 180° apart.", c: "impedance" }));
  gen("c12-7.pf", 3, [[30, 60, 80], [40, 60, 80]], (R, X) => ({ q: `A circuit has R = ${R} Ω and net reactance ${X} Ω. Find its power factor.`, v: R / Math.hypot(R, X), w: [X / Math.hypot(R, X), R / X], fmt: x => x.toFixed(2), e: "cos φ = R/Z. Only the resistor uses power on average.", c: "impedance" }));
  gen("c12-8.fm", 1, [[88, 91.1, 93.5, 98.3, 104.8, 107.2]], f => ({ q: `An FM station broadcasts at ${f} MHz. What is its wavelength?`, v: 3e8 / (f * 1e6), u: "m", w: [f * 1e6 / 3e8, 300 / f / 10], e: "λ = c/f. FM waves are about 3 m long, the size of a car.", c: "electromagnetic wave" }));
  gen("c12-8.E", 2, [[["radio (1 m)", 1], ["microwave (1 cm)", 0.01], ["infrared (10 μm)", 1e-5], ["green light (550 nm)", 5.5e-7], ["UV (100 nm)", 1e-7], ["X-ray (0.1 nm)", 1e-10]]], w => ({ q: `Find the energy of one photon of ${w[0]}.`, v: 1240e-9 / w[1], u: "eV", w: [w[1] / 1240e-9, 1240 / w[1]], e: "E = hc/λ ≈ 1240 eV nm / λ. Only UV and beyond can break chemical bonds (a few eV).", c: "photon" }));
  gen("c12-9.v", 1, [[1.33, 1.5, 1.65, 2.42]], n => ({ q: `How fast does light travel in a material of refractive index ${n}?`, v: 3e8 / n, u: "m/s", w: [3e8 * n, 3e8], e: "v = c/n.", c: "refractive index" }));
  gen("c12-9.depth", 2, [[1, 2, 3], [1.33, 1.5]], (d, n) => ({ q: `A coin lies ${d} m deep in a liquid of refractive index ${n}. How deep does it appear from above?`, v: d / n, u: "m", w: [d * n, d - n], e: "Apparent depth = real depth / n. Pools look shallower than they are!", c: "refractive index" }));
  gen("c12-9.combo", 3, [[10, 20, 25], [-20, 40, 50]], (f1, f2) => ({ q: `Two thin lenses of focal lengths ${f1} cm and ${f2} cm are placed in contact. Find the power of the combination.`, v: 100 / f1 + 100 / f2, u: "D", w: [100 / (f1 + f2), (100 / f1) * (100 / f2)], fmt: x => (x > 0 ? "+" : "") + sig(x), e: "Powers add: P = P₁ + P₂ (f in metres).", c: "focal length" }));
  gen("c12-9.twolens", 4, [[10], [20], [30, 40]], (f1, f2, u) => { const v1 = 1 / (1 / f1 - 1 / u), u2 = -(v1 - 20), v2 = 1 / (1 / f2 + 1 / u2); return { q: `Two convex lenses (f₁ = ${f1} cm, f₂ = ${f2} cm) are 20 cm apart. An object is ${u} cm in front of the first. Where is the final image, measured from the second lens?`, v: v2, u: "cm", w: [v1, 1 / (1 / f2 - 1 / u), v1 - 20], fmt: x => (x > 0 ? "+" : "") + sig(x), e: "The first lens's image becomes the object for the second.", steps: [`Lens 1: 1/v = 1/${f1} − 1/${u} ⇒ v₁ = ${sig(v1)} cm`, `Object for lens 2: u₂ = −(${sig(v1)} − 20) = ${sig(u2)} cm`, `Lens 2: v₂ = ${sig(v2)} cm`], c: "lens formula" }; });
  gen("c12-10.slit", 2, [[500, 600], [0.1, 0.2, 0.5], [1, 2]], (l, a, D) => ({ q: `Light of ${l} nm passes a single slit ${a} mm wide onto a screen ${D} m away. How wide is the central bright band?`, v: 2 * l * 1e-9 * D / (a * 1e-3) * 1000, u: "mm", w: [l * 1e-9 * D / (a * 1e-3) * 1000, l * 1e-9 * a / D * 1000], e: "Width = 2λD/a. Narrower slit, wider spread.", c: "diffraction" }));
  gen("c12-10.path", 2, [[500, 600], [0.5, 1, 1.5, 2, 2.5, 3]], (l, n) => pickQ({ q: `Two coherent waves (λ = ${l} nm) arrive with a path difference of ${n * l} nm. Bright or dark?`, right: Number.isInteger(n) ? "Bright (constructive)" : "Dark (destructive)", pool: ["Bright (constructive)", "Dark (destructive)"], e: `Path difference = ${n}λ. Whole numbers of λ: bright. Half-odd numbers: dark.`, c: "interference" }));
  gen("c12-11.p", 2, [[400, 500, 700, 1]], l => ({ q: `Find the momentum of a photon of wavelength ${l} nm.`, v: h / (l * 1e-9), u: "kg m/s", w: [h * l * 1e-9, h * c / (l * 1e-9)], e: "p = h/λ. Tiny, but it is why sunlight can push solar sails.", c: "photon" }));
  gen("c12-11.N", 3, [[1, 5, 100], [450, 650]], (P, l) => ({ q: `A ${P} mW laser emits ${l} nm light. How many photons does it send out each second?`, v: P * 1e-3 / (h * c / (l * 1e-9)), u: "photons/s", w: [P * 1e-3 / (h * c), P / (h * c / (l * 1e-9))], e: "N = P/E_photon. Even a pointer emits ~10¹⁵ photons a second, so light looks smooth.", c: "photon" }));
  gen("c12-11.h", 4, [[0]], () => ({ q: `Light of 400 nm gives a stopping potential of 1.00 V; light of 300 nm gives 2.03 V on the same metal. Estimate Planck's constant from these data.`, v: (2.03 - 1.00) * eV / (c / 300e-9 - c / 400e-9), u: "J s", w: [1.03 * eV / (c / 300e-9), (2.03 - 1.00) / (c / 300e-9 - c / 400e-9)], e: "Einstein: eV₀ = hf − φ, so h = eΔV₀/Δf (the slope of V₀ against f, times e). Millikan measured h this way in 1916.", steps: ["f₁ = c/400 nm = 7.5 × 10¹⁴ Hz, f₂ = c/300 nm = 1.0 × 10¹⁵ Hz", "Δf = 2.5 × 10¹⁴ Hz, ΔV₀ = 1.03 V", "h = eΔV₀/Δf = 1.6 × 10⁻¹⁹ × 1.03 / 2.5 × 10¹⁴ ≈ 6.6 × 10⁻³⁴ J s"], c: "photoelectric effect" }));
  gen("c12-11.ball", 3, [[["an electron at 10⁶ m/s", 9.11e-31, 1e6], ["a proton at 10⁵ m/s", 1.67e-27, 1e5], ["a cricket ball (0.16 kg) at 40 m/s", 0.16, 40]]], p => ({ q: `Find the de Broglie wavelength of ${p[0]}.`, v: h / (p[1] * p[2]), u: "m", w: [h * p[1] * p[2], h / p[1]], e: "λ = h/mv. For everyday objects λ is absurdly small, which is why we never see a cricket ball diffract.", c: "de Broglie wavelength" }));
  gen("c12-12.ion", 2, [[1, 2, 3, 4, 5]], n => ({ q: `How much energy is needed to ionise hydrogen from level n = ${n}?`, v: 13.6 / (n * n), u: "eV", w: [13.6 / n, 13.6 * n * n], e: "Ionisation from level n needs +13.6/n² eV (to reach E = 0).", c: "Bohr model" }));
  gen("c12-12.lines", 3, [[2, 3, 4, 5, 6]], n => ({ q: `Hydrogen atoms are excited to level n = ${n}. How many different spectral lines can they emit as they fall back?`, v: n * (n - 1) / 2, w: [n - 1, n, n * n], fmt: x => String(Math.round(x)), e: "Any pair of levels can give a line: n(n − 1)/2 combinations.", c: "spectral line" }));
  gen("c12-13.NZ", 1, [[["carbon-12", 6, 12], ["oxygen-16", 8, 16], ["iron-56", 26, 56], ["gold-197", 79, 197], ["uranium-235", 92, 235], ["uranium-238", 92, 238]]], x => ({ q: `How many neutrons are in a nucleus of ${x[0]} (Z = ${x[1]})?`, v: x[2] - x[1], w: [x[2], x[1], x[2] + x[1]], fmt: v => String(v), e: "N = A − Z.", c: "isotope" }));
  gen("c12-13.fission", 4, [[1, 0.1, 0.01]], m => { const E = m * 1000 / 235 * 6.022e23 * 200 * 1.602e-13; return { q: `About 200 MeV is released per U-235 fission. How much energy comes from fully fissioning ${m} kg of U-235?`, v: E, u: "J", w: [m * 200 * 1.602e-13, E / 1000], e: `That is about the energy of burning ${sig(E / 3e7 / 1000)} tonnes of coal (≈ 30 MJ/kg).`, steps: [`atoms = ${m * 1000} g ÷ 235 g/mol × 6.022 × 10²³ = ${sig(m * 1000 / 235 * 6.022e23)}`, `energy per fission = 200 MeV = 3.2 × 10⁻¹¹ J`, `total ≈ ${sig(E)} J`], c: "fission" }; });
  gen("c12-13.fusion", 3, [[["D + T → He-4 + n", 17.6], ["D + D → He-3 + n", 3.27], ["4 H → He-4 (the Sun's net result)", 26.7]]], r => ({ q: `The fusion reaction ${r[0]} releases ${r[1]} MeV. How much mass disappears?`, v: r[1] / 931.5, u: "u", w: [r[1] * 931.5, r[1] / 93.15], e: "Δm = E/931.5 MeV per u.", c: "fusion" }));
  gen("c12-13.decay", 2, [[1, 2, 3, 4, 5]], n => ({ q: `After ${n} half-lives, what fraction of a radioactive sample remains?`, v: Math.pow(0.5, n), w: [1 - Math.pow(0.5, n), 1 / (2 * n), 0.5 / n], fmt: x => "1/" + Math.round(1 / x), e: "Each half-life halves what is left: (½)ⁿ.", c: "half-life" }));
  gen("c12-14.ni", 3, [[1.5e16], [1e21, 5e22, 1e23]], (ni, nd) => ({ q: `Silicon (nᵢ = 1.5 × 10¹⁶ m⁻³) is doped with ${sig(nd)} donor atoms per m³. Find the hole concentration.`, v: ni * ni / nd, u: "m⁻³", w: [ni, nd, ni / nd], e: "n_e n_h = nᵢ². More electrons means far fewer holes.", c: "semiconductor" }));
  gen("c12-14.hw", 2, [[10, 20, 50], [0.7]], (Vp, Vd) => ({ q: `A silicon diode (0.7 V drop) rectifies a ${Vp} V peak AC signal. What is the peak output voltage?`, v: Vp - Vd, u: "V", w: [Vp, Vp / Math.SQRT2], e: "The diode 'uses up' about 0.7 V when conducting.", c: "rectifier" }));

  /* ---------- SECTION extras ---------- */
  gen("origin.age", 4, [[0.5, 1, 3, 6, 10]], z => ({ q: `Light from a galaxy at redshift z = ${z} has been stretched by how much? And if you watched a star there blink once per second, how often would it blink as seen here?`, v: 1 + z, u: "× (blinks every that many seconds)", w: [z, 1 / (1 + z)], e: "Wavelengths and time intervals both stretch by (1 + z). Distant supernovae really do fade in slow motion: a confirmed test of cosmic expansion.", c: "redshift" }));
  gen("stars.flux", 4, [[1, 10, 100], [10, 100]], (L, d) => ({ q: `A star ${L}× as luminous as the Sun is ${d} light years away. How bright does it look compared with a Sun-like star at 10 light years? (brightness ∝ L/d²)`, v: L * 100 / (d * d), u: "×", w: [L * 10 / d, L / d], e: "Apparent brightness falls with the square of distance.", c: "luminosity" }));
  gen("stars.radius", 4, [[["Betelgeuse", 3600, 100000], ["Sirius B", 25000, 0.056], ["Rigel", 12100, 120000], ["Proxima Centauri", 3040, 0.0017]]], s => { const R = Math.sqrt(s[2]) * Math.pow(5772 / s[1], 2); return { q: `${s[0]} has luminosity ≈ ${G.fmt(s[2])} L☉ and temperature ≈ ${s[1].toLocaleString("en-IN")} K. Estimate its radius in solar radii. (L ∝ R²T⁴)`, v: R, u: "R☉", w: [s[2] * Math.pow(5772 / s[1], 4), Math.sqrt(s[2]) * 5772 / s[1]], e: "R/R☉ = √(L/L☉) × (T☉/T)². This is exactly how astronomers 'measure' star sizes they cannot resolve.", steps: [`√(L/L☉) = ${sig(Math.sqrt(s[2]))}`, `(5772/${s[1]})² = ${sig(Math.pow(5772 / s[1], 2))}`, `R ≈ ${sig(R)} R☉`], c: "Stefan–Boltzmann law" }; });
  gen("sky.angle", 3, [[["the Moon", 3474, 384400], ["the Sun", 1.3927e6, 1.496e8], ["the ISS", 0.109, 420], ["Jupiter at opposition", 139820, 6.3e8]]], o => ({ q: `How big does ${o[0]} look in the sky? (diameter ${o[1].toLocaleString("en-IN")} km, distance ${o[2].toLocaleString("en-IN")} km)`, v: o[1] / o[2] * 180 / PI, w: [o[2] / o[1], o[1] / o[2]], fmt: x => x < 0.01 ? (x * 3600).toFixed(1) + " arcseconds" : sig(x) + "°", e: "Angle (radians) ≈ size / distance. The Sun and Moon both come out near 0.5°: that is why total eclipses are possible.", c: "eclipse" }));
  gen("sky.hand", 1, [[["little finger", 1], ["three middle fingers", 5], ["fist", 10], ["spread hand", 20]]], x => ({ q: `At arm's length, roughly how many degrees of sky does your ${x[0]} cover?`, v: x[1], u: "°", w: [x[1] * 2, x[1] / 2, x[1] + 15], fmt: v => String(v), e: "Everyone's hand-to-arm ratio is similar, so this works for most people.", c: "latitude" }));
  gen("sc.fit", 2, [[["Earth", 6371], ["the Moon", 1737], ["Mars", 3390], ["Neptune", 24622]], [["Jupiter", 69911], ["the Sun", 696340]]], (a, b) => ({ q: `Roughly how many balls the size of ${a[0]} could fit inside ${b[0]} (by volume)?`, v: Math.pow(b[1] / a[1], 3), w: [b[1] / a[1], Math.pow(b[1] / a[1], 2)], fmt: x => G.fmt(Math.round(x)), e: "Volume grows as radius cubed: (R_big/R_small)³.", c: "powers of ten" }));
  gen("sc.age", 2, [[["ancient Egypt's pyramids", 4500], ["the first humans", 300000], ["the dinosaurs' extinction", 6.6e7], ["the Sun's birth", 4.6e9]]], e => ({ q: `If a galaxy's light left it when ${e[0]} happened (${G.fmt(e[1])} years ago), how far away is it (ignoring expansion)?`, v: e[1] * 9.461e12, u: "km", w: [e[1] * 3e5, e[1] * 9.461e12 / 1000], e: "Light years measure distance: light time × speed of light.", c: "light year" }));
  gen("sc.plx", 3, [[0.1, 0.2, 0.5, 0.768]], p => ({ q: `A star shows a parallax of ${p}″. How far away is it in light years?`, v: 3.26 / p, u: "ly", w: [1 / p, 3.26 * p], e: "d(pc) = 1/p; 1 pc = 3.26 ly.", c: "parsec" }));
  gen("sc.voyager", 4, [[["Proxima Centauri", 4.24], ["Sirius", 8.6], ["Vega", 25]]], s => ({ q: `Voyager 1 travels at about 17 km/s. How long would it take to reach ${s[0]} (${s[1]} light years)?`, v: s[1] * 9.461e12 / 17 / 3.156e7, u: "years", w: [s[1] * 9.461e12 / 17 / 3.156e10, s[1] / 17], fmt: x => G.fmt(Math.round(x)), e: "time = distance/speed. Even our fastest probes would take tens of thousands of years: interstellar travel is hard.", c: "light year" }));
  gen("hist.order", 3, [[[0, 3, 10], [4, 9, 14], [11, 15, 22], [2, 6, 13], [8, 18, 26], [5, 16, 24]]], idx => { const ev = [[1543, "Copernicus's Sun-centred model"], [1609, "Kepler's first laws"], [1610, "Galileo sees Jupiter's moons"], [1687, "Newton's Principia"], [1781, "Uranus discovered"], [1846, "Neptune discovered"], [1868, "Helium found in the Sun"], [1887, "Radio waves made in the lab"], [1895, "X-rays discovered"], [1897, "Electron discovered"], [1905, "Special relativity"], [1911, "Atomic nucleus found"], [1912, "Leavitt's Cepheid law"], [1913, "Bohr's atom"], [1915, "General relativity"], [1920, "Saha's equation"], [1924, "Bose statistics"], [1925, "Stars are mostly hydrogen"], [1928, "Raman effect"], [1929, "Hubble's expanding universe"], [1930, "Pluto discovered"], [1932, "Neutron discovered"], [1965, "CMB detected"], [1967, "First pulsar"], [1995, "First exoplanet around a Sun-like star"], [2012, "Higgs boson"], [2015, "Gravitational waves detected"]]; const pick = idx.map(i => ev[i]); const right = pick.map(p => p[1]).join(" → "); const alt = [[1, 0, 2], [2, 1, 0], [0, 2, 1], [1, 2, 0]].map(o => o.map(i => pick[i][1]).join(" → ")); return pickQ({ q: "Put these discoveries in the correct order, earliest first.", right, pool: alt, e: pick.map(p => `${p[1]} (${p[0]})`).join(", ") + ".", c: "scientific method" }); });

  /* ---------- top-ups so every chapter passes 100 ---------- */
  gen("c11-1.prefix", 1, [[["kilo", 1e3], ["mega", 1e6], ["milli", 1e-3], ["micro", 1e-6], ["nano", 1e-9]], [["metres", "m"], ["grams", "g"], ["seconds", "s"], ["watts", "W"], ["volts", "V"]]], (pf, u) => ({ q: `How many ${u[0]} are in 1 ${pf[0]}${u[1] === "g" ? "gram" : u[0].slice(0, -1)}?`, v: pf[1], w: [1 / pf[1], pf[1] * 1000, pf[1] / 1000], fmt: x => G.fmt(x), e: "kilo = 10³, mega = 10⁶, milli = 10⁻³, micro = 10⁻⁶, nano = 10⁻⁹.", c: "powers of ten" }));
  gen("c11-8.strain", 1, [[1, 2, 5], [0.5, 1, 2, 4]], (L, dL) => ({ q: `A ${L} m rod stretches by ${dL} mm. What is the strain?`, v: dL * 1e-3 / L, w: [dL / L, L / (dL * 1e-3)], e: "Strain = ΔL/L (no units). Convert mm to m first.", c: "stress" }));
  gen("c11-8.bulk", 3, [[1e6, 1e7, 1e8], [1e-4, 5e-4, 1e-3]], (P, f) => ({ q: `A pressure increase of ${sig(P)} Pa squeezes a liquid's volume by a fraction ${sig(f)}. Find its bulk modulus.`, v: P / f, u: "Pa", w: [P * f, f / P], e: "B = ΔP / (ΔV/V). Water's is about 2.2 × 10⁹ Pa: it is very hard to compress.", c: "pressure" }));
  gen("c11-9.force", 1, [[1e5], [0.5, 1, 2, 4], [1, 2, 3]], (P, A, n) => ({ q: `Air pressure (≈ 10⁵ Pa) pushes on a table top of ${A} m². What force is that${n > 1 ? `, if the pressure were ${n} times greater` : ""}?`, v: P * n * A, u: "N", w: [P * n / A, P * A], e: "F = P × A. Air pushes on everything with tonnes of force; it is balanced from below, so we don't notice.", c: "pressure" }));
  gen("c11-11.cop", 3, [[250, 260, 270], [300, 310, 320]], (Tc, Th) => ({ q: `An ideal refrigerator keeps ${Tc} K inside a ${Th} K room. What is its best possible coefficient of performance?`, v: Tc / (Th - Tc), w: [Th / (Th - Tc), (Th - Tc) / Tc], e: "COP = T_cold/(T_hot − T_cold): heat removed per joule of work.", c: "entropy" }));
  gen("c11-11.Q", 1, [[100, 200, 400], [50, 100, 150, 300]], (dU, W) => ({ q: `A gas's internal energy rises by ${dU} J while it does ${W} J of work. How much heat was supplied?`, v: dU + W, u: "J", w: [dU - W, W - dU].map(x => Math.abs(x) || 10), e: "Q = ΔU + W.", c: "internal energy" }));
  gen("c11-11.adi", 4, [[273, 300], [2, 4, 8, 10], [["air (γ = 1.4)", 1.4], ["helium (γ = 1.67)", 5 / 3]]], (T, r, g) => ({ q: `${g[0]} at ${T} K is compressed adiabatically to 1/${r} of its volume. Find its new temperature. (TV^(γ−1) = constant)`, v: T * Math.pow(r, g[1] - 1), u: "K", w: [T * r, T * Math.pow(r, g[1])], e: "Quick compression heats gas strongly. Diesel engines ignite fuel with no spark this way.", steps: [`T₂ = T₁ × (V₁/V₂)^(γ−1)`, `= ${T} × ${r}^${sig(g[1] - 1)}`, `= ${sig(T * Math.pow(r, g[1] - 1))} K`], c: "internal energy" }));
  gen("c11-12.N", 2, [[1e5], [0.001, 0.01, 1], [273, 300, 350]], (P, V, T) => ({ q: `How many gas molecules are in ${V} m³ at ${sig(P)} Pa and ${T} K? (k = 1.38 × 10⁻²³ J/K)`, v: P * V / (1.38e-23 * T), w: [P * V / T, 1.38e-23 * T / (P * V)], e: "N = PV/kT.", c: "temperature" }));
  gen("c11-12.dof", 3, [[["monatomic (helium)", 3], ["diatomic (nitrogen)", 5]], [300, 600], [1, 2]], (g, T, n) => ({ q: `Find the internal energy of ${n} mol of ${g[0]} gas at ${T} K using equipartition. (R = 8.314)`, v: n * g[1] / 2 * 8.314 * T, u: "J", w: [n * 1.5 * 8.314 * T * (g[1] === 3 ? 5 / 3 : 3 / 5), n * 8.314 * T], e: `Each degree of freedom holds ½RT per mole: ${g[1]} of them here.`, c: "temperature" }));
  gen("c11-13.f", 1, [[0.01, 0.1, 0.5, 2, 5, 60]], T => ({ q: `An oscillation repeats every ${T} s. What is its frequency?`, v: 1 / T, u: "Hz", w: [T, 2 * PI / T], e: "f = 1/T.", c: "simple harmonic motion" }));
  gen("c11-13.amax", 2, [[0.02, 0.05, 0.1], [5, 10, 20]], (A, w) => ({ q: `A body in SHM has amplitude ${A} m and ω = ${w} rad/s. Find its maximum acceleration.`, v: A * w * w, u: "m/s²", w: [A * w, A * w * w * w], e: "a_max = Aω², at the extreme positions.", c: "simple harmonic motion" }));
  gen("c11-13.x", 3, [[0.1], [2, PI], [0.25, 0.5, 1, 1.5]], (A, w, t) => ({ q: `x = ${A} cos(${w === PI ? "π" : w}t) metres. Where is the body at t = ${t} s?`, v: A * Math.cos(w * t), u: "m", w: [A * Math.sin(w * t), -A * Math.cos(w * t)].map(x => Math.abs(x) < 1e-9 ? 0.05 : x), fmt: x => Math.abs(x) < 1e-9 ? "0" : sig(x), e: "Substitute t and use radians!", c: "simple harmonic motion" }));
  gen("c11-14.f", 1, [[340, 1480, 5000], [0.5, 1, 2, 4]], (v, l) => ({ q: `A wave travels at ${v} m/s with wavelength ${l} m. Find its frequency.`, v: v / l, u: "Hz", w: [v * l, l / v], e: "f = v/λ.", c: "resonance" }));
  gen("c11-14.odd", 2, [[100, 150, 200], [1, 2, 3, 4, 5]], (f1, n) => pickQ({ q: `A pipe closed at one end has fundamental ${f1} Hz. Can it produce ${n * f1} Hz?`, right: n % 2 ? "Yes (odd harmonic)" : "No (closed pipes give only odd harmonics)", pool: ["Yes (odd harmonic)", "No (closed pipes give only odd harmonics)"], e: "A closed end must be a node and the open end an antinode, allowing only 1, 3, 5... times the fundamental.", c: "resonance" }));
  const BANDS = ["radio waves", "microwaves", "infrared", "visible light", "ultraviolet", "X-rays", "gamma rays"];
  gen("c12-8.order", 1, [(() => { const o = []; BANDS.forEach((a, i) => BANDS.forEach((b, j) => { if (i < j) o.push([a, b]); })); return o; })()], ([a, b]) => ({ q: `Which has the higher frequency: ${a} or ${b}?`, o: [a, b], a: 1, e: "Order of rising frequency: radio, microwave, infrared, visible, UV, X-ray, gamma.", c: "electromagnetic spectrum" }));
  gen("c12-8.lam", 1, [[["GPS (1.575 GHz)", 1.575e9], ["4G (2.3 GHz)", 2.3e9], ["Wi-Fi 5 GHz", 5e9], ["AM radio (1 MHz)", 1e6], ["ISRO S-band (2.2 GHz)", 2.2e9], ["X-band (8.4 GHz)", 8.4e9]]], f => ({ q: `Find the wavelength of ${f[0]} signals.`, v: 3e8 / f[1], u: "m", w: [f[1] / 3e8, 3e8 / f[1] * 100], e: "λ = c/f.", c: "electromagnetic wave" }));
  gen("c12-9.mag", 1, [[-10, -20, -30], [15, 30, 60]], (u, v) => ({ q: `A lens forms an image at v = +${v} cm of an object at u = ${u} cm. What is the magnification?`, v: v / u, w: [u / v, -v / u], fmt: x => sig(x), e: "m = v/u for a lens. Negative means inverted.", c: "lens formula" }));
  gen("c12-9.prism", 3, [[60], [30, 37, 40, 45, 50]], (A, D) => ({ q: `A ${A}° prism gives a minimum deviation of ${D}°. Find its refractive index.`, v: Math.sin(deg((A + D) / 2)) / Math.sin(deg(A / 2)), w: [(A + D) / A, Math.sin(deg(D)) / Math.sin(deg(A))], fmt: x => x.toFixed(3), e: "n = sin((A + D_m)/2) / sin(A/2).", c: "refractive index" }));
  gen("c12-10.water", 3, [[1, 1.5, 2], [1.33]], (b, n) => ({ q: `Young's experiment gives a fringe width of ${b} mm in air. What is it when the whole apparatus is under water (n = ${n})?`, v: b / n, u: "mm", w: [b * n, b], e: "Wavelength shrinks to λ/n in water, so fringes squeeze to β/n.", c: "interference" }));
  gen("c12-11.Vs", 1, [[0.5, 1.2, 2, 3.5]], K => ({ q: `Photoelectrons leave a metal with maximum kinetic energy ${K} eV. What is the stopping potential?`, v: K, u: "V", w: [K * 2, K / 2, K * 1.6], e: "eV₀ = K_max, so in volts it has the same number.", c: "stopping potential" }));
  gen("c12-11.f0", 2, [[2.1, 2.3, 4.3, 4.7, 5.6]], phi => ({ q: `A metal has work function ${phi} eV. Find its threshold frequency. (h = 6.63 × 10⁻³⁴ J s)`, v: phi * 1.6e-19 / 6.63e-34, u: "Hz", w: [6.63e-34 / (phi * 1.6e-19), phi / 6.63e-34], e: "f₀ = φ/h.", c: "work function" }));
  const COL = [["red", 700], ["orange", 610], ["yellow", 580], ["green", 530], ["blue", 470], ["violet", 410]];
  gen("c12-11.cmp", 1, [(() => { const o = []; COL.forEach((a, i) => COL.forEach((b, j) => { if (i < j) o.push([a, b]); })); return o; })()], ([a, b]) => ({ q: `Which photon carries more energy: ${a[0]} light (≈ ${a[1]} nm) or ${b[0]} light (≈ ${b[1]} nm)?`, o: [a[0], b[0]], a: 1, e: "Shorter wavelength means higher frequency and more energy per photon (E = hc/λ).", c: "photon" }));
  gen("c12-12.v", 2, [[1, 2, 3, 4, 5, 6]], n => ({ q: `In Bohr's model the electron in hydrogen's ground state moves at about 2.19 × 10⁶ m/s. How fast does it move in level n = ${n}?`, v: 2.19e6 / n, u: "m/s", w: [2.19e6 / (n * n), 2.19e6 * n], e: "v_n = v₁/n.", c: "Bohr model" }));
  const TR2 = []; for (let a = 2; a <= 6; a++) for (let b = 1; b < a; b++) TR2.push([a, b]);
  gen("c12-12.f", 2, [TR2], ([a, b]) => { const E = 13.6 * (1 / (b * b) - 1 / (a * a)); return { q: `Find the frequency of the photon emitted in hydrogen's jump n = ${a} → n = ${b}.`, v: E * 1.6e-19 / 6.63e-34, u: "Hz", w: [E / 6.63e-34, 6.63e-34 / (E * 1.6e-19)], e: `f = ΔE/h with ΔE = ${sig(E)} eV.`, c: "spectral line" }; });
  gen("c12-13.half", 2, [[1000, 800, 6400], [1, 2, 3], [5, 10]], (N0, n, T) => ({ q: `A sample has ${N0} undecayed nuclei and a half-life of ${T} min. How many remain after ${n * T} min?`, v: N0 * Math.pow(0.5, n), w: [N0 / (2 * n), N0 - N0 / (2 * n), N0 * Math.pow(0.5, n + 1)], fmt: x => String(Math.round(x)), e: "N = N₀(½)^(t/T).", c: "half-life" }));
  gen("c12-13.iso", 1, [[["¹²C and ¹⁴C", "isotopes"], ["²H and ³H", "isotopes"], ["¹⁴C and ¹⁴N", "isobars"], ["⁴⁰Ar and ⁴⁰Ca", "isobars"], ["³H and ⁴He", "isotones"], ["¹³C and ¹⁴N", "isotones"]]], x => pickQ({ q: `${x[0]} are best described as...`, right: x[1], pool: ["isotopes", "isobars", "isotones"], e: "Isotopes: same Z. Isobars: same A. Isotones: same number of neutrons.", c: "isotope" }));
  gen("c12-13.mc2", 2, [[1e-3, 1e-6, 1, 0.01, 0.1]], m => ({ q: `If ${m} g of matter were converted completely into energy, how much energy would be released?`, v: m * 1e-3 * 9e16, u: "J", w: [m * 9e16, m * 1e-3 * 3e8], e: "E = mc² with m in kg.", c: "E = mc²" }));
  gen("c12-14.gap", 1, [[["copper", "overlapping bands", "conductor"], ["silicon", "1.1 eV", "semiconductor"], ["germanium", "0.7 eV", "semiconductor"], ["diamond", "5.5 eV", "insulator"], ["glass", "about 9 eV", "insulator"], ["gallium arsenide", "1.4 eV", "semiconductor"]]], x => pickQ({ q: `${x[0][0].toUpperCase() + x[0].slice(1)} has a band gap of ${x[1]}. What is it?`, right: x[2], pool: ["conductor", "semiconductor", "insulator"], e: "No gap: conductor. Small gap (under ~3 eV): semiconductor. Large gap: insulator.", c: "band gap" }));
  gen("c12-14.led", 2, [[1.8, 2.1, 2.3, 2.6, 3.0]], Eg => ({ q: `An LED's semiconductor has a band gap of ${Eg} eV. Roughly what wavelength does it emit?`, v: 1240 / Eg, u: "nm", w: [Eg * 1240 / 1000, 1240 * Eg], e: "λ ≈ 1240/E_g nm. Bigger gap, bluer light.", c: "band gap" }));
  gen("c12-14.solar", 2, [[0.5, 1, 2], [0.15, 0.2, 0.22], [1000, 600]], (A, eff, I) => ({ q: `A ${A} m² solar panel of ${eff * 100}% efficiency receives ${I} W/m² of sunlight. What power does it give?`, v: A * eff * I, u: "W", w: [A * I, eff * I], e: "P = intensity × area × efficiency. Solar cells are p-n junctions.", c: "p-n junction" }));

  /* ---------- second top-up for the thinner chapters ---------- */
  gen("c11-11.eff", 1, [[500, 1000, 2000], [100, 200, 300, 400]], (Q, W) => ({ q: `An engine takes in ${Q} J of heat and does ${W} J of work. What is its efficiency?`, v: W / Q * 100, u: "%", w: [(Q - W) / Q * 100, Q / W], e: `η = W/Q_in. The other ${Q - W} J is dumped as waste heat: no engine can turn all heat into work.`, c: "heat engine" }));
  const GAS = [["hydrogen (H₂)", 2], ["helium (He)", 4], ["nitrogen (N₂)", 28], ["oxygen (O₂)", 32], ["argon (Ar)", 40], ["carbon dioxide (CO₂)", 44]];
  gen("c11-12.vcmp", 1, [(() => { const o = []; GAS.forEach((a, i) => GAS.forEach((b, j) => { if (i < j) o.push([a, b]); })); return o; })()], ([a, b]) => ({ q: `At the same temperature, whose molecules move faster on average: ${a[0]} or ${b[0]}?`, o: [a[0], b[0]], a: a[1] < b[1] ? 0 : 1, e: `v_rms = √(3RT/M). Same temperature means same average kinetic energy, so the lighter molecule (M = ${Math.min(a[1], b[1])} g/mol) must move faster. This is why Earth has lost almost all its hydrogen.`, c: "temperature" }));
  gen("c11-12.mfp", 4, [[2e-10, 3e-10, 3.7e-10], [1e5, 100, 1e-3]], (d, P) => ({ q: `Gas molecules of diameter ${sig(d)} m are at 300 K and ${sig(P)} Pa. Find their mean free path. (λ = kT / (√2 π d² P), k = 1.38 × 10⁻²³ J/K)`, v: 1.38e-23 * 300 / (Math.SQRT2 * PI * d * d * P), u: "m", w: [1.38e-23 * 300 / (PI * d * d * P), 1.38e-23 * 300 / (Math.SQRT2 * PI * d * P)], e: "Lower pressure means fewer molecules to bump into, so the path between collisions grows. In a good vacuum it can be metres long.", c: "temperature" }));
  gen("c11-13.scale", 2, [[["a pendulum's length", "T ∝ √L"], ["the mass on a spring", "T ∝ √m"]], [2, 4, 9, 16, 0.25]], (s, n) => ({ q: `If ${s[0]} is multiplied by ${n}, its period is multiplied by...`, v: Math.sqrt(n), w: [n, 1 / Math.sqrt(n), n * n], fmt: x => "× " + sig(x), e: `${s[1]}, so the period changes by √${n}.`, c: "simple harmonic motion" }));
  gen("c12-8.use", 1, [[["TV remote controls", "infrared"], ["cancer radiotherapy", "gamma rays"], ["airport luggage scanners", "X-rays"], ["killing germs in water purifiers", "ultraviolet"], ["mobile phone signals", "microwaves"], ["FM radio broadcasts", "radio waves"], ["night-vision cameras", "infrared"], ["microwave ovens", "microwaves"], ["photosynthesis in leaves", "visible light"], ["LASIK eye surgery", "ultraviolet"], ["radar speed guns", "microwaves"], ["imaging broken bones", "X-rays"]]], x => pickQ({ q: `Which part of the electromagnetic spectrum is used for ${x[0]}?`, right: x[1], pool: BANDS, e: "Every band is the same kind of wave. Only the wavelength differs, and that decides what it can do.", c: "electromagnetic spectrum" }));
  gen("c12-10.brewster", 2, [[["water", 1.33], ["glass", 1.5], ["dense glass", 1.6], ["diamond", 2.42]]], m => ({ q: `At what angle of incidence is light reflected from ${m[0]} (n = ${m[1]}) completely polarised?`, v: Math.atan(m[1]) * 180 / PI, w: [Math.asin(1 / m[1]) * 180 / PI, Math.atan(1 / m[1]) * 180 / PI], fmt: x => x.toFixed(1) + "°", e: "Brewster's law: tan θ_B = n. Polarised sunglasses use this to cut glare from water and roads.", c: "polarisation" }));
  gen("c12-10.diffr", 3, [[500, 600, 700], [0.1, 0.2, 0.5]], (l, a) => ({ q: `Light of ${l} nm passes through a single slit ${a} mm wide. At what angle (in radians) is the first dark fringe?`, v: l * 1e-9 / (a * 1e-3), u: "rad", w: [2 * l * 1e-9 / (a * 1e-3), l * 1e-9 / (2 * a * 1e-3)], e: "a sin θ = λ for the first minimum. A narrower slit spreads the light wider.", c: "diffraction" }));
  gen("c12-11.dbe", 2, [[25, 50, 100, 150, 400, 1000, 2500, 10000]], V => ({ q: `An electron is accelerated from rest through ${V} V. What is its de Broglie wavelength?`, v: 1.227 / Math.sqrt(V), u: "nm", w: [1.227 / V, 1.227 * Math.sqrt(V)], e: "λ = 1.227/√V nm for an electron. At a few kV it is smaller than an atom, which is why electron microscopes see so much detail.", c: "de Broglie wavelength" }));
  gen("c12-11.mom", 2, [[300, 400, 500, 600, 700, 1000]], l => ({ q: `What is the momentum of one photon of wavelength ${l} nm?`, v: h / (l * 1e-9), u: "kg m/s", w: [h * l * 1e-9, h * c / (l * 1e-9)], e: "p = h/λ. Tiny, but billions of photons push solar sails.", c: "photon" }));
  gen("c12-11.rate", 3, [[[1e-3, "1 mW"], [5e-3, "5 mW"], [1, "1 W"]], [405, 532, 650]], (P, l) => ({ q: `A ${P[1]} laser emits light of ${l} nm. How many photons does it send out each second?`, v: P[0] * l * 1e-9 / (h * c), w: [P[0] / (h * c), P[0] * h * c / (l * 1e-9)], e: "N = P/E = Pλ/(hc).", c: "photon" }));
  gen("c12-12.KE", 2, [[1, 2, 3, 4, 5], ["kinetic", "potential"]], (n, t) => { const E = -13.6 / (n * n), v = t === "kinetic" ? -E : 2 * E; return { q: `In hydrogen's level n = ${n}, what is the electron's ${t} energy?`, v, u: "eV", w: [-v, v / 2, E === v ? -E : E], fmt: x => (x > 0 ? "+" : "") + sig(x), e: `Total E = −13.6/n² = ${sig(E)} eV. Then K = −E and U = 2E.`, c: "Bohr model" }; });
  const DEC = [["uranium-238", 238, 92, "alpha", "thorium-234"], ["radium-226", 226, 88, "alpha", "radon-222"], ["polonium-210", 210, 84, "alpha", "lead-206"], ["americium-241", 241, 95, "alpha", "neptunium-237"], ["plutonium-239", 239, 94, "alpha", "uranium-235"], ["thorium-234", 234, 90, "beta-minus", "protactinium-234"], ["carbon-14", 14, 6, "beta-minus", "nitrogen-14"], ["cobalt-60", 60, 27, "beta-minus", "nickel-60"], ["strontium-90", 90, 38, "beta-minus", "yttrium-90"], ["iodine-131", 131, 53, "beta-minus", "xenon-131"], ["tritium (hydrogen-3)", 3, 1, "beta-minus", "helium-3"], ["potassium-40", 40, 19, "beta-minus", "calcium-40"]];
  gen("c12-13.daughter", 2, [DEC], ([nm, A, Z, t, d]) => { const r = t === "alpha" ? [A - 4, Z - 2] : [A, Z + 1], f = x => `A = ${x[0]}, Z = ${x[1]}`; return pickQ({ q: `${nm[0].toUpperCase() + nm.slice(1)} (A = ${A}, Z = ${Z}) undergoes ${t} decay. What are the mass number and atomic number of the new nucleus?`, right: f(r), pool: [[A - 4, Z - 2], [A, Z + 1], [A, Z - 1], [A - 4, Z + 2], [A - 2, Z - 4], [A - 4, Z]].map(f), e: `${t === "alpha" ? "Alpha decay removes 2 protons and 2 neutrons: A − 4, Z − 2." : "Beta-minus decay turns a neutron into a proton: A stays, Z + 1."} The new nucleus is ${d}.`, c: "radioactivity" }); });
  const HL = [["iodine-131", 8.02, "day"], ["radon-222", 3.82, "day"], ["cobalt-60", 5.27, "year"], ["carbon-14", 5730, "year"], ["technetium-99m", 6.0, "hour"], ["polonium-210", 138, "day"]];
  gen("c12-13.lambda", 2, [HL], x => ({ q: `${x[0][0].toUpperCase() + x[0].slice(1)} has a half-life of ${x[1]} ${x[2]}s. What is its decay constant?`, v: 0.693 / x[1], u: "per " + x[2], w: [x[1] / 0.693, 0.693 * x[1]], e: "λ = ln 2 / T½ = 0.693 / T½.", c: "half-life" }));
  gen("c12-13.mean", 3, [HL], x => ({ q: `${x[0][0].toUpperCase() + x[0].slice(1)} has a half-life of ${x[1]} ${x[2]}s. What is its mean life?`, v: x[1] / 0.693, u: x[2] + "s", w: [x[1] * 0.693, x[1] / 2, x[1] * 2], e: "Mean life τ = 1/λ = T½ / 0.693 ≈ 1.44 T½. It is always longer than the half-life.", c: "half-life" }));
  gen("c12-13.BEn", 2, [[["helium-4", 28.3, 4], ["carbon-12", 92.2, 12], ["oxygen-16", 127.6, 16], ["iron-56", 492.3, 56], ["uranium-238", 1801.7, 238]]], x => ({ q: `${x[0][0].toUpperCase() + x[0].slice(1)} has a total binding energy of ${x[1]} MeV. What is its binding energy per nucleon?`, v: x[1] / x[2], u: "MeV", w: [x[1] / (x[2] / 2), x[1] * x[2] / 100], e: "Divide by the number of nucleons A. Iron-56 sits near the top of the curve, which is why fusion in stars stops at iron.", c: "binding energy" }));
  gen("c12-14.ripple", 1, [[50, 60], ["half-wave", "full-wave"]], (f, t) => ({ q: `A ${t} rectifier is fed ${f} Hz AC. What is the frequency of the output ripple?`, v: t === "half-wave" ? f : 2 * f, u: "Hz", w: [t === "half-wave" ? 2 * f : f, f / 2], e: "A half-wave rectifier passes one pulse per cycle. A full-wave rectifier flips the negative half too, so it gives two.", c: "p-n junction" }));
  gen("c12-14.I", 2, [[5, 9, 12], [100, 470, 1000]], (V, R) => ({ q: `A silicon diode (0.7 V drop) in forward bias is in series with a ${R} Ω resistor across a ${V} V battery. Find the current.`, v: (V - 0.7) / R * 1000, u: "mA", w: [V / R * 1000, (V + 0.7) / R * 1000], e: "I = (V − 0.7)/R. The diode takes its 0.7 V and the resistor gets the rest.", c: "p-n junction" }));

  /* ---------- wire extras and cross-links into pools ---------- */
  const add = (id, list) => { const P = G.POOLS[id]; if (!P) return; P.gens = (P.gens || []).concat(list); delete P._gens; delete P._fixed; };
  const X = {
    "c11-1": ["sc.conv", "sc.pow", "sc.speed", "sc.plx"], "c11-3": ["nw.range", "nw.cent"], "c11-4": ["nw.fma", "nw.acc", "nw.recoil", "nw.stick", "nw.fric"],
    "c11-5": ["nw.weight"], "c11-6": [], "c11-7": ["nw.orbv", "nw.orbT", "nw.esc", "nw.kepler", "nw.kepler2", "nw.gh", "nw.weight", "ready.energy", "ready.geo"],
    "c11-8": [], "c11-9": [], "c11-10": ["stars.wien"], "c11-11": [], "c11-12": [], "c11-13": [], "c11-14": ["sky.rise"],
    "c12-1": [], "c12-5": [], "c12-7": [], "c12-8": ["ready.delay", "ready.doppler", "c12-11.E"], "c12-9": ["ready.res"], "c12-10": ["ready.res"],
    "c12-11": ["st.emc2"], "c12-12": ["stars.wien"], "c12-13": ["st.emc2"], "c12-14": ["ready.panel"]
  };
  Object.entries(X).forEach(([id, list]) => add(id, list));
  add("scale", ["sc.fit", "sc.age", "sc.plx", "sc.voyager", "stars.plx", "ready.delay"]);
  add("sky", ["sky.angle", "sky.hand"]);
  add("origin", ["origin.age", "st.emc2"]);
  add("stars", ["stars.flux", "stars.radius"]);
  add("heroes", ["hist.order"]);
  add("newton", ["c11-3.height", "c11-4.pulley", "c11-5.spring", "c11-7.satE", "c11-13.tunnel", "c11-6.roll"]);
  add("myths", []);
  add("topic-gravity", ["c11-7.satE", "c11-13.tunnel", "ready.geo", "ready.energy", "stars.rs", "st.rs", "nw.weight"]);
  add("topic-light", ["c12-9.v", "c12-9.depth", "c12-9.combo", "c12-9.twolens", "c12-10.slit", "c12-10.path"]);
  add("topic-quantum", ["c12-11.p", "c12-11.N", "c12-11.h", "c12-11.ball", "c12-12.ion", "c12-12.lines", "c12-13.fission", "c12-13.fusion", "c12-13.decay"]);
  add("topic-cosmos", ["origin.age"]); add("topic-stars", ["stars.flux", "stars.radius"]); add("topic-moon", ["sky.angle", "sky.hand"]);
  ["quiz", "mega", "class11", "class12", "quantum"].forEach(id => { const P = G.POOLS[id]; if (P) { delete P._gens; delete P._fixed; } });
})();
