/* Topic quiz bank. Each question: [question, [options], correctIndex, explanation] */
DATA.topics = [
  { id: "solar", name: "The Solar System", c: "var(--g)", qs: [
    ["Which is the largest planet?", ["Saturn", "Jupiter", "Neptune", "Earth"], 1, "More than 1,300 Earths could fit inside Jupiter."],
    ["Which planet has the most known moons (as of 2025)?", ["Jupiter", "Saturn", "Uranus", "Mars"], 1, "Saturn passed 270 known moons after 128 new ones were announced in 2025."],
    ["The tallest volcano in the Solar System, Olympus Mons, is on", ["Venus", "Earth", "Mars", "Io"], 2, "About 22 km high, roughly two and a half Everests."],
    ["Which planet spins on its side?", ["Uranus", "Neptune", "Saturn", "Mercury"], 0, "Its axis is tilted about 98°, probably from a giant collision long ago."],
    ["Jupiter's Great Red Spot is", ["a volcano", "a storm bigger than Earth", "a crater", "a moon's shadow"], 1, "It has been raging for at least 150 years (though it is slowly shrinking)."],
    ["Saturn's rings are made mostly of", ["gas", "rock dust only", "chunks of water ice", "metal"], 2, "Pieces range from dust grains to house-sized blocks."],
    ["Which planet has the shortest year?", ["Mercury", "Venus", "Mars", "Earth"], 0, "Mercury circles the Sun in just 88 days."],
    ["Why was Pluto reclassified as a dwarf planet in 2006?", ["It is made of ice", "It has not cleared its orbit of other objects", "It is too far", "It has no moons"], 1, "The IAU's rule: a planet must dominate its orbital neighbourhood. Pluto shares its zone with many Kuiper belt objects."],
    ["The asteroid belt lies between", ["Earth and Mars", "Mars and Jupiter", "Jupiter and Saturn", "Neptune and Pluto"], 1, "Jupiter's gravity probably stopped a planet forming there."],
    ["Which moon has a thick atmosphere and lakes of liquid methane?", ["Europa", "Titan", "Io", "Ganymede"], 1, "Titan, Saturn's largest moon. NASA's Dragonfly helicopter is planned to fly there."],
    ["The most volcanically active body in the Solar System is", ["Earth", "Venus", "Io", "Mars"], 2, "Jupiter's tides squeeze Io and heat its insides."],
    ["Why is Jupiter's moon Europa exciting to scientists?", ["It is made of gold", "It probably hides a salty ocean under its ice", "It is the biggest moon", "It has rings"], 1, "Where there is liquid water, there might be life. NASA's Europa Clipper is on its way."],
    ["A comet's tail always points", ["behind its motion", "towards the Sun", "away from the Sun", "towards Earth"], 2, "Sunlight and the solar wind push the gas and dust away from the Sun."],
    ["Long-period comets are thought to come from the", ["asteroid belt", "Oort Cloud", "Moon", "Sun"], 1, "A giant shell of icy bodies far beyond Pluto."],
    ["The Sun holds about how much of the Solar System's mass?", ["50%", "75%", "90%", "99.8%"], 3, "Everything else, all planets included, is the leftover 0.2%."],
    ["Mars looks red because of", ["hot lava", "iron oxide (rust) in its dust", "red plants", "its atmosphere"], 1, "The whole planet is rusty."],
    ["The planet with the fastest winds is", ["Earth", "Jupiter", "Neptune", "Venus"], 2, "Neptune's winds reach about 2,000 km/h."],
    ["Which is hotter: the Sun's visible surface or its outer atmosphere, the corona?", ["the surface", "the corona", "they are equal", "neither is hot"], 1, "The surface is about 5,500 °C but the corona is over a million degrees. Why is still an active research question. Aditya-L1 studies it."],
    ["Sunspots look dark because they are", ["holes in the Sun", "cooler than the gas around them", "shadows of planets", "burnt areas"], 1, "About 3,500 to 4,500 °C. Still very hot, just darker in comparison."],
    ["Which planet would float in a (very large) bathtub of water?", ["Jupiter", "Saturn", "Earth", "Mercury"], 1, "Saturn's average density is about 0.69 g/cm³, less than water."],
    ["On Venus, the Sun rises in the", ["east", "west", "north", "it never rises"], 1, "Venus spins backwards compared to most planets."],
    ["How long does sunlight take to reach Neptune?", ["8 minutes", "40 minutes", "about 4 hours", "about 4 days"], 2, "Neptune is about 4.5 billion km away."],
    ["Which planet has the largest ocean of liquid water on its surface?", ["Mars", "Earth", "Venus", "Neptune"], 1, "Earth is the only place we know with surface oceans right now."]
  ]},
  { id: "moon", name: "Earth, Moon and Sky", c: "var(--a)", qs: [
    ["What causes the Moon's phases?", ["Earth's shadow", "Seeing different amounts of the Moon's sunlit half", "Clouds", "The Moon changing shape"], 1, "Half the Moon is always lit. Its position around us decides how much of that half we see."],
    ["A lunar eclipse can happen only at", ["new moon", "first quarter", "full moon", "any phase"], 2, "Earth must be between the Sun and the Moon."],
    ["A solar eclipse can happen only at", ["new moon", "full moon", "last quarter", "any phase"], 0, "The Moon must be between the Sun and Earth."],
    ["Why don't we get eclipses every month?", ["The Moon is too small", "The Moon's orbit is tilted about 5° to Earth's", "Clouds block them", "The Sun moves"], 1, "Usually the Moon passes a little above or below the line."],
    ["During a total lunar eclipse the Moon often turns", ["green", "blue", "coppery red", "invisible"], 2, "Earth's atmosphere bends red sunlight into the shadow. You are seeing all of Earth's sunsets at once."],
    ["Why are there about two high tides a day?", ["The Sun heats the sea", "The Moon's pull stretches Earth, making bulges on the near and far sides", "Wind", "Earth's magnetism"], 1, "Earth spins through both bulges every day."],
    ["The Moon is slowly moving away from Earth by about", ["3.8 cm per year", "1 km per year", "1 m per year", "it is getting closer"], 0, "Measured by bouncing lasers off mirrors left by Apollo astronauts."],
    ["Total solar eclipses are possible because", ["the Moon is bigger than the Sun", "the Sun is about 400 times wider and 400 times farther away than the Moon", "the Sun is dim", "Earth is round"], 1, "A cosmic coincidence: both appear almost the same size in our sky."],
    ["The sky is blue because", ["it reflects the oceans", "air scatters blue light much more than red", "space is blue", "of ozone"], 1, "Rayleigh scattering is proportional to 1/λ⁴, so short blue wavelengths scatter most."],
    ["Sunsets look red because", ["the Sun cools in the evening", "light passes through more air and loses its blue", "of pollution only", "the Sun is farther away"], 1, "Blue is scattered out along the long path, leaving red and orange."],
    ["The stars seem to circle around Polaris because", ["they orbit it", "Earth rotates on its axis", "Polaris pulls them", "the Sun moves"], 1, "Long-exposure photos show perfect circular star trails."],
    ["The Tropic of Cancer marks where the Sun is overhead at noon on", ["21 March", "21 June", "23 September", "22 December"], 1, "The June solstice. It passes through eight Indian states."],
    ["A 'supermoon' is", ["a new type of moon", "a full moon near its closest point to Earth", "a blue moon", "an eclipse"], 1, "It can look about 14% larger than a full moon at its farthest point."],
    ["We have leap years because Earth's orbit takes about", ["365 days exactly", "365.24 days", "366 days", "360 days"], 1, "An extra day every 4 years keeps the calendar in step (with a few exceptions)."],
    ["Why can't we see stars in the daytime?", ["They switch off", "Scattered sunlight makes the sky too bright", "They go behind the Sun", "They move away"], 1, "From the Moon, with no air, you can see stars in daylight."],
    ["At the equator, Earth's surface spins at about", ["100 km/h", "1,670 km/h", "30,000 km/h", "0 km/h"], 1, "You are moving very fast right now and do not feel it: Newton's first law."],
    ["Earth orbits the Sun at about", ["3 km/s", "30 km/s", "300 km/s", "3,000 km/s"], 1, "About 107,000 km/h."],
    ["Meteor showers happen when Earth", ["passes through a comet's leftover dust trail", "gets close to Mars", "has an eclipse", "tilts"], 0, "The Perseids in August come from comet Swift-Tuttle."],
    ["The Moon looks bigger near the horizon because", ["it is closer then", "our brain is tricked (the Moon illusion)", "the air magnifies it a lot", "it grows"], 1, "Photograph it and measure: it is the same size, even very slightly smaller."],
    ["Why is the sky black on the Moon even in daytime?", ["no air to scatter sunlight", "the Sun is dimmer", "the Moon is far", "dust"], 0, "No atmosphere, no blue sky."],
    ["Which direction does the Sun rise from?", ["west", "roughly east", "north", "south"], 1, "Earth spins from west to east, so the Sun appears to rise in the east."],
    ["How long does the Moon take to go from full moon to full moon?", ["7 days", "27.3 days", "29.5 days", "365 days"], 2, "27.3 days to orbit, plus about 2 extra days to catch up with the Sun's position."]
  ]},
  { id: "stars", name: "Stars and Starlight", c: "var(--k)", qs: [
    ["A star's colour tells you its", ["age", "surface temperature", "distance", "size only"], 1, "Blue stars are hottest, red stars are coolest."],
    ["The spectral classes from hottest to coolest are", ["A B C D E F G", "O B A F G K M", "M K G F A B O", "G K M O B A F"], 1, "Astronomers remember it as 'Oh Be A Fine Girl/Guy, Kiss Me'."],
    ["On the magnitude scale, a star of magnitude 1 is ___ than magnitude 6", ["dimmer", "100 times brighter", "6 times brighter", "the same"], 1, "Smaller numbers mean brighter. Five magnitudes is exactly a factor of 100."],
    ["Stellar parallax is used to measure", ["temperature", "distance to nearby stars", "mass", "speed of light"], 1, "Nearby stars shift slightly against far ones as Earth orbits the Sun."],
    ["The most common type of star in the Milky Way is", ["yellow like the Sun", "red dwarfs", "blue giants", "white dwarfs"], 1, "About three out of every four stars are small, dim red dwarfs. None is visible to the naked eye."],
    ["What stops a star from collapsing under its own gravity?", ["its spin", "pressure from hot gas and radiation", "magnetism", "nothing"], 1, "This balance is called hydrostatic equilibrium."],
    ["The temperature in the Sun's core is about", ["5,500 K", "1 million K", "15 million K", "1 billion K"], 2, "Hot enough to fuse hydrogen into helium."],
    ["About how much mass does the Sun turn into energy every second?", ["4 kg", "4 tonnes", "4 million tonnes", "4 billion tonnes"], 2, "E = mc². It fuses about 600 million tonnes of hydrogen, and about 4 million tonnes of that disappears as energy."],
    ["Helium was first discovered", ["in a lab in London", "in the Sun's spectrum during an 1868 eclipse seen from India", "in a volcano", "on the Moon"], 1, "Jules Janssen observed the eclipse from Guntur, India. Helium is named after Helios, the Sun."],
    ["Which is hotter, Betelgeuse or Rigel?", ["Betelgeuse", "Rigel", "same", "cannot tell"], 1, "Rigel is blue-white (about 12,000 K), Betelgeuse is red (about 3,600 K)."],
    ["A brown dwarf is", ["a dead star", "an object too small to fuse ordinary hydrogen", "a type of planet", "a black hole"], 1, "Below about 8% of the Sun's mass, roughly 80 Jupiters."],
    ["Dark lines in a star's spectrum show", ["dust", "which chemical elements are in the star", "its speed only", "nothing"], 1, "Each element absorbs its own set of colours."],
    ["Sirius B is", ["a red giant", "a white dwarf", "a planet", "a comet"], 1, "Sirius's tiny, super-dense companion."],
    ["Cepheid variable stars are useful because", ["they are the brightest", "their pulsing rate reveals their true brightness, and so their distance", "they never change", "they are nearby"], 1, "Discovered by Henrietta Leavitt. Used by Hubble to measure other galaxies."],
    ["The nearest star system to the Sun is", ["Sirius", "Alpha Centauri", "Vega", "Betelgeuse"], 1, "It includes Proxima Centauri, the closest single star at 4.24 light years."],
    ["Planets twinkle less than stars because", ["planets are brighter", "planets appear as tiny discs, not points", "planets are closer", "they have no atmosphere"], 1, "Atmospheric wobbles average out across a disc."],
    ["The fastest spinning pulsar known turns about", ["once a second", "30 times a second", "716 times a second", "1 million times a second"], 2, "Its surface moves at about a quarter of the speed of light."],
    ["A magnetar is", ["a magnet on a spacecraft", "a neutron star with an extreme magnetic field", "a planet", "a galaxy"], 1, "The strongest magnets in the universe."],
    ["Which element can a star NOT fuse to release energy?", ["hydrogen", "helium", "carbon", "iron"], 3, "Fusing iron absorbs energy. This triggers a massive star's collapse."],
    ["Every second, how many neutrinos from the Sun pass through each square centimetre of you?", ["none", "about 1,000", "about 65 billion", "exactly one"], 2, "They almost never interact, so they pass through you and the whole Earth."],
    ["A light year is about", ["9.46 trillion km", "150 million km", "1 billion km", "300,000 km"], 0, "The distance light travels in one year."],
    ["A Type Ia supernova happens when", ["a white dwarf gains too much mass and explodes", "two planets collide", "a black hole evaporates", "the Sun dies"], 0, "They all explode with similar brightness, making them 'standard candles'."]
  ]},
  { id: "cosmos", name: "Galaxies and the Universe", c: "var(--rose)", qs: [
    ["What type of galaxy is the Milky Way?", ["elliptical", "barred spiral", "irregular", "ring"], 1, "A spiral with a bar of stars across its centre."],
    ["Roughly how many stars are in the Milky Way?", ["1 million", "100 to 400 billion", "10 trillion", "exactly 1 billion"], 1, "Estimates vary because many stars are dim and hidden by dust."],
    ["How long does the Sun take to go once around the Milky Way?", ["1 year", "230 million years", "1 billion years", "13.8 billion years"], 1, "Last time we were here, the first dinosaurs were appearing."],
    ["The Milky Way's disc is about how wide?", ["1,000 light years", "100,000 light years", "1 million light years", "10 light years"], 1, "Light would take 100,000 years to cross it."],
    ["Redshift in a galaxy's light means", ["it is hot", "its light is stretched because it moves away / space expands", "it is red coloured", "it is close"], 1, "The more distant the galaxy, the larger the redshift."],
    ["The Cosmic Microwave Background was discovered in 1965 by", ["Einstein", "Penzias and Wilson", "Hubble", "Chandrasekhar"], 1, "They first blamed pigeon droppings on their antenna for the noise!"],
    ["Evidence for dark matter includes", ["stars at galaxy edges orbiting too fast", "dark clouds on photos", "black holes only", "eclipses"], 0, "Vera Rubin's measurements, plus gravitational lensing by invisible mass."],
    ["Dark energy is the name for whatever is", ["making black holes", "making the universe's expansion speed up", "dimming stars", "inside atoms"], 1, "Nobody yet knows what it actually is."],
    ["What sits at the centre of most large galaxies?", ["a giant star", "a supermassive black hole", "nothing", "a white dwarf"], 1, "Ours is Sagittarius A*, about 4 million Suns."],
    ["When two galaxies collide, stars inside them", ["almost never hit each other", "all explode", "turn into planets", "stop moving"], 0, "The space between stars is enormous."],
    ["Who showed in the 1920s that Andromeda is a separate galaxy?", ["Galileo", "Edwin Hubble", "Newton", "Carl Sagan"], 1, "Using Leavitt's Cepheid stars as distance markers."],
    ["Why is the night sky dark if the universe is full of stars?", ["Stars are too small", "The universe has a finite age and is expanding", "Dust blocks everything", "Earth's shadow"], 1, "This is Olbers' paradox. Light from very far away has not reached us yet, and expansion dims it."],
    ["The Magellanic Clouds are", ["storms on Jupiter", "small galaxies orbiting the Milky Way", "nebulae in Orion", "comets"], 1, "Visible to the naked eye from the Southern Hemisphere."],
    ["A quasar is", ["a quiet star", "the blazing core of a galaxy powered by a supermassive black hole", "a pulsar", "a planet"], 1, "Some outshine their whole galaxy of billions of stars."],
    ["Gravitational lensing was first confirmed during the solar eclipse of", ["1776", "1919", "1969", "2019"], 1, "Starlight passing the Sun was bent by the amount Einstein predicted."],
    ["On the largest scales, galaxies are arranged in", ["a perfect grid", "filaments and walls around huge empty voids: the cosmic web", "one big ball", "circles"], 1, "Like foam or a spider web."],
    ["Elliptical galaxies mostly contain", ["young blue stars", "old stars and little gas", "only black holes", "only planets"], 1, "They have mostly stopped making new stars."],
    ["The Hubble constant is about 70 km/s per Mpc. What is the 'Hubble tension'?", ["a broken telescope", "different methods give about 67 or 73, and nobody knows why", "a type of star", "a force"], 1, "It might hint at new physics. A real unsolved puzzle."],
    ["Which two elements were made in the first few minutes after the Big Bang?", ["iron and gold", "hydrogen and helium", "carbon and oxygen", "silicon and neon"], 1, "Heavier elements came much later, inside stars."],
    ["How many galaxies are there in the observable universe?", ["about 100", "about a million", "hundreds of billions or more", "exactly one"], 2, "Estimates range up to about 2 trillion."],
    ["The Milky Way and Andromeda are the biggest members of the", ["Local Group", "Virgo Cluster only", "Solar System", "Orion Arm"], 0, "A group of dozens of galaxies."]
  ]},
  { id: "bh", name: "Black Holes and Relativity", c: "var(--o)", qs: [
    ["The speed of light in vacuum is about", ["300 km/s", "3 × 10⁸ m/s", "3 × 10⁵ m/s", "infinite"], 1, "About 300,000 km every second."],
    ["Can anything with mass travel at the speed of light?", ["yes, rockets", "no, it would need infinite energy", "yes, if light enough", "only electrons"], 1, "Only massless things like light travel at exactly c."],
    ["Special relativity says a moving clock", ["runs fast", "runs slow compared to a stationary observer", "stops", "runs backwards"], 1, "Time dilation. Tiny at everyday speeds, huge near light speed."],
    ["E = mc² tells us that", ["energy is heavy", "mass and energy can convert into each other", "light has mass", "c is small"], 1, "A small mass holds a huge amount of energy because c² is enormous."],
    ["Muons created high in the atmosphere reach the ground because", ["they are very heavy", "time dilation makes them live longer from our view", "they are pulled by gravity", "they are light"], 1, "Without relativity most would decay before reaching the surface."],
    ["Where can light travel in a circle around a black hole?", ["at the event horizon", "at 1.5 times the horizon radius (photon sphere)", "at 10 times", "nowhere"], 1, "Light could orbit there, unstably."],
    ["'Spaghettification' happens because", ["black holes are hot", "gravity pulls much harder on your feet than your head", "of magnetism", "of pasta"], 1, "Tidal stretching. It is strongest near small black holes."],
    ["The black hole at our galaxy's centre has a mass of about", ["1 Sun", "4 million Suns", "1 billion Suns", "4 Earths"], 1, "Sagittarius A*, confirmed by tracking stars around it."],
    ["Gravitational waves travel at", ["the speed of sound", "the speed of light", "half the speed of light", "instantly"], 1, "Confirmed in 2017 when light and gravitational waves from a neutron star collision arrived together."],
    ["LIGO detects changes in its 4 km arms smaller than", ["a hair", "an atom", "1/10,000 of a proton's width", "a millimetre"], 2, "The most precise measurement ever made."],
    ["A fast-moving object appears shorter along its motion. This is", ["length contraction", "redshift", "refraction", "diffraction"], 0, "Another prediction of special relativity."],
    ["In the twin paradox, the twin who travels at near light speed and returns is", ["older", "younger", "the same age", "invisible"], 1, "The travelling twin experiences less time."],
    ["Clocks at higher altitude (weaker gravity) run", ["slower", "faster", "the same", "backwards"], 1, "Measured by atomic clocks. GPS must correct for this."],
    ["Einstein's Nobel Prize (1921) was for", ["relativity", "the photoelectric effect", "E = mc²", "black holes"], 1, "Relativity was still considered too controversial."],
    ["General relativity explained a tiny wobble in which planet's orbit that Newton could not?", ["Earth", "Mercury", "Mars", "Neptune"], 1, "43 arcseconds per century of extra precession."],
    ["The event horizon radius of a 10-solar-mass black hole is about", ["3 km", "30 km", "3,000 km", "300,000 km"], 1, "About 3 km per solar mass."],
    ["Wormholes are", ["proven and observed", "allowed by the equations but never observed", "common in the Solar System", "impossible to imagine"], 1, "A fun idea, but no evidence yet. Two sides of the coin."],
    ["Kip Thorne, science adviser for 'Interstellar', won the 2017 Nobel Prize for", ["black hole images", "detecting gravitational waves (LIGO)", "dark matter", "exoplanets"], 1, "Shared with Rainer Weiss and Barry Barish."],
    ["Is a black hole a hole?", ["yes, a hole in space", "no, it is an extremely compact mass", "it is a tunnel", "it is a star"], 1, "It is a region where so much mass is packed that nothing escapes."],
    ["If you watch a friend fall towards a black hole, they appear to", ["speed up and vanish instantly", "slow down and fade redder near the horizon", "bounce back", "turn blue"], 1, "Gravitational time dilation and redshift. From their view, they cross it normally."],
    ["Most stellar black holes weigh", ["less than the Earth", "about 5 to a few tens of Suns", "a billion Suns", "exactly one Sun"], 1, "Some mergers seen by LIGO produced black holes over 100 Suns."]
  ]},
  { id: "light", name: "Light and Telescopes", c: "var(--b)", qs: [
    ["A refracting telescope uses ___ and a reflecting telescope uses ___", ["mirrors, lenses", "lenses, mirrors", "prisms, lenses", "radio, light"], 1, "Galileo's telescope was a refractor. Newton built the first practical reflector."],
    ["Big modern telescopes use mirrors because", ["mirrors are cheap and can be supported from behind, with no colour blurring", "lenses are illegal", "mirrors magnify more", "tradition"], 0, "A giant glass lens would sag under its own weight."],
    ["The James Webb Space Telescope mainly observes in", ["X-rays", "ultraviolet", "infrared", "radio"], 2, "To see the stretched light of the first galaxies and look through dust."],
    ["JWST's main mirror is made of how many gold-coated segments?", ["1", "6", "18", "100"], 2, "18 hexagons forming a 6.5 m mirror, folded up to fit in the rocket."],
    ["JWST orbits near", ["the ISS", "the Moon", "the Sun-Earth L2 point, 1.5 million km away", "Mars"], 2, "It stays in Earth's shadow side to keep its instruments cold."],
    ["X-ray telescopes must be in space because", ["X-rays are too fast", "Earth's atmosphere absorbs X-rays", "they are heavy", "X-rays are dangerous on Earth"], 1, "Chandra and AstroSat work from orbit."],
    ["India's Giant Metrewave Radio Telescope (GMRT) is near", ["Pune", "Chennai", "Kolkata", "Jaipur"], 0, "30 dishes, each 45 m wide, spread over 25 km."],
    ["A telescope's light-gathering power depends on", ["its length", "the area of its main lens or mirror", "the eyepiece", "its colour"], 1, "Double the diameter, collect 4 times the light."],
    ["The magnifying power of a simple telescope is", ["f_objective × f_eyepiece", "f_objective / f_eyepiece", "f_eyepiece / f_objective", "always 10"], 1, "A long objective focal length and short eyepiece give high magnification."],
    ["Adaptive optics helps telescopes by", ["adding colour", "bending mirrors hundreds of times a second to cancel atmospheric twinkling", "zooming", "cooling"], 1, "Ground telescopes can then approach space-like sharpness."],
    ["Chromatic aberration is", ["a colour filter", "different colours focusing at different points through a lens", "a lens crack", "an eye disease"], 1, "Mirrors do not suffer from it."],
    ["Galileo's telescope in 1610 discovered", ["Saturn's rings clearly", "four moons of Jupiter", "Pluto", "black holes"], 1, "Io, Europa, Ganymede and Callisto: proof that not everything orbits Earth."],
    ["Visible light has wavelengths of about", ["1 to 10 nm", "400 to 700 nm", "1 mm to 1 m", "1 to 10 μm"], 1, "Violet is shortest, red is longest."],
    ["Which light has the most energy per photon?", ["radio", "infrared", "visible", "gamma rays"], 3, "Shorter wavelength, higher energy."],
    ["Light in glass (n ≈ 1.5) travels at about", ["3 × 10⁸ m/s", "2 × 10⁸ m/s", "1 × 10⁸ m/s", "4.5 × 10⁸ m/s"], 1, "v = c/n."],
    ["Rainbows form because raindrops", ["reflect only", "refract, disperse and internally reflect sunlight", "are coloured", "scatter blue light"], 1, "The Sun must be behind you."],
    ["The Vera C. Rubin Observatory has", ["the largest digital camera ever built for astronomy", "no camera", "a radio dish", "the biggest lens"], 0, "A 3.2-gigapixel camera. Its first images were released in 2025."],
    ["India's first dedicated multi-wavelength space observatory is", ["Chandrayaan", "AstroSat", "Aditya-L1", "Mangalyaan"], 1, "Launched in 2015, it sees in UV, visible and X-rays at once."],
    ["Observatories are built on high mountains because", ["it is closer to the stars", "there is less air, less water vapour and less light pollution", "it is cooler for staff", "tradition"], 1, "Hanle in Ladakh hosts one of India's highest observatories."],
    ["A bigger telescope can separate two close stars better because its resolving limit θ ≈ 1.22λ/D", ["increases with D", "decreases with D", "is independent of D", "depends on colour only"], 1, "Larger D, smaller θ, finer detail."],
    ["The Hubble Space Telescope was launched in", ["1969", "1990", "2010", "2021"], 1, "It orbits about 540 km above Earth and was repaired by astronauts five times."]
  ]},
  { id: "explore", name: "Space Exploration and ISRO", c: "var(--good)", qs: [
    ["The first artificial satellite was", ["Explorer 1", "Sputnik 1", "Aryabhata", "Hubble"], 1, "Launched by the Soviet Union in 1957."],
    ["The first human in space was", ["Neil Armstrong", "Yuri Gagarin", "Rakesh Sharma", "Valentina Tereshkova"], 1, "12 April 1961, one orbit in 108 minutes."],
    ["The first woman in space was", ["Kalpana Chawla", "Sally Ride", "Valentina Tereshkova", "Sunita Williams"], 2, "In 1963."],
    ["The first humans walked on the Moon in", ["1961", "1969", "1975", "1984"], 1, "Apollo 11: Neil Armstrong and Buzz Aldrin."],
    ["The first Indian in space was", ["Kalpana Chawla", "Rakesh Sharma", "Shubhanshu Shukla", "Vikram Sarabhai"], 1, "1984, aboard a Soviet Soyuz. Asked how India looked from space, he said 'Saare Jahan Se Achha'."],
    ["The first Indian to visit the International Space Station was", ["Rakesh Sharma", "Shubhanshu Shukla", "Sunita Williams", "Kalpana Chawla"], 1, "On the Axiom-4 mission in June 2025."],
    ["India's first satellite was", ["Rohini", "Aryabhata", "INSAT-1A", "Bhaskara"], 1, "Launched in 1975 on a Soviet rocket."],
    ["Who is called the father of India's space programme?", ["APJ Abdul Kalam", "Vikram Sarabhai", "Homi Bhabha", "C. V. Raman"], 1, "ISRO was founded in 1969."],
    ["ISRO's main launch site is", ["Thumba", "Sriharikota", "Bengaluru", "Ahmedabad"], 1, "The Satish Dhawan Space Centre, on an island on the east coast."],
    ["In 2017 ISRO's PSLV set a record by launching", ["1 satellite", "31 satellites", "104 satellites", "500 satellites"], 2, "PSLV-C37, in a single launch."],
    ["Chandrayaan-1 (2008) helped discover", ["life on the Moon", "water molecules on the Moon", "gold", "a Moon ring"], 1, "Together with NASA's instrument on board."],
    ["Aditya-L1 studies", ["Mars", "the Sun, from 1.5 million km away", "Jupiter", "black holes"], 1, "Launched in September 2023, it reached the L1 point in January 2024."],
    ["In January 2025, the SpaDeX mission made India the ___ country to dock two spacecraft in orbit", ["first", "second", "fourth", "tenth"], 2, "After the USA, Russia and China."],
    ["NISAR, launched in July 2025, is a joint Earth-watching radar satellite of ISRO and", ["ESA", "NASA", "JAXA", "Roscosmos"], 1, "It scans nearly all of Earth's land and ice every 12 days."],
    ["The first uncrewed Gaganyaan test flight is planned to carry", ["a dog", "a half-humanoid robot called Vyommitra", "a monkey", "nothing"], 1, "To test life support before Indian astronauts fly."],
    ["Voyager 1 entered interstellar space in", ["1977", "1990", "2012", "2024"], 2, "It launched in 1977 and is still sending data."],
    ["The ISS goes around Earth about every", ["24 hours", "90 minutes", "1 week", "10 minutes"], 1, "Astronauts see about 16 sunrises a day."],
    ["Rockets usually launch towards the east because", ["it is tradition", "Earth's spin gives them a free speed boost", "the Sun rises there", "winds"], 1, "Near the equator this boost is about 0.46 km/s."],
    ["A cryogenic rocket engine burns", ["kerosene and air", "liquid hydrogen and liquid oxygen", "solid fuel", "petrol"], 1, "Liquid hydrogen must be kept at about −253 °C."],
    ["The first powered flight on another planet was made by", ["Pragyan", "Ingenuity helicopter on Mars", "Curiosity", "Vikram"], 1, "In April 2021."],
    ["New Horizons flew past Pluto in", ["2006", "2015", "2020", "never"], 1, "It showed a giant heart-shaped plain of nitrogen ice."],
    ["Astronauts living long in microgravity tend to lose", ["height", "bone and muscle mass", "memory", "eyesight completely"], 1, "They exercise about 2 hours a day on the ISS to fight this."],
    ["Mangalyaan reached Mars orbit on its first attempt in", ["2008", "2014", "2019", "2023"], 1, "24 September 2014, at a very low cost for an interplanetary mission."],
    ["Chandrayaan-3's rover was named", ["Vikram", "Pragyan", "Aryabhata", "Kalpana"], 1, "Pragyan means wisdom. The lander was Vikram."]
  ]},
  { id: "motion", name: "Motion and Newton's Laws", c: "var(--good)", qs: [
    ["Inertia of a body depends on its", ["speed", "mass", "colour", "shape"], 1, "More mass, more resistance to change in motion."],
    ["1 newton equals", ["1 kg m/s", "1 kg m/s²", "1 kg m²/s", "1 J/s"], 1, "The force that accelerates 1 kg at 1 m/s²."],
    ["Momentum is", ["mass × acceleration", "mass × velocity", "force × time", "½mv²"], 1, "p = mv. Impulse (FΔt) changes it."],
    ["Airbags and seat belts reduce injury by", ["reducing your mass", "increasing the stopping time, so the force is smaller", "increasing speed", "adding friction"], 1, "F = Δp/Δt."],
    ["In uniform circular motion, a body has", ["constant velocity", "constant speed but changing velocity", "no acceleration", "increasing speed"], 1, "Velocity includes direction, which keeps changing."],
    ["Action and reaction forces", ["cancel each other", "act on different bodies", "act on the same body", "are unequal"], 1, "That is why they do not cancel."],
    ["Maximum static friction is usually ___ kinetic friction", ["less than", "greater than", "equal to", "zero compared to"], 1, "Getting something to start sliding is harder than keeping it sliding."],
    ["You feel heavier in a lift that is", ["moving up at steady speed", "accelerating upwards", "accelerating downwards", "stopped"], 1, "The floor pushes up with m(g + a)."],
    ["If a lift cable snapped, a person inside would feel", ["double weight", "weightless", "normal", "heavier"], 1, "Everything falls together. This is how astronauts train in 'vomit comet' planes."],
    ["You run once around a 400 m circular track. Your displacement is", ["400 m", "200 m", "0 m", "800 m"], 2, "You ended where you started."],
    ["Ignoring air, maximum range is at", ["30°", "45°", "60°", "90°"], 1, "sin 2θ = 1."],
    ["Two trains move towards each other at 60 km/h and 40 km/h. Their relative speed is", ["20 km/h", "100 km/h", "2400 km/h", "40 km/h"], 1, "Speeds add when moving towards each other."],
    ["A gun recoils when fired because of", ["friction", "conservation of momentum", "gravity", "heat"], 1, "Bullet forward, gun backward, total momentum stays zero."],
    ["Roads are banked at curves to", ["drain rain only", "help provide the centripetal force", "look nice", "slow cars"], 1, "Part of the normal force points towards the centre."],
    ["Torque is greatest when you push a door", ["near the hinge", "far from the hinge, perpendicular to the door", "along the door", "at the top"], 1, "τ = rF sin θ."],
    ["Newton's second law in its most general form is", ["F = mv", "F = dp/dt", "F = m/a", "F = ½mv²"], 1, "It also works when mass changes, like a rocket burning fuel."],
    ["A feather and a hammer dropped on the Moon", ["hammer lands first", "feather lands first", "land together", "float"], 2, "No air resistance. Shown by Apollo 15 astronaut David Scott in 1971."],
    ["Why is it hard to walk on ice?", ["ice is cold", "very little friction to push against", "ice is heavy", "ice pushes you"], 1, "Walking needs friction: you push the ground back, it pushes you forward."],
    ["The SI unit of impulse is", ["N", "N s", "N/s", "J"], 1, "Same as momentum, kg m/s."],
    ["A rocket works in space by", ["pushing against air", "pushing exhaust gas backwards (third law)", "using wings", "magnetism"], 1, "It works even better without air."],
    ["An object moving in a circle whose string snaps flies off", ["towards the centre", "along the tangent", "outwards along the radius", "in a spiral"], 1, "It continues in a straight line in the direction it was moving."]
  ]},
  { id: "gravity", name: "Gravity and Orbits", c: "var(--o)", qs: [
    ["The value of G is about", ["9.8 N/kg", "6.67 × 10⁻¹¹ N m²/kg²", "3 × 10⁸", "1.6 × 10⁻¹⁹"], 1, "First measured by Henry Cavendish in 1798."],
    ["Acceleration due to gravity ___ as you go deep into a mine", ["increases", "decreases", "stays same", "becomes infinite"], 1, "g_d = g(1 − d/R)."],
    ["A geostationary satellite orbits about how high above Earth?", ["400 km", "2,000 km", "36,000 km", "384,000 km"], 2, "About 35,786 km. It circles once per day above the equator."],
    ["Kepler's first law says planet orbits are", ["circles", "ellipses with the Sun at one focus", "squares", "spirals"], 1, "Most are nearly circular, but not quite."],
    ["Kepler's second law means a planet moves", ["at constant speed", "fastest when closest to the Sun", "slowest near the Sun", "backwards sometimes"], 1, "Equal areas in equal times."],
    ["The escape speed from the Moon is about", ["0.24 km/s", "2.4 km/s", "11.2 km/s", "42 km/s"], 1, "Low escape speed is why the Moon lost its air."],
    ["The total energy of an orbiting satellite is", ["positive", "zero", "negative", "infinite"], 2, "Negative energy means it is bound to Earth."],
    ["A satellite's kinetic energy equals ___ of its potential energy's size", ["twice", "half", "equal", "a quarter"], 1, "K = GMm/2r, U = −GMm/r."],
    ["Low Earth orbit takes about", ["24 h", "90 min", "1 week", "10 min"], 1, "The lower the orbit, the faster it goes."],
    ["If Earth's mass doubled with the same radius, g would", ["halve", "double", "stay the same", "quadruple"], 1, "g = GM/R²."],
    ["The force between two 1 kg masses 1 m apart is", ["9.8 N", "1 N", "6.67 × 10⁻¹¹ N", "zero"], 2, "Gravity is incredibly weak between everyday objects."],
    ["The weakest of the four fundamental forces is", ["electromagnetic", "strong nuclear", "weak nuclear", "gravity"], 3, "But it adds up over huge masses and has infinite range."],
    ["Polar satellites are mainly used for", ["TV broadcasting", "mapping and Earth observation", "GPS only", "talking to the Moon"], 1, "As Earth spins below, they eventually see every part of it."],
    ["Geostationary satellites are mainly used for", ["mapping", "communication and weather", "space tourism", "mining"], 1, "Like India's INSAT and GSAT series."],
    ["You weigh slightly more at", ["the top of Everest", "sea level", "on a plane", "all equal"], 1, "Farther from Earth's centre, g is smaller."],
    ["A 'gravity assist' lets a spacecraft", ["stop", "gain speed by swinging past a planet", "land softly", "make fuel"], 1, "Voyager used Jupiter and Saturn to fling itself outwards."],
    ["By Kepler's third law, a planet 4 times farther from the Sun takes ___ times longer to orbit", ["4", "8", "16", "2"], 1, "T ∝ r^1.5, and 4^1.5 = 8."],
    ["A 60 kg person on the Moon (g = 1.62 m/s²) has a mass of", ["10 kg", "60 kg", "97 kg", "0 kg"], 1, "Mass never changes. Their weight would be about 97 N instead of about 590 N."],
    ["Newton's shell theorem says a uniform sphere pulls outside objects as if", ["it had no mass", "all its mass were at its centre", "it were a ring", "it were flat"], 1, "That is why we can treat planets as points."],
    ["Why doesn't the Moon fall onto Earth?", ["No gravity there", "It is falling, but moving sideways fast enough to keep missing", "Magnetism holds it", "It is too light"], 1, "Orbit = falling with style."],
    ["Escape speed from Earth's surface is about", ["7.9 km/s", "11.2 km/s", "30 km/s", "3 km/s"], 1, "√2 times the orbital speed near the surface."]
  ]},
  { id: "energy", name: "Energy, Heat and Matter", c: "var(--k)", qs: [
    ["Energy can be", ["created", "destroyed", "changed from one form to another", "created and destroyed"], 2, "The law of conservation of energy."],
    ["Absolute zero is", ["0 °C", "−100 °C", "−273.15 °C", "−459 °C"], 2, "The lowest possible temperature, 0 K."],
    ["If you double your speed, your kinetic energy becomes", ["2 times", "4 times", "8 times", "same"], 1, "KE = ½mv². That is why speeding is so dangerous."],
    ["1 kilowatt-hour equals", ["1000 J", "3.6 × 10⁶ J", "3600 J", "1 J"], 1, "The 'unit' on your electricity bill."],
    ["In space, heat can travel only by", ["conduction", "convection", "radiation", "sound"], 2, "There is no matter to conduct or convect. Sunlight reaches us by radiation."],
    ["A metal spoon feels colder than a wooden one at the same temperature because metal", ["is colder", "conducts heat away from your hand faster", "is heavier", "is shiny"], 1, "Your skin senses heat flow, not temperature."],
    ["Water is densest at", ["0 °C", "4 °C", "100 °C", "−4 °C"], 1, "So lakes freeze from the top, and fish survive below."],
    ["Heat flows naturally from", ["cold to hot", "hot to cold", "big to small", "either way"], 1, "The second law of thermodynamics."],
    ["Can any heat engine be 100% efficient?", ["yes", "no", "only petrol engines", "only in space"], 1, "Some heat must always be rejected to a colder place."],
    ["Water boils at a lower temperature on high mountains because", ["the air is cleaner", "air pressure is lower", "it is colder", "gravity is less"], 1, "Food takes longer to cook. Pressure cookers do the opposite."],
    ["The temperature of a gas is a measure of the molecules'", ["colour", "average kinetic energy", "size", "number"], 1, "Faster molecules, higher temperature."],
    ["Stars are mostly made of", ["solid", "liquid", "plasma", "ice"], 2, "Plasma is gas so hot that electrons are stripped from atoms."],
    ["Insects like pond skaters walk on water thanks to", ["viscosity", "surface tension", "buoyancy only", "magnetism"], 1, "The water surface acts like a stretched skin."],
    ["Airplane wings get lift from", ["only Bernoulli's principle", "only pushing air down", "both pressure differences and deflecting air down, which are two views of the same flow", "hot air"], 2, "Popular explanations argue about this. Physicists agree both descriptions work together."],
    ["Why is ice slippery?", ["pressure melts it, fully explained", "a thin, liquid-like surface layer, and scientists still debate the details", "it is wet inside", "it is magnetic"], 1, "The old 'pressure melting' story is too weak to explain it. A lovely open question."],
    ["Raindrops don't injure us because they", ["are soft", "reach terminal velocity (under about 9 m/s)", "evaporate", "are tiny"], 1, "Air drag balances their weight."],
    ["Hotter objects glow", ["redder", "bluer", "darker", "greener only"], 1, "Wien's law: λ_max × T = 2.9 × 10⁻³ m·K."],
    ["The total power radiated by a hot object is proportional to", ["T", "T²", "T⁴", "1/T"], 2, "Stefan–Boltzmann law. Double the temperature, 16 times the power."],
    ["An object floats if the buoyant force equals its weight. The buoyant force equals", ["its volume", "the weight of fluid it displaces", "its mass", "air pressure"], 1, "Archimedes' principle."],
    ["Hooke's law says, within the elastic limit,", ["stress ∝ 1/strain", "stress ∝ strain", "stress = 0", "strain is constant"], 1, "Springs and wires stretch in proportion to the load."],
    ["During boiling, added heat", ["raises the temperature", "turns water into steam without raising the temperature", "is lost", "cools the water"], 1, "Latent heat of vaporisation."]
  ]},
  { id: "waves", name: "Waves and Sound", c: "var(--b)", qs: [
    ["Sound cannot travel through", ["water", "steel", "air", "vacuum"], 3, "It needs a medium to vibrate."],
    ["The speed of sound in air at 20 °C is about", ["34 m/s", "343 m/s", "3,430 m/s", "3 × 10⁸ m/s"], 1, "It is faster in water (about 1,480 m/s) and steel (about 5,000 m/s)."],
    ["You see lightning before hearing thunder because", ["light is much faster than sound", "thunder happens later", "ears are slow", "clouds block sound"], 0, "Count seconds and divide by 3 for the distance in km."],
    ["The pitch of an ambulance siren is higher as it approaches. This is the", ["echo", "Doppler effect", "resonance", "beats"], 1, "The same effect in light gives redshift and blueshift of stars."],
    ["Humans can hear roughly", ["2 to 200 Hz", "20 Hz to 20 kHz", "20 kHz to 200 kHz", "all frequencies"], 1, "Bats and dolphins use ultrasound above 20 kHz."],
    ["Sound in air is a ___ wave; light is a ___ wave", ["transverse, longitudinal", "longitudinal, transverse", "both transverse", "both longitudinal"], 1, "Sound squeezes air along its path; light's fields wiggle sideways."],
    ["To hear a distinct echo, the reflecting wall must be at least about", ["1.7 m", "17 m", "170 m", "1.7 km"], 1, "Your ear needs about 0.1 s between sounds."],
    ["The Tacoma Narrows bridge collapse (1940) is often called 'resonance'. Engineers say it was mainly", ["simple resonance", "aeroelastic flutter, where wind and bridge motion fed each other", "an earthquake", "overloading"], 1, "A good example of checking popular explanations."],
    ["The wave equation is", ["v = f/λ", "v = fλ", "v = λ/f", "v = f + λ"], 1, "Speed = frequency × wavelength."],
    ["A pendulum's period depends on", ["its mass", "its length and g", "the size of the swing (for small swings)", "its colour"], 1, "T = 2π√(l/g)."],
    ["On the Moon, a pendulum swings", ["faster", "slower", "the same", "not at all"], 1, "Weaker gravity, longer period."],
    ["Two notes of 440 Hz and 444 Hz played together produce", ["4 beats per second", "884 Hz", "no sound", "2 beats per second"], 0, "Musicians use beats to tune instruments."],
    ["Scientists know Earth's outer core is liquid because", ["they drilled there", "S waves from earthquakes cannot pass through it", "it is hot", "of magnetism"], 1, "S waves are transverse and cannot travel through liquids."],
    ["Noise-cancelling headphones work by", ["blocking with foam only", "playing an opposite wave so the two cancel (destructive interference)", "turning up music", "magnetism"], 1, "Crest meets trough."],
    ["Loudness depends mainly on a sound wave's", ["frequency", "amplitude", "speed", "wavelength"], 1, "Pitch depends on frequency."],
    ["A sonic boom happens when an aircraft", ["lands", "travels faster than sound", "turns", "slows down"], 1, "Sound waves pile up into a shock wave."],
    ["You can hear someone around a corner but not see them because", ["sound is faster", "sound waves are long (metres), so they diffract much more than light", "light is blocked by air", "walls reflect only sound"], 1, "Diffraction is big when the wavelength is similar to the gap."],
    ["The period of a mass on a spring is", ["2π√(k/m)", "2π√(m/k)", "2πmk", "m/k"], 1, "Heavier mass, slower oscillation."],
    ["In a standing wave, points that never move are called", ["antinodes", "nodes", "crests", "troughs"], 1, "Antinodes swing the most."],
    ["The Sun 'rings' with sound-like pressure waves. Studying them is called", ["seismology", "helioseismology", "acoustics", "astrology"], 1, "It lets scientists see inside the Sun."]
  ]},
  { id: "em", name: "Electricity and Magnetism", c: "var(--m)", qs: [
    ["The charge of an electron is", ["1.6 × 10⁻¹⁹ C", "−1.6 × 10⁻¹⁹ C", "1 C", "9.1 × 10⁻³¹ C"], 1, "Every charge is a whole-number multiple of this."],
    ["Coulomb's law is an", ["inverse law", "inverse-square law", "linear law", "exponential law"], 1, "Like gravity."],
    ["Ohm's law states", ["V = I/R", "V = IR", "I = VR", "R = VI"], 1, "For many conductors at constant temperature."],
    ["You are fairly safe inside a metal car during lightning because", ["rubber tyres", "charge stays on the outside of the metal shell (Faraday cage)", "cars are low", "glass"], 1, "The electric field inside a closed conductor is zero."],
    ["Earth's magnetic field is produced by", ["a giant bar magnet inside", "moving molten iron in the outer core (geodynamo)", "the Moon", "the Sun"], 1, "It flips every few hundred thousand years on average."],
    ["A compass needle's north end points to Earth's geographic north because", ["there is a magnetic north pole there", "Earth's magnetic SOUTH pole is near geographic north", "of gravity", "of the Sun"], 1, "Opposite poles attract."],
    ["Auroras occur because", ["sunlight reflects off ice", "charged solar particles guided by Earth's magnetic field hit the upper atmosphere", "of lightning", "the Moon glows"], 1, "Oxygen glows green and red, nitrogen blue and purple."],
    ["Faraday's law says an emf is induced when", ["a magnet is still", "magnetic flux through a circuit changes", "current is steady", "there is light"], 1, "The basis of every generator."],
    ["Lenz's law says the induced current", ["helps the change", "opposes the change that caused it", "is always zero", "is always clockwise"], 1, "Otherwise energy would come from nothing."],
    ["Transformers work only with", ["DC", "AC", "both", "neither"], 1, "They need a changing flux."],
    ["India's household mains supply is", ["110 V, 60 Hz", "230 V, 50 Hz", "12 V DC", "440 V DC"], 1, "USA uses 120 V, 60 Hz."],
    ["Who first predicted electromagnetic waves?", ["Faraday", "Maxwell", "Hertz", "Newton"], 1, "Hertz produced them in the lab in 1887."],
    ["Light is", ["a sound wave", "an electromagnetic wave", "a stream of electrons", "a magnetic field only"], 1, "Maxwell's equations predicted its speed exactly."],
    ["Order of EM waves from low to high frequency:", ["gamma, X, UV, visible, IR, micro, radio", "radio, micro, IR, visible, UV, X, gamma", "visible first", "random"], 1, "Energy per photon increases along this list."],
    ["A bird sitting on a single high-voltage wire is safe because", ["birds are insulators", "there is almost no potential difference across its body", "the wire is off", "feathers"], 1, "Current needs a potential difference to flow through the bird."],
    ["Adding resistors in parallel makes the total resistance", ["larger", "smaller than the smallest one", "zero", "equal to the largest"], 1, "More paths for current."],
    ["Electric power is", ["P = V/I", "P = VI", "P = V + I", "P = I/V"], 1, "Also I²R or V²/R."],
    ["A superconductor has", ["infinite resistance", "zero resistance below a critical temperature", "normal resistance", "negative resistance"], 1, "MRI magnets use superconducting coils."],
    ["An electric motor converts", ["mechanical to electrical energy", "electrical to mechanical energy", "heat to light", "sound to electricity"], 1, "A generator does the reverse."],
    ["A capacitor stores energy in", ["a magnetic field", "an electric field", "chemical bonds", "heat"], 1, "U = ½CV²."],
    ["A diode allows current to flow", ["both ways equally", "mainly in one direction", "never", "only in light"], 1, "Used to turn AC into DC."],
    ["A typical lightning stroke carries a current of about", ["1 A", "30,000 A", "1 mA", "10 A"], 1, "For only tens of microseconds."]
  ]},
  { id: "quantum", name: "Atoms, Quantum and Nuclear", c: "var(--rose)", qs: [
    ["Rutherford's gold foil experiment showed the atom", ["is solid", "is mostly empty space with a tiny nucleus", "has no electrons", "is a pudding"], 1, "Done by Geiger and Marsden under Rutherford, 1909."],
    ["In Bohr's model, hydrogen's ground-state energy is", ["−13.6 eV", "0 eV", "+13.6 eV", "−3.4 eV"], 0, "Negative means the electron is bound."],
    ["The photoelectric effect shows that light", ["is only a wave", "comes in packets called photons", "has no energy", "is slow"], 1, "E = hf per photon."],
    ["Below the threshold frequency, increasing light intensity", ["ejects electrons", "ejects no electrons at all", "melts the metal", "doubles the energy"], 1, "Each photon lacks the energy to free an electron."],
    ["The de Broglie wavelength of a particle is", ["λ = hp", "λ = h/p", "λ = p/h", "λ = mc²"], 1, "Everything has a wavelength, even you (just incredibly tiny)."],
    ["Heisenberg's uncertainty principle says", ["measurements are always wrong", "you cannot know both position and momentum exactly at the same time", "atoms are uncertain", "energy is not conserved"], 1, "Δx Δp ≥ h/4π."],
    ["Nuclear power plants use", ["fusion", "fission of heavy nuclei like uranium-235", "burning coal", "chemical reactions"], 1, "Splitting heavy nuclei releases energy."],
    ["ITER, an international fusion experiment that India is part of, is being built in", ["India", "France", "USA", "Japan"], 1, "It aims to show fusion can produce more energy than it uses."],
    ["The half-life of carbon-14 is about", ["5.7 years", "5,730 years", "5.7 million years", "57 seconds"], 1, "Used to date things up to about 50,000 years old."],
    ["An alpha particle is", ["an electron", "a helium nucleus", "a photon", "a neutron"], 1, "Two protons and two neutrons."],
    ["The most tightly bound nuclei are near", ["hydrogen", "iron", "uranium", "helium"], 1, "Top of the binding energy curve."],
    ["Mass defect is converted into", ["heat only", "binding energy, by E = mc²", "new electrons", "nothing"], 1, "The whole is lighter than its parts."],
    ["Nebulae often look pink in photos because of hydrogen's", ["Lyman line", "H-alpha red line at 656 nm", "X-rays", "blue light"], 1, "From electrons dropping from level 3 to 2."],
    ["LASER stands for light amplification by", ["simple electricity", "stimulated emission of radiation", "solar energy", "strong electrons"], 1, "Einstein predicted stimulated emission in 1917."],
    ["The Sun's core is 'only' 15 million K, too cool by classical physics for protons to fuse. Fusion still happens thanks to", ["magnetism", "quantum tunnelling", "gravity alone", "neutrinos"], 1, "Protons can sneak through the electric barrier."],
    ["Neutrinos are", ["heavy and slow", "almost massless and barely interact with anything", "charged", "made of quarks"], 1, "Trillions pass through you every second."],
    ["The positron (anti-electron) was predicted by", ["Einstein", "Dirac", "Bohr", "Newton"], 1, "Discovered by Carl Anderson in 1932."],
    ["The Higgs boson was discovered at CERN in", ["1964", "2000", "2012", "2020"], 2, "Predicted in 1964."],
    ["Bosons are named after which Indian physicist?", ["C. V. Raman", "Satyendra Nath Bose", "Meghnad Saha", "Homi Bhabha"], 1, "Bose's 1924 work, extended by Einstein."],
    ["For a single radioactive atom, the moment of decay", ["is fixed", "is completely random", "is exactly the half-life", "never comes"], 1, "Half-life only describes large numbers of atoms."],
    ["1 electronvolt equals", ["1 J", "1.6 × 10⁻¹⁹ J", "9.1 × 10⁻³¹ J", "931 MeV"], 1, "The energy an electron gains across 1 volt."],
    ["Doping silicon with phosphorus makes it", ["p-type", "n-type", "an insulator", "a superconductor"], 1, "Extra electrons are the majority carriers."],
    ["An LED's colour is decided by", ["the plastic cap", "the energy band gap of its semiconductor", "the current", "the voltage only"], 1, "Blue LEDs were so hard to make that they won the 2014 Nobel Prize."],
    ["C. V. Raman won the 1930 Nobel Prize for discovering", ["X-rays", "the Raman effect in scattered light", "electrons", "radio"], 1, "India celebrates 28 February as National Science Day for it."]
  ]}
];
