/* Mission: ISRO Ready. Roadmap, study plan, tiered Q&A with step-by-step answers, generators and charts. */
(function () {
  const gen = G.gen, sig = G.sig, MU = 3.986e14, RE = 6.371e6;

  /* ---------- hand-written Q&A: lv 1 Launchpad, 2 Orbit, 3 Deep space, 4 Mission control ---------- */
  DATA.ready = [
    // Launchpad
    { lv: 1, q: "Why does ISRO launch rockets from Sriharikota?", o: ["It is near the equator and on the east coast, so rockets fly east over the sea", "It has the tallest mountain in India", "Its air has less oxygen", "It is closest to the Moon"], a: 0,
      steps: ["Earth spins eastward. At Sriharikota (about 13.7°N) the ground already moves at roughly 450 m/s. Launching east adds this speed for free.", "Launching east from the east coast means the rocket flies over the Bay of Bengal, so falling stages land safely in the sea.", "Being closer to the equator also makes it cheaper to reach geostationary orbit, which sits above the equator."], tip: "Rockets want free speed and a safe place to drop their empty stages." },
    { lv: 1, q: "What does PSLV stand for?", o: ["Polar Satellite Launch Vehicle", "Primary Space Launch Vehicle", "Powered Satellite Lift Vehicle", "Planetary Science Launch Vehicle"], a: 0,
      steps: ["PSLV = Polar Satellite Launch Vehicle.", "It was designed to put Earth-observation satellites into polar, sun-synchronous orbits.", "It proved so flexible that it also launched Chandrayaan-1, Mangalyaan and Aditya-L1."], tip: "Polar orbits pass over every part of Earth as the planet turns below." },
    { lv: 1, q: "Which ISRO rocket launched Chandrayaan-3?", o: ["LVM3 (Launch Vehicle Mark-3)", "PSLV", "SLV-3", "a SpaceX Falcon 9"], a: 0,
      steps: ["LVM3 is ISRO's heaviest rocket, with two solid boosters, a liquid core stage and a cryogenic upper stage.", "A human-rated version (HLVM3) has been prepared for the Gaganyaan programme."], tip: "Heavier payloads and farther destinations need bigger rockets." },
    { lv: 1, q: "Why do rockets have several stages?", o: ["To throw away empty fuel tanks and engines, so the rest is lighter", "To look taller", "Because one engine cannot be switched on twice", "To carry more astronauts"], a: 0,
      steps: ["Once a tank is empty, it is dead weight.", "Dropping it means the remaining engines only push what is still useful.", "The rocket equation rewards a low final mass, so staging gives much more speed from the same fuel."], tip: "Like a relay race: each runner hands over and drops out." },
    { lv: 1, q: "What is NavIC?", o: ["India's own regional satellite navigation system", "A Mars rover", "A rocket engine", "A radio telescope"], a: 0,
      steps: ["NavIC (Navigation with Indian Constellation) is India's regional satellite navigation system, similar in idea to GPS.", "It is designed to cover India and the region around it.", "Satellite clocks and the speed of light let a receiver work out its position from signal travel times."], tip: "Position from timing: distance = speed of light × travel time." },
    { lv: 1, q: "Why do satellites need both solar panels and batteries?", o: ["Solar panels charge batteries in sunlight; batteries power the satellite in Earth's shadow", "Batteries are only for launch", "Solar panels work only at night", "Batteries make the satellite heavier on purpose"], a: 0,
      steps: ["In low Earth orbit a satellite spends up to about a third of each 90-minute lap in Earth's shadow.", "Panels make power in sunlight and also charge the batteries.", "Batteries keep everything running during the eclipse."], tip: "Every orbit has a day and a night." },
    { lv: 1, q: "What is special about a geostationary orbit?", o: ["A satellite there circles once a day above the equator, so it seems to hover over one spot", "It is the lowest possible orbit", "It passes over the poles", "Satellites there do not move at all"], a: 0,
      steps: ["At about 35,786 km above the equator, one orbit takes one sidereal day (about 23 h 56 min).", "Earth turns at the same rate, so the satellite stays above the same point.", "Dish antennas can point at it without moving. India's GSAT satellites use this orbit."], tip: "It moves at about 3.07 km/s, it just keeps pace with Earth." },
    { lv: 1, q: "What is remote sensing?", o: ["Studying Earth from far away using the light or radar it reflects or emits", "Controlling a satellite with a remote", "Sensing earthquakes by touch", "Listening to aliens"], a: 0,
      steps: ["Satellites carry cameras and radars that record reflected sunlight, heat or radar echoes.", "Different wavelengths reveal crops, water, forests, cities and ice.", "India's Cartosat, Resourcesat, Oceansat and the joint NASA-ISRO NISAR do this."], tip: "Each surface has its own 'colour fingerprint' across the spectrum." },
    { lv: 1, q: "Why did Chandrayaan-3's lander use rocket engines instead of a parachute to land?", o: ["The Moon has almost no atmosphere, so a parachute has nothing to push against", "Parachutes are too heavy", "The Moon's gravity is too strong", "Parachutes cannot be packed in space"], a: 0,
      steps: ["A parachute works by pushing on air.", "The Moon has essentially no air.", "So Vikram fired its throttleable engines to slow down from orbital speed, hovered, and touched down softly."], tip: "No air: no parachutes, no wings, no aerobraking." },
    { lv: 1, q: "What heats a spacecraft most during re-entry?", o: ["Air compressed in front of it (a shock wave), not mainly rubbing friction", "The Sun", "Its own engines", "Friction with clouds only"], a: 0,
      steps: ["At about 7.8 km/s, the air in front cannot get out of the way and is squeezed violently.", "Compressed air gets extremely hot, thousands of degrees.", "Heat shields either reflect/insulate or slowly burn away (ablate), carrying heat off."], tip: "Pump a bicycle tyre fast and the pump warms up: compression heating." },
    { lv: 1, q: "What is a sounding rocket used for?", o: ["Short up-and-down flights to study the upper atmosphere", "Carrying astronauts", "Reaching Mars", "Playing music"], a: 0,
      steps: ["It rises to a high altitude, takes measurements, and falls back without going into orbit.", "India's space programme began with one from Thumba in 1963.", "ISRO still flies its Rohini sounding rockets for research."], tip: "Suborbital: up and down, not around." },
    // Orbit
    { lv: 2, q: "What is the orbital speed of a satellite 400 km above Earth? (GM = 3.986 × 10¹⁴ m³/s², R = 6371 km)", o: ["≈ 7.67 km/s", "≈ 11.2 km/s", "≈ 3.07 km/s", "≈ 30 km/s"], a: 0,
      steps: ["Measure r from Earth's centre: r = 6371 + 400 = 6771 km = 6.771 × 10⁶ m.", "v = √(GM/r) = √(3.986 × 10¹⁴ / 6.771 × 10⁶) = √(5.887 × 10⁷).", "v ≈ 7,673 m/s ≈ 7.67 km/s. That is the ISS's speed."], tip: "Always add Earth's radius to the altitude." },
    { lv: 2, q: "About how long does the ISS (400 km up) take to go once around Earth?", o: ["≈ 92 minutes", "24 hours", "≈ 45 minutes", "≈ 12 hours"], a: 0,
      steps: ["Circumference = 2πr = 2π × 6.771 × 10⁶ m ≈ 4.254 × 10⁷ m.", "T = distance/speed = 4.254 × 10⁷ / 7,673 ≈ 5,545 s.", "≈ 92 minutes, so about 15 to 16 sunrises a day."], tip: "T = 2πr/v, or T = 2π√(r³/GM)." },
    { lv: 2, q: "Why must a geostationary satellite be above the equator?", o: ["Its orbit must be centred on Earth's centre and turn with Earth, which is only possible in the equatorial plane", "Gravity is stronger there", "It is warmer there", "ISRO rules require it"], a: 0,
      steps: ["Every orbit's plane passes through Earth's centre.", "A tilted orbit would carry the satellite north and south each day.", "Only an orbit in the equatorial plane can stay fixed over one point."], tip: "Draw the orbit plane: it always cuts through Earth's centre." },
    { lv: 2, q: "What is a sun-synchronous orbit good for?", o: ["Photographing Earth with the same sunlight angle every day", "Staying above one city", "Reaching the Sun", "Avoiding all shadows forever"], a: 0,
      steps: ["It is a near-polar orbit whose plane slowly turns about 1° per day, keeping pace with Earth's trip around the Sun.", "So the satellite crosses each latitude at the same local time daily.", "Same lighting makes it easy to compare images taken weeks apart. PSLV was built for these orbits."], tip: "Consistent shadows, easier comparison." },
    { lv: 2, q: "An engine ejects 250 kg of gas per second at 3,000 m/s. What is its thrust?", o: ["750 kN", "75 kN", "7.5 MN", "250 kN"], a: 0,
      steps: ["Thrust F = ṁ × v_e (rate of momentum thrown backwards).", "F = 250 kg/s × 3,000 m/s = 750,000 N.", "= 750 kN, enough to lift about 76 tonnes against Earth's gravity."], tip: "Newton's second and third laws together." },
    { lv: 2, q: "A cryogenic engine has an exhaust speed of 4,400 m/s. What is its specific impulse? (g₀ = 9.81 m/s²)", o: ["≈ 449 s", "≈ 4,400 s", "≈ 44.9 s", "≈ 9.81 s"], a: 0,
      steps: ["I_sp = v_e / g₀.", "I_sp = 4,400 / 9.81 ≈ 449 s.", "Kerosene engines reach roughly 300 s at sea level. Hydrogen's light molecules shoot out faster, so cryogenic stages are more efficient."], tip: "Higher I_sp means more speed from each kilogram of fuel." },
    { lv: 2, q: "Why is liquid hydrogen such a good rocket fuel despite being hard to store?", o: ["Its light molecules leave the nozzle very fast, giving high exhaust speed", "It is the heaviest fuel", "It burns without oxygen", "It is cheap and easy to handle"], a: 0,
      steps: ["At the same temperature, lighter molecules move faster (v_rms ∝ 1/√M).", "Hydrogen-oxygen exhaust is mostly light water vapour and hydrogen, so v_e is high.", "The catch: it must stay below −253 °C and its low density needs big tanks."], tip: "Kinetic theory from Class 11 explains rocket fuel!" },
    { lv: 2, q: "A signal travels up to a geostationary satellite (35,786 km) and back down. Roughly how long does that take?", o: ["≈ 0.24 s", "≈ 2.4 s", "≈ 0.024 s", "≈ 24 s"], a: 0,
      steps: ["One way: 3.5786 × 10⁷ m / 3 × 10⁸ m/s ≈ 0.119 s.", "Up and down: ≈ 0.24 s.", "That is why satellite phone calls have a noticeable delay."], tip: "t = d/c." },
    { lv: 2, q: "Why is a satellite in a lower orbit faster than one in a higher orbit?", o: ["Gravity is stronger closer in, so it must move faster to keep missing Earth", "Lower satellites have bigger engines", "Air pushes them", "They are lighter"], a: 0,
      steps: ["For a circular orbit, gravity provides the centripetal force: GMm/r² = mv²/r.", "So v = √(GM/r): smaller r, larger v.", "The Moon at 384,000 km moves at only about 1 km/s."], tip: "Closer = faster = shorter year." },
    { lv: 2, q: "What are 'apogee' and 'perigee'?", o: ["The farthest and nearest points of an orbit around Earth", "Two rocket stages", "Launch and landing sites", "Two types of fuel"], a: 0,
      steps: ["On an elliptical orbit the distance to Earth changes.", "Perigee: closest point, fastest speed. Apogee: farthest point, slowest speed.", "Chandrayaan-3 raised its apogee step by step with burns at perigee."], tip: "Burn at perigee to raise apogee." },
    { lv: 2, q: "Why did Aditya-L1 go to the L1 point instead of orbiting Earth?", o: ["From L1 the Sun is never blocked by Earth or the Moon", "L1 is closer to the Sun than Mercury", "It has no gravity at all", "It is cheaper than low Earth orbit"], a: 0,
      steps: ["L1 lies about 1.5 million km from Earth towards the Sun, where gravity and orbital motion balance.", "A spacecraft orbiting around L1 keeps the Sun in view continuously, with no eclipses.", "It can also sample the solar wind before it reaches Earth."], tip: "A front-row seat facing the Sun." },
    { lv: 2, q: "A satellite has 10 m² of solar panels at 28% efficiency near Earth. Roughly how much power do they make? (Solar constant 1,361 W/m²)", o: ["≈ 3.8 kW", "≈ 13.6 kW", "≈ 380 W", "≈ 38 kW"], a: 0,
      steps: ["Sunlight arriving: 1,361 W/m² × 10 m² = 13,610 W.", "Useful fraction: 13,610 × 0.28 ≈ 3,811 W.", "≈ 3.8 kW, when the panels face the Sun directly."], tip: "Power = intensity × area × efficiency." },
    // Deep space
    { lv: 3, q: "A rocket's exhaust speed is 3 km/s and its mass ratio (full ÷ empty) is 5. What speed change can it give? (Δv = v_e ln(m₀/m_f))", o: ["≈ 4.8 km/s", "≈ 15 km/s", "≈ 1.6 km/s", "≈ 3 km/s"], a: 0,
      steps: ["Tsiolkovsky's rocket equation: Δv = v_e ln(m₀/m_f).", "ln 5 ≈ 1.609.", "Δv = 3 × 1.609 ≈ 4.83 km/s."], tip: "Doubling the fuel does NOT double the speed: it is a logarithm." },
    { lv: 3, q: "Reaching low Earth orbit needs about 9.4 km/s of Δv once gravity and air losses are included. With v_e = 3 km/s in a single stage, what mass ratio is needed?", o: ["≈ 23", "≈ 3", "≈ 9", "≈ 100"], a: 0,
      steps: ["m₀/m_f = e^(Δv/v_e) = e^(9.4/3) = e^3.13.", "e^3.13 ≈ 23.", "Over 95% of the rocket would have to be fuel, which is almost impossible to build. Hence stages and better engines."], tip: "This one calculation explains why rockets are staged." },
    { lv: 3, q: "Why does reaching low Earth orbit take about 9.4 km/s of Δv when the orbital speed is only about 7.8 km/s?", o: ["Extra is lost fighting gravity during the climb and pushing through air", "The rocket must go twice around Earth", "Fuel gets heavier", "Because of the Moon's pull"], a: 0,
      steps: ["While climbing, some thrust just holds the rocket up against gravity (gravity loss).", "Air drag and steering also cost Δv.", "These losses add roughly 1.5 to 2 km/s. Earth's eastward spin gives a little back."], tip: "Budgets in rocketry are always Δv budgets." },
    { lv: 3, q: "Find the escape speed from the Moon. (M = 7.35 × 10²² kg, R = 1,737 km)", o: ["≈ 2.38 km/s", "≈ 11.2 km/s", "≈ 1.68 km/s", "≈ 0.24 km/s"], a: 0,
      steps: ["v = √(2GM/R).", "= √(2 × 6.674 × 10⁻¹¹ × 7.35 × 10²² / 1.737 × 10⁶) = √(5.65 × 10⁶).", "≈ 2,376 m/s. Low escape speed is why the Moon lost its atmosphere."], tip: "Escape speed = √2 × orbital speed at the same radius." },
    { lv: 3, q: "Chandrayaan-3 took about 40 days to reach the Moon, while Apollo took about 3 days. Why?", o: ["It raised its orbit in many small, fuel-saving burns instead of one big, expensive one", "The Moon was farther away in 2023", "It flew slower to avoid meteors", "It visited Mars first"], a: 0,
      steps: ["Apollo's giant Saturn V could push straight onto a fast Moon-bound path.", "Chandrayaan-3 used repeated burns near perigee to stretch its orbit step by step, then a final push towards the Moon.", "This uses Earth's gravity cleverly and saves fuel, fitting a smaller rocket."], tip: "Patience saves propellant." },
    { lv: 3, q: "A satellite camera has a 0.7 m aperture and images from 500 km at 500 nm. What is the finest ground detail it can resolve? (θ ≈ 1.22λ/D)", o: ["≈ 0.44 m", "≈ 4.4 m", "≈ 4.4 cm", "≈ 44 m"], a: 0,
      steps: ["θ = 1.22 × 500 × 10⁻⁹ / 0.7 ≈ 8.7 × 10⁻⁷ rad.", "Ground detail = θ × distance = 8.7 × 10⁻⁷ × 5 × 10⁵ m.", "≈ 0.44 m. Real cameras are also limited by their detectors and the atmosphere."], tip: "Bigger mirror, sharper photo." },
    { lv: 3, q: "Re-entering from low Earth orbit at 7.8 km/s, how much kinetic energy does each kilogram carry?", o: ["≈ 30 MJ", "≈ 3 MJ", "≈ 300 MJ", "≈ 30 kJ"], a: 0,
      steps: ["KE per kg = ½v² = ½ × (7,800)².", "= 3.04 × 10⁷ J ≈ 30 MJ.", "That is about 7 times the chemical energy in a kilogram of TNT (4.2 MJ). The heat shield must get rid of it."], tip: "Speed squared makes re-entry brutal." },
    { lv: 3, q: "How does a gravity assist speed up a spacecraft without fuel?", o: ["It steals a tiny bit of the planet's orbital momentum as it swings past", "The planet's air pushes it", "It bounces off the surface", "Gravity creates energy from nothing"], a: 0,
      steps: ["In the planet's frame the spacecraft leaves as fast as it arrived, just in a new direction.", "In the Sun's frame, the planet's motion is added, so the craft can gain speed.", "The planet slows by an unmeasurably tiny amount: momentum is conserved."], tip: "Like a ball bouncing off a moving train." },
    { lv: 3, q: "Earth and Mars line up well for a launch only every so often. What is the synodic period of Mars? (Mars year = 1.88 Earth years)", o: ["≈ 26 months", "≈ 12 months", "≈ 6 months", "≈ 5 years"], a: 0,
      steps: ["1/S = 1/T_Earth − 1/T_Mars = 1 − 1/1.88 = 0.468.", "S ≈ 2.14 years.", "≈ 26 months. Mangalyaan launched in November 2013 to catch one of these windows."], tip: "Like two runners on a track: how often does the faster lap the slower?" },
    { lv: 3, q: "A satellite approaches a ground station at 5 km/s along the line of sight, transmitting at 2.2 GHz. By how much is the received frequency shifted?", o: ["≈ +36.7 kHz", "≈ +36.7 MHz", "≈ +3.67 kHz", "≈ −36.7 kHz"], a: 0,
      steps: ["For v ≪ c: Δf = f × v/c.", "Δf = 2.2 × 10⁹ × 5 × 10³ / 3 × 10⁸.", "≈ 3.67 × 10⁴ Hz = 36.7 kHz higher (approaching raises frequency)."], tip: "The same Doppler shift gives galaxies their redshift." },
    // Mission control
    { lv: 4, q: "Derive the radius of geostationary orbit. (GM = 3.986 × 10¹⁴ m³/s², sidereal day = 86,164 s)", o: ["≈ 42,164 km from Earth's centre (35,786 km altitude)", "≈ 6,771 km", "≈ 384,400 km", "≈ 20,200 km"], a: 0,
      steps: ["Gravity supplies the centripetal force: GMm/r² = m(2π/T)²r ⇒ r³ = GMT²/4π².", "r³ = 3.986 × 10¹⁴ × (86,164)² / 39.48 ≈ 7.50 × 10²² m³.", "r ≈ 4.216 × 10⁷ m = 42,164 km. Subtract 6,378 km (equatorial radius): altitude ≈ 35,786 km."], tip: "Kepler's third law with Earth instead of the Sun." },
    { lv: 4, q: "A two-stage rocket: 100 t total. Stage 1 has 60 t propellant, 6 t structure, v_e = 2.8 km/s. Stage 2 has 25 t propellant, 3 t structure, v_e = 4.4 km/s. Payload 6 t. Find the total Δv.", o: ["≈ 8.4 km/s", "≈ 5.3 km/s", "≈ 12 km/s", "≈ 4.4 km/s"], a: 0,
      steps: ["Stage 1: m₀ = 100 t, burns 60 t → m_f = 40 t. Δv₁ = 2.8 ln(2.5) ≈ 2.57 km/s.", "Drop 6 t of empty structure → 34 t. Stage 2 burns 25 t → 9 t. Δv₂ = 4.4 ln(34/9) ≈ 5.85 km/s.", "Total ≈ 8.4 km/s. The same propellant in one stage with the kerosene engine gives only 2.8 ln(100/15) ≈ 5.3 km/s."], tip: "Staging plus a high-efficiency upper stage is the winning combination." },
    { lv: 4, q: "Estimate the minimum transfer time from Earth to Mars on a Hohmann orbit. (Mars at 1.524 AU)", o: ["≈ 259 days", "≈ 687 days", "≈ 3 months", "≈ 2 years"], a: 0,
      steps: ["The transfer ellipse touches both orbits: semi-major axis a = (1 + 1.524)/2 = 1.262 AU.", "Full ellipse period T = a^1.5 = 1.418 years. The trip is half of it.", "0.709 years ≈ 259 days. Mangalyaan's cruise was about 10 months."], tip: "Half an ellipse, timed so Mars arrives there too." },
    { lv: 4, q: "Estimate the distance from Earth to the Sun-Earth L1 point. (Hint: r ≈ R × (m/3M)^(1/3), m/M = 3.0 × 10⁻⁶, R = 1.496 × 10⁸ km)", o: ["≈ 1.5 million km", "≈ 150 million km", "≈ 384,400 km", "≈ 15,000 km"], a: 0,
      steps: ["m/3M = 1.0 × 10⁻⁶.", "Cube root: (10⁻⁶)^(1/3) = 10⁻² = 0.01.", "r ≈ 0.01 × 1.496 × 10⁸ km ≈ 1.5 × 10⁶ km. Exactly where Aditya-L1 went."], tip: "The Hill-sphere approximation: a beautiful Class 12-level estimate." },
    { lv: 4, q: "What is the free-space path loss for a 4 GHz signal over 36,000 km (geostationary link)? FSPL(dB) = 20 log₁₀(4πd/λ)", o: ["≈ 196 dB", "≈ 96 dB", "≈ 36 dB", "≈ 400 dB"], a: 0,
      steps: ["λ = c/f = 3 × 10⁸ / 4 × 10⁹ = 0.075 m.", "4πd/λ = 4π × 3.6 × 10⁷ / 0.075 ≈ 6.03 × 10⁹.", "20 log₁₀(6.03 × 10⁹) ≈ 195.6 dB. The signal arrives about 10¹⁹ times weaker, which is why dishes and amplifiers are needed."], tip: "The inverse-square law, written in decibels." },
    { lv: 4, q: "What is the minimum energy (ignoring losses) to put 1 kg into a 400 km circular orbit?", o: ["≈ 33 MJ", "≈ 3.3 MJ", "≈ 330 MJ", "≈ 33 kJ"], a: 0,
      steps: ["Kinetic energy in orbit: ½v² = ½ × (7,673)² ≈ 2.94 × 10⁷ J.", "Potential energy gained: GM(1/R − 1/r) = 3.986 × 10¹⁴ (1/6.371 × 10⁶ − 1/6.771 × 10⁶) ≈ 3.7 × 10⁶ J.", "Total ≈ 3.3 × 10⁷ J ≈ 33 MJ (about 9 kWh). The energy is cheap. Carrying the fuel to deliver it is the hard part."], tip: "Most of the cost is speed, not height." },
    { lv: 4, q: "From geostationary orbit, how wide does Earth look (angular diameter)? Why do three GEO satellites cover almost the whole planet?", o: ["≈ 17.4°; each sees about a third of the globe", "≈ 1°; they cover tiny spots", "≈ 90°; one is enough", "≈ 45°; you need eight"], a: 0,
      steps: ["Half-angle = asin(R/r) = asin(6,371/42,164) ≈ 8.7°, so Earth spans about 17.4°.", "Each GEO satellite sees nearly a whole hemisphere (up to about 81° of latitude/longitude from its point).", "Three spaced 120° apart cover everything except the polar caps, as Arthur C. Clarke proposed in 1945."], tip: "Geometry decides communication networks." },
    { lv: 4, q: "LEO (300 km) to GEO by a Hohmann transfer: roughly what total Δv is needed (ignoring plane change)?", o: ["≈ 3.9 km/s", "≈ 0.9 km/s", "≈ 11 km/s", "≈ 7.7 km/s"], a: 0,
      steps: ["r₁ = 6,671 km, r₂ = 42,164 km. v₁ = √(μ/r₁) ≈ 7.73 km/s.", "Burn 1: Δv₁ = v₁(√(2r₂/(r₁+r₂)) − 1) ≈ 2.43 km/s. Burn 2 at apogee: Δv₂ = √(μ/r₂)(1 − √(2r₁/(r₁+r₂))) ≈ 1.46 km/s.", "Total ≈ 3.9 km/s. From Sriharikota a plane change adds more, which is why GTO launches aim east near the equator."], tip: "Two burns and half an ellipse." },
    { lv: 4, q: "A sun-synchronous orbit must precess by how much each day?", o: ["≈ 0.986° eastward per day", "≈ 15° per day", "≈ 360° per day", "0°, it must not move"], a: 0,
      steps: ["Earth goes 360° around the Sun in 365.25 days.", "360/365.25 ≈ 0.986° per day.", "Earth's equatorial bulge supplies this twist naturally when the orbit is tilted at about 97 to 98°."], tip: "Earth's shape is a free steering tool." },
    { lv: 4, q: "Liquid hydrogen boils at about 20 K and liquid oxygen at about 90 K. Why is this a challenge for cryogenic stages?", o: ["Tanks need heavy insulation and fuel keeps boiling off, and metals turn brittle", "They freeze solid instantly", "They explode on contact with air only", "They are too heavy"], a: 0,
      steps: ["Heat leaking in makes the propellants boil, raising pressure and wasting fuel.", "Materials and seals must survive being cooled by hundreds of degrees.", "Mastering this took ISRO years; the indigenous cryogenic stage first flew successfully on GSLV-D5 in 2014."], tip: "Thermal physics is rocket science." }
  ];

  /* ---------- generators ---------- */
  gen("ready.rocket", 3, [[2.5, 3, 3.5, 4.4], [2, 3, 5, 8, 10]], (ve, R) => ({ q: `A rocket stage has exhaust speed ${ve} km/s and mass ratio m₀/m_f = ${R}. What Δv can it give?`, v: ve * Math.log(R), u: "km/s", w: [ve * R, ve / R, ve * Math.log10(R)], e: "Δv = v_e ln(m₀/m_f).", steps: [`ln ${R} = ${sig(Math.log(R))}`, `Δv = ${ve} × ${sig(Math.log(R))} = ${sig(ve * Math.log(R))} km/s`], c: "rocket equation" }));
  gen("ready.ratio", 3, [[3, 5, 7, 9.4], [3, 4.4]], (dv, ve) => ({ q: `What mass ratio m₀/m_f is needed for Δv = ${dv} km/s with an exhaust speed of ${ve} km/s?`, v: Math.exp(dv / ve), w: [dv / ve, Math.exp(ve / dv)], e: "m₀/m_f = e^(Δv/v_e). It grows exponentially, which is why efficient engines matter so much.", c: "rocket equation" }));
  gen("ready.thrust", 2, [[100, 200, 300, 500], [2500, 3000, 4400]], (m, v) => ({ q: `An engine throws out ${m} kg of gas per second at ${v} m/s. Find its thrust.`, v: m * v / 1000, u: "kN", w: [m * v, m / v * 1000], e: "F = ṁ v_e.", c: "thrust" }));
  gen("ready.isp", 2, [[2500, 2800, 3000, 3500, 4400]], v => ({ q: `An engine's exhaust speed is ${v} m/s. Find its specific impulse (g₀ = 9.81 m/s²).`, v: v / 9.81, u: "s", w: [v * 9.81, v / 98.1], e: "I_sp = v_e/g₀.", c: "specific impulse" }));
  gen("ready.delay", 1, [[["a geostationary satellite", 35786], ["the Moon", 384400], ["Aditya-L1 at L1", 1.5e6], ["Mars at its closest (≈ 55 million km)", 5.5e7], ["Mars at its farthest (≈ 400 million km)", 4e8]]], d => ({ q: `How long does a radio signal take to travel one way to ${d[0]}?`, v: d[1] / 3e5, u: "s", w: [d[1] / 3e5 / 60, d[1] / 3e8], e: "t = d/c. Mars is so far that rovers must drive themselves between commands.", c: "electromagnetic wave" }));
  gen("ready.panel", 2, [[2, 5, 10, 20], [0.2, 0.28, 0.3], [["near Earth", 1], ["at Mars", 1 / (1.524 * 1.524)]]], (A, eff, loc) => ({ q: `A spacecraft has ${A} m² of solar panels at ${eff * 100}% efficiency, ${loc[0]}. How much power do they give? (1,361 W/m² at Earth)`, v: 1361 * loc[1] * A * eff, u: "W", w: [1361 * A * eff, 1361 * loc[1] * A], e: "P = intensity × area × efficiency. Sunlight falls as 1/r², so Mars gets only 43% of Earth's.", c: "solar constant", lv: loc[0] === "at Mars" ? 3 : 2 }));
  gen("ready.doppler", 3, [[1, 3, 5, 7], [2.2, 8.4]], (v, f) => ({ q: `A spacecraft moves towards the antenna at ${v} km/s, transmitting at ${f} GHz. Find the frequency shift.`, v: f * 1e9 * v * 1e3 / 3e8 / 1000, u: "kHz", w: [f * 1e9 * v / 3e8 / 1000, f * v / 3e5], e: "Δf = f v/c (small speeds).", c: "Doppler effect" }));
  gen("ready.res", 3, [[0.3, 0.5, 0.7, 1], [400, 500, 700]], (D, h) => ({ q: `A satellite telescope of aperture ${D} m looks down from ${h} km at 500 nm. What is its finest ground resolution? (θ ≈ 1.22λ/D)`, v: 1.22 * 5e-7 / D * h * 1e3, u: "m", w: [5e-7 / D * h * 1e3, 1.22 * 5e-7 * D * h * 1e3], e: "Ground detail ≈ θ × altitude.", c: "remote sensing" }));
  const PL = { Venus: 0.723, Mars: 1.524, Jupiter: 5.2, Saturn: 9.58 };
  gen("ready.hohmann", 4, [Object.entries(PL)], p => { const a = (1 + p[1]) / 2, t = 0.5 * Math.pow(a, 1.5) * 365.25; return { q: `Estimate the Hohmann transfer time from Earth (1 AU) to ${p[0]} (${p[1]} AU).`, v: t, u: "days", w: [Math.pow(a, 1.5) * 365.25, 0.5 * Math.pow(p[1], 1.5) * 365.25], e: "Transfer ellipse a = (r₁ + r₂)/2; trip = half its period.", steps: [`a = (1 + ${p[1]})/2 = ${sig(a)} AU`, `T = a^1.5 = ${sig(Math.pow(a, 1.5))} years`, `trip = T/2 ≈ ${sig(t)} days`], c: "Hohmann transfer" }; });
  gen("ready.synodic", 4, [[["Mercury", 0.241], ["Venus", 0.615], ["Mars", 1.881], ["Jupiter", 11.86], ["Saturn", 29.46]]], p => { const S = 1 / Math.abs(1 - 1 / p[1]); return { q: `How often do Earth and ${p[0]} (year = ${p[1]} Earth years) return to the same alignment? (synodic period)`, v: S * 12, u: "months", w: [p[1] * 12, (S / 2) * 12], e: "1/S = |1/T₁ − 1/T₂|. Launch windows repeat with this period.", c: "Kepler's third law" }; });
  gen("ready.energy", 4, [[300, 400, 500, 800]], h => { const r = RE + h * 1e3, E = 0.5 * MU / r + MU * (1 / RE - 1 / r); return { q: `Ignoring losses, what minimum energy puts 1 kg into a circular orbit ${h} km up?`, v: E / 1e6, u: "MJ", w: [0.5 * MU / r / 1e6, MU * (1 / RE - 1 / r) / 1e6], e: "E = ½v² (speed) + GM(1/R − 1/r) (height). Speed dominates.", c: "orbital speed" }; });
  gen("ready.geo", 4, [[200, 300, 400, 500]], h => { const r1 = RE + h * 1e3, r2 = 4.2164e7, v1 = Math.sqrt(MU / r1), a = (r1 + r2) / 2; const d1 = v1 * (Math.sqrt(2 * r2 / (r1 + r2)) - 1), d2 = Math.sqrt(MU / r2) * (1 - Math.sqrt(2 * r1 / (r1 + r2))); return { q: `Estimate the total Hohmann Δv to go from a ${h} km circular orbit to geostationary orbit (no plane change).`, v: (d1 + d2) / 1000, u: "km/s", w: [d1 / 1000, (v1 - Math.sqrt(MU / r2)) / 1000], e: "Two burns: one to enter the transfer ellipse, one at apogee to circularise.", steps: [`v₁ = √(μ/r₁) = ${sig(v1 / 1000)} km/s`, `Δv₁ = ${sig(d1 / 1000)} km/s, Δv₂ = ${sig(d2 / 1000)} km/s`, `total ≈ ${sig((d1 + d2) / 1000)} km/s`], c: "Hohmann transfer" }; });

  G.pool("ready", { name: "ISRO Ready", fixed: () => DATA.ready.map(x => ({ q: x.q, o: x.o, a: x.a, steps: x.steps, e: x.tip, lv: x.lv })), gens: ["ready.*", "nw.orbv", "nw.orbT", "nw.esc", "st.emc2", "hist.isro"] });

  /* ---------- view ---------- */
  const V = G.views.ready = {};
  const TIERS = [[1, "Launchpad", "easy"], [2, "Orbit", "medium"], [3, "Deep space", "hard"], [4, "Mission control", "super hard"]];
  let tier = 1;
  V.init = function () {
    const tabs = document.getElementById("qa-tabs");
    tabs.innerHTML = TIERS.map(t => `<button class="chip" type="button" data-tier="${t[0]}" aria-pressed="${t[0] === tier}">${t[1]} <span class="muted">· ${t[2]}</span></button>`).join("");
    tabs.onclick = e => { const b = e.target.closest("[data-tier]"); if (b) { tier = +b.dataset.tier; tabs.querySelectorAll("[data-tier]").forEach(x => x.setAttribute("aria-pressed", x === b)); drawQA(); } };
    drawQA();
  };
  function drawQA() {
    const list = DATA.ready.filter(x => x.lv === tier);
    const box = document.getElementById("qa-list");
    box.innerHTML = list.map((x, i) => `<details class="qa">
      <summary><span class="qa-n mono">${String(i + 1).padStart(2, "0")}</span><span class="qa-q">${x.q}</span><span class="qa-toggle" aria-hidden="true">+</span></summary>
      <div class="qa-body"><p class="qa-ans"><b>Answer:</b> ${x.o[x.a]}</p>
        <ol class="steps">${x.steps.map(s => `<li>${s}</li>`).join("")}</ol>
        <p class="note small"><b>Remember:</b> ${x.tip}</p></div></details>`).join("");
    box.querySelectorAll("details").forEach(d => d.addEventListener("toggle", () => { if (d.open) G.award("qa-" + tier + "-" + d.querySelector(".qa-n").textContent, 3, "Q&A read"); }));
  }
})();
