#!/usr/bin/env node
/* ============================================================
   Bundles src/ into one self-contained HTML file.

   Output:  Triton Sales Portal.html
   That file plus the "Sales Kit" folder is the entire product.

   Usage:  node tools/build.mjs
   ============================================================ */
import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = f => readFileSync(join(ROOT, f), 'utf8');

const OUT = 'Triton Sales Portal.html';

let html = read('src/index.html');
const css = read('src/fonts.css') + '\n' + read('src/styles.css');
const js  = read('src/data.js') + '\n' + read('src/app.js');

if (!html.includes('<!--STYLES-->') || !html.includes('<!--SCRIPTS-->'))
  throw new Error('src/index.html is missing its <!--STYLES--> / <!--SCRIPTS--> markers');

/* `</script>` inside a string would close the tag early — the one escape that matters */
const guard = s => s.replace(/<\/script>/gi, () => '<\\/script>');

/* Every replacement below passes a FUNCTION, never a string. A string replacement
   would treat `$$`, `$&`, `$'` and `` $` `` as substitution patterns — which silently
   rewrote `var $$ = ...` to `var $ = ...` and broke the bundle. */
html = html
  .replace('<!--STYLES-->',  () => '<style>\n' + css + '\n</style>')
  .replace('<!--SCRIPTS-->', () => '<script>\n' + guard(js) + '\n</script>')
  .replace('<!DOCTYPE html>', () =>
    '<!DOCTYPE html>\n<!-- Triton Group — Offline Sales Portal\n' +
    '     Built ' + new Date().toISOString().slice(0, 10) + ' from src/. Do not edit this file\n' +
    '     by hand; edit src/ and run: node tools/build.mjs -->');

/* the bundle must be byte-identical to the sources it came from */
for (const [label, src] of [['styles.css', read('src/styles.css')], ['js', js]]) {
  if (!html.includes(src)) throw new Error(`bundling altered ${label} — refusing to write`);
}

writeFileSync(join(ROOT, OUT), html, 'utf8');

const kb = (statSync(join(ROOT, OUT)).size / 1024).toFixed(0);
console.log(`\n  ✓ ${OUT}  (${kb} KB, self-contained)\n`);
console.log('  Ship this one file together with the "Sales Kit" folder.');
console.log('  They must sit next to each other.\n');
