#!/usr/bin/env node
/* ============================================================
   Bakes the webfonts into src/fonts.css as base64 @font-face
   rules, so the portal carries its own typography and needs no
   network. Run after changing the font choice:

       npm i @fontsource-variable/fraunces @fontsource/geist-sans
       node tools/embed-fonts.mjs

   The generated src/fonts.css is committed, so a normal build
   never needs npm.
   ============================================================ */
import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const NM   = join(ROOT, 'node_modules');

/* Fraunces carries the headings — a variable serif with optical sizing, warm and
   high-contrast, chosen to sit beside the gold Didone logo without imitating it.
   Geist does the working text. Latin only; that is all the kit needs. */
const FACES = [
  { family: 'Fraunces', weight: '100 900', style: 'normal',
    file: '@fontsource-variable/fraunces/files/fraunces-latin-wght-normal.woff2' },
  { family: 'Geist', weight: 400, style: 'normal',
    file: '@fontsource/geist-sans/files/geist-sans-latin-400-normal.woff2' },
  { family: 'Geist', weight: 500, style: 'normal',
    file: '@fontsource/geist-sans/files/geist-sans-latin-500-normal.woff2' },
  { family: 'Geist', weight: 600, style: 'normal',
    file: '@fontsource/geist-sans/files/geist-sans-latin-600-normal.woff2' }
];

let css = '/* Generated by tools/embed-fonts.mjs — do not edit by hand. */\n';
let total = 0;

for (const f of FACES) {
  const path = join(NM, f.file);
  const bytes = readFileSync(path);
  total += statSync(path).size;
  css += `@font-face{font-family:'${f.family}';font-style:${f.style};` +
         `font-weight:${f.weight};font-display:swap;` +
         `src:url(data:font/woff2;base64,${bytes.toString('base64')}) format('woff2')}\n`;
}

writeFileSync(join(ROOT, 'src/fonts.css'), css, 'utf8');
console.log(`\n  ✓ src/fonts.css — ${FACES.length} faces, ` +
            `${(total / 1024).toFixed(0)} KB of font data ` +
            `(${(css.length / 1024).toFixed(0)} KB base64)\n`);
